"""
AUTO-GENERATED: EchoBot TypeSpec compliance tests.
Generated from: specs/typespec/messages.tsp

Verifies that EchoBot conforms to Agent Framework Protocol specification.
Tests cover:
- Message structure (ChatMessage, role, contents)
- Required properties (messageId, role, contents)
- XML/JSON serialization
- Content type support
- Message ID preservation

DO NOT EDIT THIS FILE MANUALLY.
Regenerate with: python scripts/generation/generate-tests.py --compliance
"""

import pytest
from datetime import datetime
from typing import List

# Note: These imports will need to be adjusted based on actual package structure
# from microsoft.agents.xml.generated.models import (
#     UserMessage, AgentMessage, SystemMessage, DeveloperMessage,
#     ToolMessage, ChannelMessage, TextContent, ChatRole
# )
# from microsoft.agents.xml.core.serialization import MessageSerializer


@pytest.fixture
def client():
    """Create test client for the echo bot."""
    # TODO: Implement client fixture based on the web framework used
    # This will vary depending on whether using aiohttp, Flask, or FastAPI
    import aiohttp
    from aiohttp import web
    import asyncio

    # Import the echo bot application
    # from python.samples.echo_bot.src.app import app

    # For now, return a mock client
    pytest.skip("Client fixture not yet implemented")


@pytest.fixture
def serializer():
    """Create XML serializer."""
    # from microsoft.agents.xml.core.serialization import MessageSerializer
    # return MessageSerializer()
    pytest.skip("Serializer not yet implemented")


class TestEchoBotCompliance:
    """EchoBot TypeSpec compliance tests."""

    # Message Structure Tests

    @pytest.mark.asyncio
    async def test_echobot_accepts_valid_user_message(self, client, serializer):
        """Test that EchoBot accepts valid UserMessage per TypeSpec."""
        # Arrange: Create valid UserMessage per TypeSpec
        message = {
            "type": "user",
            "message_id": "msg_compliance_001",
            "user_id": "user_test_123",
            "created_at": datetime.utcnow().isoformat(),
            "contents": [
                {"type": "text", "text": "Hello EchoBot"}
            ]
        }

        xml = serializer.serialize(message)

        # Act: POST to /api/messages
        response = await client.post("/api/messages", data=xml,
                                    headers={"Content-Type": "application/xml"})

        # Assert: 200 OK with AgentMessage
        assert response.status == 200

        response_xml = await response.text()
        response_message = serializer.deserialize(response_xml)

        assert response_message is not None
        assert response_message["type"] == "agent"
        assert "message_id" in response_message
        assert len(response_message["contents"]) > 0

    @pytest.mark.asyncio
    async def test_echobot_requires_message_id(self, client):
        """Test that messageId is required per TypeSpec."""
        # Arrange: Create UserMessage WITHOUT messageId (invalid per TypeSpec)
        xml = """
            <user user-id="user_123">
                <text>Hello</text>
            </user>"""

        # Act: POST to /api/messages
        response = await client.post("/api/messages", data=xml,
                                    headers={"Content-Type": "application/xml"})

        # Assert: 400 Bad Request (messageId is required per TypeSpec)
        assert response.status == 400, "messageId is marked as required (@key) in TypeSpec"

    @pytest.mark.asyncio
    async def test_echobot_preserves_message_structure(self, client, serializer):
        """Test that EchoBot preserves message structure."""
        # Arrange
        message = {
            "type": "user",
            "message_id": "msg_preserve_001",
            "user_id": "user_test_456",
            "author_name": "Test User",
            "created_at": "2026-02-07T10:00:00Z",
            "contents": [
                {"type": "text", "text": "Test message"}
            ]
        }

        xml = serializer.serialize(message)

        # Act
        response = await client.post("/api/messages", data=xml,
                                    headers={"Content-Type": "application/xml"})
        response_xml = await response.text()
        response_message = serializer.deserialize(response_xml)

        # Assert: AgentMessage has all required ChatMessage properties
        assert "message_id" in response_message, "messageId is required per TypeSpec @key annotation"
        assert response_message["type"] == "agent", "role must match message type"
        assert len(response_message["contents"]) > 0, "contents array is required per TypeSpec"

    # Role Handling Tests

    @pytest.mark.asyncio
    async def test_echobot_handles_system_role(self, client, serializer):
        """Test that EchoBot handles system role messages."""
        # Arrange: Create system message per TypeSpec
        message = {
            "type": "system",
            "message_id": "msg_system_001",
            "contents": [
                {"type": "text", "text": "Test system role"}
            ]
        }

        xml = serializer.serialize(message)

        # Act
        response = await client.post("/api/messages", data=xml,
                                    headers={"Content-Type": "application/xml"})

        # Assert: Bot can process system messages
        assert response.status == 200, f"Bot should accept messages with role=system"

    @pytest.mark.asyncio
    async def test_echobot_handles_developer_role(self, client, serializer):
        """Test that EchoBot handles developer role messages."""
        # Arrange: Create developer message per TypeSpec
        message = {
            "type": "developer",
            "message_id": "msg_developer_001",
            "contents": [
                {"type": "text", "text": "Test developer role"}
            ]
        }

        xml = serializer.serialize(message)

        # Act
        response = await client.post("/api/messages", data=xml,
                                    headers={"Content-Type": "application/xml"})

        # Assert: Bot can process developer messages
        assert response.status == 200, f"Bot should accept messages with role=developer"

    @pytest.mark.asyncio
    async def test_echobot_handles_user_role(self, client, serializer):
        """Test that EchoBot handles user role messages."""
        # Arrange: Create user message per TypeSpec
        message = {
            "type": "user",
            "message_id": "msg_user_001",
            "contents": [
                {"type": "text", "text": "Test user role"}
            ]
        }

        xml = serializer.serialize(message)

        # Act
        response = await client.post("/api/messages", data=xml,
                                    headers={"Content-Type": "application/xml"})

        # Assert: Bot can process user messages
        assert response.status == 200, f"Bot should accept messages with role=user"

    @pytest.mark.asyncio
    async def test_echobot_handles_agent_role(self, client, serializer):
        """Test that EchoBot handles agent role messages."""
        # Arrange: Create agent message per TypeSpec
        message = {
            "type": "agent",
            "message_id": "msg_agent_001",
            "contents": [
                {"type": "text", "text": "Test agent role"}
            ]
        }

        xml = serializer.serialize(message)

        # Act
        response = await client.post("/api/messages", data=xml,
                                    headers={"Content-Type": "application/xml"})

        # Assert: Bot can process agent messages
        assert response.status == 200, f"Bot should accept messages with role=agent"

    @pytest.mark.asyncio
    async def test_echobot_handles_tool_role(self, client, serializer):
        """Test that EchoBot handles tool role messages."""
        # Arrange: Create tool message per TypeSpec
        message = {
            "type": "tool",
            "message_id": "msg_tool_001",
            "contents": [
                {"type": "text", "text": "Test tool role"}
            ]
        }

        xml = serializer.serialize(message)

        # Act
        response = await client.post("/api/messages", data=xml,
                                    headers={"Content-Type": "application/xml"})

        # Assert: Bot can process tool messages
        assert response.status == 200, f"Bot should accept messages with role=tool"

    @pytest.mark.asyncio
    async def test_echobot_handles_channel_role(self, client, serializer):
        """Test that EchoBot handles channel role messages."""
        # Arrange: Create channel message per TypeSpec
        message = {
            "type": "channel",
            "message_id": "msg_channel_001",
            "contents": [
                {"type": "text", "text": "Test channel role"}
            ]
        }

        xml = serializer.serialize(message)

        # Act
        response = await client.post("/api/messages", data=xml,
                                    headers={"Content-Type": "application/xml"})

        # Assert: Bot can process channel messages
        assert response.status == 200, f"Bot should accept messages with role=channel"


    # Content Type Tests

    @pytest.mark.asyncio
    async def test_echobot_handles_text_content(self, client, serializer):
        """Test that EchoBot handles TextContent."""
        # Arrange
        message = {
            "type": "user",
            "message_id": "msg_text_001",
            "contents": [
                {"type": "text", "text": "Hello bot!"}
            ]
        }

        # Act
        xml = serializer.serialize(message)
        response = await client.post("/api/messages", data=xml,
                                    headers={"Content-Type": "application/xml"})

        # Assert
        assert response.status == 200
        response_xml = await response.text()
        response_message = serializer.deserialize(response_xml)

        assert response_message["type"] == "agent"
        text_content = next((c for c in response_message["contents"] if c["type"] == "text"), None)
        assert text_content is not None
        assert "You said:" in text_content["text"]

    # Serialization Tests

    @pytest.mark.asyncio
    @pytest.mark.parametrize("content_type", ["application/xml", "application/json"])
    async def test_echobot_supports_content_types(self, client, serializer, content_type):
        """Test that EchoBot supports both XML and JSON."""
        # Arrange
        message = {
            "type": "user",
            "message_id": "msg_serialization_001",
            "contents": [
                {"type": "text", "text": "Test serialization"}
            ]
        }

        if "xml" in content_type:
            serialized = serializer.serialize(message)
        else:
            # TODO: Add JSON serialization support
            import json
            serialized = json.dumps(message)

        # Act
        response = await client.post("/api/messages", data=serialized,
                                    headers={"Content-Type": content_type})

        # Assert
        assert response.status == 200
        assert content_type in response.headers.get("Content-Type", "")

    @pytest.mark.asyncio
    async def test_echobot_produces_valid_xml(self, client, serializer):
        """Test that EchoBot produces valid XML per TypeSpec."""
        # Arrange
        message = {
            "type": "user",
            "message_id": "msg_xml_001",
            "contents": [
                {"type": "text", "text": "Test XML"}
            ]
        }

        xml = serializer.serialize(message)

        # Act
        response = await client.post("/api/messages", data=xml,
                                    headers={"Content-Type": "application/xml"})
        response_xml = await response.text()

        # Assert: Response is valid XML per TypeSpec schema
        response_message = serializer.deserialize(response_xml)
        assert response_message is not None, "Response must be valid XML"

        # Validate XML structure
        assert "<agent" in response_xml, "Response must be AgentMessage"
        assert "message-id=" in response_xml, "message-id attribute required"
        assert "<text>" in response_xml, "TextContent required"

    # Round-Trip Tests

    @pytest.mark.asyncio
    async def test_echobot_roundtrip_preserves_structure(self, client, serializer):
        """Test that round-trip preserves message structure."""
        # Arrange: Original message
        original = {
            "type": "user",
            "message_id": "msg_roundtrip_001",
            "user_id": "user_roundtrip_123",
            "created_at": "2026-02-07T10:00:00Z",
            "contents": [
                {"type": "text", "text": "Test round-trip"}
            ]
        }

        # Act: Serialize → Send → Receive → Deserialize
        xml_request = serializer.serialize(original)
        response = await client.post("/api/messages", data=xml_request,
                                    headers={"Content-Type": "application/xml"})
        xml_response = await response.text()
        response_message = serializer.deserialize(xml_response)

        # Assert: Response is valid AgentMessage
        assert response_message["type"] == "agent"

        # Verify structure preservation per TypeSpec
        assert "message_id" in response_message, "messageId required"
        assert response_message["type"] == "agent", "role must match type"
        assert len(response_message["contents"]) > 0, "contents required"

        # Verify XML schema compliance
        self._validate_xml_structure(xml_response)

    # Helper Methods

    def _validate_xml_structure(self, xml: str):
        """Validate XML structure."""
        import xml.etree.ElementTree as ET

        # Basic XML validation
        assert xml, "XML must not be empty"
        assert "<" in xml, "Must be valid XML"

        # Must have root element
        root = ET.fromstring(xml)
        assert root is not None, "Must have root element"

        # Must have message-id attribute
        assert root.get("message-id") is not None, "message-id is required per TypeSpec @key annotation"
