#!/bin/bash

# Generate Python types from TypeSpec definitions using Roslyn code generator
# Generates from all major TypeSpec files
# Usage: ./generate-python.sh

set -e  # Exit on error

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# Paths
TYPESPEC_DIR="$REPO_ROOT/specs/typespec"
CODEGEN_PROJECT="$REPO_ROOT/dotnet/src/Microsoft.Agents.CodeGen"
OUTPUT_BASE="$REPO_ROOT/python/microsoft-agents-abstractions/microsoft/agents"

# Check if dotnet is available
if ! command -v dotnet &> /dev/null; then
    # Try full path on macOS
    DOTNET="/usr/local/share/dotnet/dotnet"
    if [ ! -f "$DOTNET" ]; then
        echo -e "${YELLOW}Error: dotnet not found${NC}"
        exit 1
    fi
else
    DOTNET="dotnet"
fi

echo -e "${CYAN}╔════════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║       Python Type Generation from TypeSpec            ║${NC}"
echo -e "${CYAN}╚════════════════════════════════════════════════════════╝${NC}"
echo

# Clean previous generation (keep __init__.py)
echo -e "${BLUE}🧹 Cleaning previous generated files...${NC}"
find "$OUTPUT_BASE" -type f -name "*.py" ! -name "__init__.py" -delete
rm -rf "$OUTPUT_BASE/models" 2>/dev/null || true
mkdir -p "$OUTPUT_BASE/models"

# Create models __init__.py
cat > "$OUTPUT_BASE/models/__init__.py" << 'EOF'
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

"""
Generated models from TypeSpec definitions.

This module is autogenerated - DO NOT EDIT MANUALLY.
Run ./scripts/generation/generate-python.sh to regenerate.
"""

# Exports will be added during code generation
__all__ = []
EOF

# TypeSpec files to generate from (in order)
TYPESPEC_FILES=(
    "messages"      # Core message types (ChatMessage, AIContent, etc.)
    "threads"       # Thread/conversation types
    "execution"     # Run/execution types
    "tools"         # Tool/function types
    "agents"        # Agent configuration types
    "streaming"     # SSE streaming event types
    "subscriptions" # Webhook subscription types
    "common"        # Common/shared types
)

total=${#TYPESPEC_FILES[@]}
current=0

for file in "${TYPESPEC_FILES[@]}"; do
    current=$((current + 1))
    echo
    echo -e "${GREEN}[$current/$total] Generating from ${file}.tsp...${NC}"

    # Check if file exists
    if [ ! -f "$TYPESPEC_DIR/${file}.tsp" ]; then
        echo -e "${YELLOW}⚠️  Skipping ${file}.tsp (not found)${NC}"
        continue
    fi

    # Generate Python types
    $DOTNET run --project "$CODEGEN_PROJECT" --no-build -- \
      --typespec "$TYPESPEC_DIR/${file}.tsp" \
      --language python \
      --output "$OUTPUT_BASE/models" \
      --namespace "microsoft.agents" \
      2>&1 | grep -v "warning NU"  # Filter out NuGet warnings
done

echo
echo -e "${GREEN}╔════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║     ✅ Python types generated successfully!            ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════════════════╝${NC}"
echo
echo -e "${BLUE}Output directory: $OUTPUT_BASE${NC}"
echo -e "${BLUE}Generated from: ${total} TypeSpec files${NC}"
echo
echo -e "${YELLOW}📝 Note: The code generator needs Python language support.${NC}"
echo -e "${YELLOW}   If generation failed, you'll need to add Python codegen to:${NC}"
echo -e "${YELLOW}   dotnet/src/Microsoft.Agents.Xml/Microsoft.Agents.Xml.CodeGen/Program.cs${NC}"
echo
