"""
AUTO-GENERATED: Round-trip tests for content types.
Generated from TypeSpec schema at: /Users/mabolan/AgentProtocol/typespec/messages.tsp

DO NOT EDIT THIS FILE MANUALLY.
Regenerate with: python scripts/generation/generate-tests.py
"""

import pytest
from pathlib import Path
from lxml import etree
from microsoft.agents.xml.serialization import MessageSerializer


class TestGeneratedRoundTrip:
    """Auto-generated round-trip tests from TypeSpec"""

    @pytest.fixture
    def serializer(self):
        """Create message serializer"""
        return MessageSerializer()

    @pytest.fixture
    def test_data_dir(self):
        """Get test data directory"""
        return Path(__file__).parent / ".." / ".." / ".." / "test-data" / "input"

    @pytest.mark.parametrize("filename", [
    "19-refusal-content.xml",
    "20-content-filter-result-content.xml",
    "21-typing-indicator-content.xml",
    "22-message-reaction-content.xml",
    "23-message-delete-content.xml",
    "24-message-update-content.xml",
    "25-hosted-file-content.xml",
    "26-hosted-vector-store-content.xml"
    ])
    def test_roundtrip_generated(self, serializer, test_data_dir, filename):
        """
        Test serialization round-trip for generated test files.

        Each test:
        1. Loads XML from test_data/input/
        2. Deserializes to message object
        3. Serializes back to XML
        4. Compares structure (ignoring whitespace)
        """
        # Arrange
        file_path = test_data_dir / filename
        assert file_path.exists(), f"Test file not found: {file_path}"

        original_xml = file_path.read_text()

        # Act - Deserialize
        message = serializer.deserialize(original_xml)
        assert message is not None, f"Failed to deserialize {filename}"

        # Act - Serialize back
        serialized_xml = serializer.serialize(message)
        assert serialized_xml, f"Failed to serialize {filename}"

        # Assert - Compare XMLs
        self._compare_xml(original_xml, serialized_xml, filename)

        print(f"✅ {filename} - Round-trip successful")
        print(f"   Message Type: {type(message).__name__}")
        print(f"   Message ID: {message.message_id}")

    def _compare_xml(self, expected: str, actual: str, context: str):
        """
        Compare two XML strings structurally (ignoring whitespace).

        Args:
            expected: Expected XML string
            actual: Actual XML string
            context: Test context for error messages
        """
        # Parse both XMLs
        expected_tree = etree.fromstring(expected.encode('utf-8'))
        actual_tree = etree.fromstring(actual.encode('utf-8'))

        # Compare root element names
        assert expected_tree.tag == actual_tree.tag, \
            f"Root element mismatch for {context}: {expected_tree.tag} != {actual_tree.tag}"

        # Compare attributes (order-independent)
        expected_attrs = sorted(expected_tree.attrib.items())
        actual_attrs = sorted(actual_tree.attrib.items())

        assert len(expected_attrs) == len(actual_attrs), \
            f"Attribute count mismatch for {context}: {len(expected_attrs)} != {len(actual_attrs)}"

        for (exp_name, exp_value), (act_name, act_value) in zip(expected_attrs, actual_attrs):
            assert exp_name == act_name, \
                f"Attribute name mismatch in {context}: {exp_name} != {act_name}"
            assert exp_value == act_value, \
                f"Attribute value mismatch for {exp_name} in {context}: {exp_value} != {act_value}"

        # Compare text content (trimmed)
        expected_text = (expected_tree.text or "").strip()
        actual_text = (actual_tree.text or "").strip()

        if expected_text or actual_text:
            assert expected_text == actual_text, \
                f"Text content mismatch in {expected_tree.tag} for {context}: {expected_text} != {actual_text}"

        # Compare child elements recursively
        expected_children = list(expected_tree)
        actual_children = list(actual_tree)

        assert len(expected_children) == len(actual_children), \
            f"Child element count mismatch in {expected_tree.tag} for {context}: {len(expected_children)} != {len(actual_children)}"

        for exp_child, act_child in zip(expected_children, actual_children):
            self._compare_elements(exp_child, act_child, context)

    def _compare_elements(self, expected, actual, context):
        """Recursively compare XML elements"""
        # Compare element names
        assert expected.tag == actual.tag, \
            f"Element name mismatch in {context}: {expected.tag} != {actual.tag}"

        # Compare attributes
        expected_attrs = sorted(expected.attrib.items())
        actual_attrs = sorted(actual.attrib.items())

        assert expected_attrs == actual_attrs, \
            f"Attributes mismatch in {expected.tag} for {context}"

        # Compare text content
        expected_text = (expected.text or "").strip()
        actual_text = (actual.text or "").strip()

        if expected_text or actual_text:
            assert expected_text == actual_text, \
                f"Text mismatch in {expected.tag} for {context}"

        # Compare children
        expected_children = list(expected)
        actual_children = list(actual)

        assert len(expected_children) == len(actual_children), \
            f"Child count mismatch in {expected.tag} for {context}"

        for exp_child, act_child in zip(expected_children, actual_children):
            self._compare_elements(exp_child, act_child, context)
