<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Microsoft.Agents.Protocol.Abstractions/Microsoft.Agents.Protocol.Abstractions.csproj" />
    <ProjectReference Include="../Microsoft.Agents.Protocol.Runtime/Microsoft.Agents.Protocol.Runtime.csproj" />
    <ProjectReference Include="../Microsoft.Agents.Protocol.Xml/Microsoft.Agents.Protocol.Xml.csproj" />
  </ItemGroup>

</Project>
