/**
 * Extension method to add Agent Protocol routes to an Express app built with M365 Agents SDK
 *
 * This is the TypeScript equivalent of .NET's app.MapAgentProtocol()
 */

import { Express, Request, Response, NextFunction } from 'express'

// Type for agent applications (simplified interface)
interface IAgentApp {
  run(context: any): Promise<void>
}

/**
 * Adds Agent Protocol routes to an Express application.
 *
 * This method adds the following routes:
 * - GET /health - Health check endpoint
 * - GET /agent-card - Agent information endpoint
 * - POST /runs/wait - Synchronous run endpoint
 * - POST /runs/stream - Streaming run endpoint
 *
 * @param app - The Express application instance
 * @param agentApp - Optional agent application to process messages through
 * @returns The Express application with Agent Protocol routes added
 *
 * @example
 * ```typescript
 * import express from 'express'
 * import { mapAgentProtocol } from '@microsoft/agents-protocol-hosting'
 *
 * const app = express()
 * // ... set up M365 agent and /api/messages endpoint ...
 * mapAgentProtocol(app, agentApp)  // Add Agent Protocol routes with agent integration
 * ```
 */
export function mapAgentProtocol(app: Express, agentApp?: IAgentApp): Express {
  // Add CORS middleware for all Agent Protocol routes
  app.use((req: Request, res: Response, next: NextFunction): void => {
    res.header('Access-Control-Allow-Origin', '*')
    res.header('Access-Control-Allow-Methods', 'GET, POST, PUT, PATCH, DELETE, OPTIONS')
    res.header('Access-Control-Allow-Headers', '*')
    res.header('Access-Control-Expose-Headers', '*')

    // Handle preflight OPTIONS requests
    if (req.method === 'OPTIONS') {
      res.sendStatus(204)
      return
    }

    next()
  })

  // Health check endpoint
  app.get('/health', (req: Request, res: Response) => {
    res.status(200).json({ status: 'healthy' })
  })

  // Agent card endpoint
  app.get('/agent-card', (req: Request, res: Response) => {
    res.status(200).json({
      agentId: 'm365-agent',
      name: 'M365 Agent',
      description: 'Agent built with M365 Agents SDK + Agent Protocol',
      version: '1.0.0'
    })
  })

  /**
   * Helper function to build Thread XML from output messages.
   * Matches the format generated by Python's build_thread_xml.
   */
  function buildThreadXml(threadId: string, outputMessages: any[], createdAt: string, status = 'active'): string {
    const escapeXml = (str: string): string => {
      return str
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&apos;')
    }

    let xml = '<?xml version="1.0" encoding="utf-8"?>\n'
    xml += `<thread thread-id="${escapeXml(threadId)}" status="${escapeXml(status)}" created-at="${escapeXml(createdAt)}">\n`

    for (const msg of outputMessages) {
      const role = msg.role || 'agent'
      const contents = msg.contents || []

      xml += `  <${role}>\n`

      for (const content of contents) {
        const kind = content.kind || 'text'

        if (kind === 'text') {
          const audience = content.audience ? ` audience="${escapeXml(content.audience)}"` : ''
          xml += `    <text${audience}>${escapeXml(content.text || '')}</text>\n`
        } else if (kind === 'functionCall') {
          const callId = escapeXml(content.callId || '')
          const name = escapeXml(content.name || '')
          const args = escapeXml(content.arguments || '')
          xml += `    <function-call call-id="${callId}" name="${name}">${args}</function-call>\n`
        } else if (kind === 'functionResult') {
          const callId = escapeXml(content.callId || '')
          const result = escapeXml(content.result || '')
          xml += `    <function-result call-id="${callId}">${result}</function-result>\n`
        }
      }

      xml += `  </${role}>\n`
    }

    xml += '</thread>\n'
    return xml
  }

  // Runs/wait endpoint - Synchronous run
  app.post('/runs/wait', async (req: Request, res: Response) => {
    try {
      const { input, threadId, agentId } = req.body

      // Get format query parameter (default to json)
      const responseFormat = (req.query.format as string) || 'json'

      // Generate IDs
      const runId = `run_${Math.random().toString(36).substring(2, 18)}`
      const finalThreadId = threadId || `thread_${Math.random().toString(36).substring(2, 18)}`
      const finalAgentId = agentId || 'default-agent'

      // Extract text from input messages
      let userText = ''
      if (input && Array.isArray(input) && input.length > 0) {
        const firstMessage = input[0]
        if (firstMessage.contents && Array.isArray(firstMessage.contents)) {
          const textContent = firstMessage.contents.find((c: any) => c.kind === 'text')
          if (textContent) {
            userText = textContent.text
          }
        }
      }

      let outputText = `Echo: ${userText}`

      // If agentApp is provided, process through the agent
      if (agentApp && userText) {
        console.log('🔍 Agent app provided, processing through agent...')
        try {
          // Create a mock activity (matches Python's convert_to_activity)
          const activity: any = {
            type: 'message',
            text: userText,
            from: { id: 'user', name: 'User' },
            recipient: { id: 'bot', name: 'Bot' },
            conversation: { id: finalThreadId },
            channelId: 'agent-protocol',
            serviceUrl: 'https://agent-protocol',
            channelData: { role: 'user' },
            timestamp: new Date(),
            id: `msg-${Math.random().toString(36).substring(2, 18)}`,
            removeRecipientMention: () => userText
          }

          // Collect responses from the agent (matches Python's capture_send)
          const responses: string[] = []

          // Create a minimal TurnContext-like object
          const mockContext: any = {
            activity,
            sendActivity: async (activityOrText: any) => {
              const responseActivity = typeof activityOrText === 'string'
                ? { text: activityOrText, value: null }
                : activityOrText

              // Extract text from response (supports both Agent Protocol format and plain text)
              if (responseActivity.value) {
                // Agent Protocol format
                const agentMessage = responseActivity.value
                if (agentMessage.contents && Array.isArray(agentMessage.contents)) {
                  for (const content of agentMessage.contents) {
                    if (content.kind === 'text' && content.text) {
                      responses.push(content.text)
                    }
                  }
                }
              } else if (responseActivity.text) {
                responses.push(responseActivity.text)
              }
              return { id: 'mock-id' }
            },
            sendActivities: async (activities: any[]) => {
              for (const act of activities) {
                const responseActivity = typeof act === 'string' ? { text: act, value: null } : act
                if (responseActivity.value) {
                  const agentMessage = responseActivity.value
                  if (agentMessage.contents && Array.isArray(agentMessage.contents)) {
                    for (const content of agentMessage.contents) {
                      if (content.kind === 'text' && content.text) {
                        responses.push(content.text)
                      }
                    }
                  }
                } else if (responseActivity.text) {
                  responses.push(responseActivity.text)
                }
              }
              return activities.map(() => ({ id: 'mock-id' }))
            },
            turnState: new Map()
          }

          // Call agent's run method to process the turn
          await agentApp.run(mockContext)

          console.log(`✅ Agent processed. Got ${responses.length} responses:`, responses)
          if (responses.length > 0) {
            outputText = responses.join('\n')
          }
        } catch (error) {
          console.error('❌ Error running agent:')
          console.error(error)
          if (error instanceof Error) {
            console.error('Error stack:', error.stack)
          }
          outputText = `Error: ${error instanceof Error ? error.message : String(error)}`
        }
      } else {
        console.log('⚠️  No agent app provided or no user text')
      }

      // Create output response
      // CRITICAL: Agent Protocol uses "agent" role, NOT "assistant" (see TypeSpec ChatRole enum)
      const output = [{
        role: 'agent',
        createdAt: new Date().toISOString(),
        contents: [{
          kind: 'text',
          text: outputText
        }]
      }]

      const createdAt = new Date().toISOString()
      const completedAt = new Date().toISOString()

      // Return XML or JSON based on format parameter
      if (responseFormat === 'xml') {
        const xmlResponse = buildThreadXml(finalThreadId, output, createdAt, 'active')
        res.status(200).type('application/xml').send(xmlResponse)
      } else {
        // Return run result as JSON
        res.status(200).json({
          runId,
          threadId: finalThreadId,
          agentId: finalAgentId,
          status: 'completed',
          output,
          createdAt,
          completedAt
        })
      }
    } catch (error) {
      res.status(400).json({ error: String(error) })
    }
  })

  // Runs/stream endpoint - Streaming run with SSE
  app.post('/runs/stream', async (req: Request, res: Response) => {
    try {
      const { input, threadId, agentId } = req.body

      // Set SSE headers
      res.setHeader('Content-Type', 'text/event-stream')
      res.setHeader('Cache-Control', 'no-cache')
      res.setHeader('Connection', 'keep-alive')

      // Generate IDs
      const runId = `run_${Math.random().toString(36).substring(2, 18)}`
      const finalThreadId = threadId || `thread_${Math.random().toString(36).substring(2, 18)}`
      const finalAgentId = agentId || 'default-agent'

      // Extract text from input
      let userText = ''
      if (input && Array.isArray(input) && input.length > 0) {
        const firstMessage = input[0]
        if (firstMessage.contents && Array.isArray(firstMessage.contents)) {
          const textContent = firstMessage.contents.find((c: any) => c.kind === 'text')
          if (textContent) {
            userText = textContent.text
          }
        }
      }

      // Helper to send SSE events
      let eventSeq = 0
      const sendEvent = (eventName: string, data: any) => {
        eventSeq++
        const eventData = { ...data, eventSeq }
        res.write(`event: ${eventName}\ndata: ${JSON.stringify(eventData)}\n\n`)
      }

      // Send run.created event
      sendEvent('run.created', {
        runId,
        threadId: finalThreadId,
        agentId: finalAgentId,
        status: 'queued',
        createdAt: new Date().toISOString()
      })

      // Send run.started event
      sendEvent('run.started', {
        runId,
        threadId: finalThreadId,
        agentId: finalAgentId,
        status: 'running'
      })

      let responseText = `Echo: ${userText}`

      // If agentApp is provided, process through the agent
      if (agentApp && userText) {
        try {
          // Create a mock activity (matches Python's convert_to_activity)
          const activity: any = {
            type: 'message',
            text: userText,
            from: { id: 'user', name: 'User' },
            recipient: { id: 'bot', name: 'Bot' },
            conversation: { id: finalThreadId },
            channelId: 'agent-protocol',
            serviceUrl: 'https://agent-protocol',
            channelData: { role: 'user' },
            timestamp: new Date(),
            id: `msg-${Math.random().toString(36).substring(2, 18)}`,
            removeRecipientMention: () => userText
          }

          // Collect responses from the agent (matches Python's capture_send)
          const responses: string[] = []

          // Create a minimal TurnContext-like object
          const mockContext: any = {
            activity,
            sendActivity: async (activityOrText: any) => {
              const responseActivity = typeof activityOrText === 'string'
                ? { text: activityOrText, value: null }
                : activityOrText

              if (responseActivity.value) {
                const agentMessage = responseActivity.value
                if (agentMessage.contents && Array.isArray(agentMessage.contents)) {
                  for (const content of agentMessage.contents) {
                    if (content.kind === 'text' && content.text) {
                      responses.push(content.text)
                    }
                  }
                }
              } else if (responseActivity.text) {
                responses.push(responseActivity.text)
              }
              return { id: 'mock-id' }
            },
            sendActivities: async (activities: any[]) => {
              for (const act of activities) {
                const responseActivity = typeof act === 'string' ? { text: act, value: null } : act
                if (responseActivity.value) {
                  const agentMessage = responseActivity.value
                  if (agentMessage.contents && Array.isArray(agentMessage.contents)) {
                    for (const content of agentMessage.contents) {
                      if (content.kind === 'text' && content.text) {
                        responses.push(content.text)
                      }
                    }
                  }
                } else if (responseActivity.text) {
                  responses.push(responseActivity.text)
                }
              }
              return activities.map(() => ({ id: 'mock-id' }))
            },
            turnState: new Map()
          }

          // Call agent's run method to process the turn
          await agentApp.run(mockContext)

          if (responses.length > 0) {
            responseText = responses.join('\n')
          }
        } catch (error) {
          console.error('Error running agent:', error)
          responseText = 'Error processing request through agent'
        }
      }

      // Stream response text word-by-word (matches Python implementation)
      if (responseText) {
        const words = responseText.split(/\s+/)
        for (let i = 0; i < words.length; i++) {
          const chunk = i === 0 ? words[i] : ' ' + words[i]
          sendEvent('message.delta', {
            runId,
            threadId: finalThreadId,
            agentId: finalAgentId,
            delta: {
              role: 'assistant',
              contents: [{ kind: 'text', text: chunk }]
            }
          })
          await new Promise(resolve => setTimeout(resolve, 30))
        }
      }

      // Send run.completed event
      sendEvent('run.completed', {
        runId,
        threadId: finalThreadId,
        agentId: finalAgentId,
        status: 'completed',
        output: [{
          role: 'assistant',
          createdAt: new Date().toISOString(),
          contents: [{ kind: 'text', text: responseText }]
        }],
        completedAt: new Date().toISOString()
      })

      res.end()
    } catch (error) {
      res.status(400).json({ error: String(error) })
    }
  })

  return app
}
