"""
AUTO-GENERATED: Thread validation tests.
Generated from C# validation test patterns.

Tests Thread validation rules:
- Required ThreadId field
- Message ordering
- Temporal consistency
- Message ID uniqueness

DO NOT EDIT THIS FILE MANUALLY.
Regenerate with validation test generator.
"""

import pytest
from datetime import datetime, timedelta
from microsoft.agents.protocol.models import (
    Thread,
    UserMessage,
    AgentMessage,
    TextContent,
)
from microsoft.agents.protocol.validation import (
    ThreadValidator,
    ValidationErrorCode,
)


class TestThreadValidation:
    """Tests for Thread validation."""

    def setup_method(self):
        """Set up test fixtures."""
        self.validator = ThreadValidator()

    def test_validate_valid_thread_returns_success(self):
        """Test that a valid thread passes validation."""
        # Arrange
        now = datetime.utcnow()
        thread = Thread(
            thread_id="thread_001",
            created_at=now - timedelta(minutes=5),
            messages=[
                UserMessage(
                    message_id="msg_001",
                    created_at=now - timedelta(minutes=4),
                    contents=[TextContent(text="Hello")]
                ),
                AgentMessage(
                    message_id="msg_002",
                    created_at=now - timedelta(minutes=3),
                    contents=[TextContent(text="Hi there!")]
                ),
            ]
        )

        # Act
        result = self.validator.validate(thread)

        # Assert
        assert result.is_valid

    def test_validate_missing_thread_id_returns_error(self):
        """Test that missing ThreadId returns validation error."""
        # Arrange
        thread = Thread(
            thread_id="",
            created_at=datetime.utcnow(),
            messages=[]
        )

        # Act
        result = self.validator.validate(thread)

        # Assert
        assert not result.is_valid

    def test_validate_duplicate_message_ids_returns_error(self):
        """Test that duplicate message IDs return validation error."""
        # Arrange
        now = datetime.utcnow()
        thread = Thread(
            thread_id="thread_001",
            created_at=now,
            messages=[
                UserMessage(
                    message_id="msg_001",
                    created_at=now,
                    contents=[TextContent(text="Hello")]
                ),
                UserMessage(
                    message_id="msg_001",  # Duplicate!
                    created_at=now,
                    contents=[TextContent(text="World")]
                ),
            ]
        )

        # Act
        result = self.validator.validate(thread)

        # Assert
        assert not result.is_valid

    def test_validate_messages_out_of_order_returns_error(self):
        """Test that messages not in chronological order fail validation."""
        # Arrange
        now = datetime.utcnow()
        thread = Thread(
            thread_id="thread_001",
            created_at=now - timedelta(minutes=5),
            messages=[
                UserMessage(
                    message_id="msg_001",
                    created_at=now,  # Later timestamp
                    contents=[TextContent(text="Hello")]
                ),
                UserMessage(
                    message_id="msg_002",
                    created_at=now - timedelta(minutes=1),  # Earlier timestamp
                    contents=[TextContent(text="World")]
                ),
            ]
        )

        # Act
        result = self.validator.validate(thread)

        # Assert
        assert not result.is_valid
