"""
Tests for test generation scripts (scripts/testgen/).

Critical: These tests must NOT write to actual test directories or
pollute generated test files.
"""

import subprocess
import sys
from pathlib import Path

import pytest

# Get path to scripts directory
SCRIPTS_DIR = Path(__file__).parent.parent
TESTGEN_DIR = SCRIPTS_DIR / "testgen"


def run_script(script_path, args=None, cwd=None):
    """Run a script as subprocess"""
    cmd = [sys.executable, str(script_path)]
    if args:
        cmd.extend(args)

    result = subprocess.run(
        cmd,
        capture_output=True,
        text=True,
        cwd=cwd
    )
    return result


class TestGenerateTests:
    """Test generate_tests.py interface"""

    def test_help_flag_works(self):
        """--help should show usage"""
        result = run_script(TESTGEN_DIR / "generate_tests.py", ["--help"])

        assert result.returncode == 0
        # The actual description is "Generate serialization tests from TypeSpec"
        assert "Generate" in result.stdout and "tests" in result.stdout and "TypeSpec" in result.stdout
        assert "Examples:" in result.stdout or "Usage:" in result.stdout

    def test_help_shows_test_type_flags(self):
        """Help should document all test type flags"""
        result = run_script(TESTGEN_DIR / "generate_tests.py", ["--help"])

        # Should show the new clear flags
        assert "--property" in result.stdout
        assert "--enum" in result.stdout
        assert "--roundtrip" in result.stdout
        assert "--compliance" in result.stdout

        # Should NOT show old confusing phase flags
        assert "--phase1" not in result.stdout.lower()
        assert "--phase1-only" not in result.stdout.lower()

    def test_help_explains_default_behavior(self):
        """Help should explain what happens with no flags"""
        result = run_script(TESTGEN_DIR / "generate_tests.py", ["--help"])

        # Should explain that all tests are generated by default
        output = result.stdout.lower()
        assert "default" in output or "all" in output

    def test_language_flags_documented(self):
        """Language selection flags should be documented (or tests generate for all languages)"""
        result = run_script(TESTGEN_DIR / "generate_tests.py", ["--help"])

        # Note: generate_tests.py generates for ALL languages by design
        # So it doesn't need language selection flags
        # This test just verifies help works
        assert result.returncode == 0

    def test_dry_run_flag_exists(self):
        """MUST have --dry-run - file-modifying scripts require it"""
        result = run_script(TESTGEN_DIR / "generate_tests.py", ["--help"])

        # REQUIRED: All file-modifying scripts must have --dry-run
        assert "--dry-run" in result.stdout, \
            "generate_tests.py modifies files and MUST have --dry-run flag"

    def test_all_flag_documented(self):
        """--all flag should be documented"""
        result = run_script(TESTGEN_DIR / "generate_tests.py", ["--help"])

        # Should have --all to force regeneration
        assert "--all" in result.stdout.lower()


class TestGenerateTestsSafety:
    """Test that generate_tests.py doesn't pollute actual test files"""

    def test_dry_run_doesnt_write_files(self, temp_project_root, mock_typespec_file):
        """--dry-run MUST not create any test files"""
        # REQUIRED: Must have --dry-run for testing
        result = run_script(TESTGEN_DIR / "generate_tests.py", ["--help"])
        assert "--dry-run" in result.stdout, \
            "Cannot test safely without --dry-run flag"

        # Track initial state
        test_dirs = [
            temp_project_root / "dotnet" / "tests",
            temp_project_root / "python" / "tests",
            temp_project_root / "typescript" / "tests"
        ]

        for test_dir in test_dirs:
            test_dir.mkdir(parents=True, exist_ok=True)

        initial_files = {}
        for test_dir in test_dirs:
            if test_dir.exists():
                initial_files[test_dir] = set(test_dir.rglob("*.py")) | set(test_dir.rglob("*.cs")) | set(test_dir.rglob("*.ts"))

        # Run with --dry-run
        result = run_script(
            TESTGEN_DIR / "generate_tests.py",
            ["--dry-run", "--typespec", str(mock_typespec_file.parent)],
            cwd=temp_project_root
        )

        # Check no files were created
        for test_dir in test_dirs:
            if test_dir.exists():
                final_files = set(test_dir.rglob("*.py")) | set(test_dir.rglob("*.cs")) | set(test_dir.rglob("*.ts"))
                assert final_files == initial_files.get(test_dir, set()), f"dry-run should not create files in {test_dir}"


class TestTestGenFlags:
    """Test that test generation flags work correctly"""

    def test_property_flag_exists(self):
        """--property flag should be documented"""
        result = run_script(TESTGEN_DIR / "generate_tests.py", ["--help"])
        assert "--property" in result.stdout

    def test_enum_flag_exists(self):
        """--enum flag should be documented"""
        result = run_script(TESTGEN_DIR / "generate_tests.py", ["--help"])
        assert "--enum" in result.stdout

    def test_roundtrip_flag_exists(self):
        """--roundtrip flag should be documented"""
        result = run_script(TESTGEN_DIR / "generate_tests.py", ["--help"])
        assert "--roundtrip" in result.stdout

    def test_compliance_flag_exists(self):
        """--compliance flag should be documented"""
        result = run_script(TESTGEN_DIR / "generate_tests.py", ["--help"])
        assert "--compliance" in result.stdout


class TestExitCodes:
    """Test testgen script exit codes"""

    def test_help_exits_zero(self):
        """--help should exit with 0"""
        result = run_script(TESTGEN_DIR / "generate_tests.py", ["--help"])
        assert result.returncode == 0

    def test_invalid_args_exit_nonzero(self):
        """Invalid arguments should fail"""
        result = run_script(TESTGEN_DIR / "generate_tests.py", ["--invalid-xyz"])
        assert result.returncode != 0
