# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

"""
Microsoft Agents Abstractions

Core message models and content types for the Microsoft Agents Framework.
All models in this package are autogenerated from TypeSpec definitions.
"""

__version__ = "0.1.0"

# Models will be generated here from TypeSpec
# from .models import (
#     ChatMessage,
#     SystemMessage,
#     DeveloperMessage,
#     UserMessage,
#     AgentMessage,
#     ToolMessage,
#     ChannelMessage,
#     AIContent,
#     TextContent,
#     ImageContent,
#     # ... etc
# )

__all__ = [
    # Will be populated by code generation
]
