# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T00:09:57Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from typing import Union

from .text_content import TextContent
from .function_call_content import FunctionCallContent
from .function_result_content import FunctionResultContent
from .error_content import ErrorContent
from .text_reasoning_content import TextReasoningContent
from .data_content import DataContent
from .uri_content import UriContent
from .image_content import ImageContent
from .audio_content import AudioContent
from .transcript_content import TranscriptContent
from .video_content import VideoContent
from .file_content import FileContent
from .search_result_content import SearchResultContent
from .document_content import DocumentContent
from .adaptive_card_content import AdaptiveCardContent
from .refusal_content import RefusalContent
from .content_filter_result_content import ContentFilterResultContent
from .user_input_request_content import UserInputRequestContent
from .suggested_actions_content import SuggestedActionsContent
from .event_content import EventContent
from .trace_content import TraceContent
from .action_content import ActionContent
from .typing_indicator_content import TypingIndicatorContent
from .message_reaction_content import MessageReactionContent
from .message_delete_content import MessageDeleteContent
from .message_update_content import MessageUpdateContent
from .hosted_file_content import HostedFileContent
from .hosted_vector_store_content import HostedVectorStoreContent


# Additional properties for extensibility.
NOT SERIALIZED: Client-side metadata, transient state.
EXAMPLES:
- Tracking IDs, correlation data
- Client-specific rendering hints
- Temporary computation results
AIContent = Union[
    TextContent,
    FunctionCallContent,
    FunctionResultContent,
    ErrorContent,
    TextReasoningContent,
    DataContent,
    UriContent,
    ImageContent,
    AudioContent,
    TranscriptContent,
    VideoContent,
    FileContent,
    SearchResultContent,
    DocumentContent,
    AdaptiveCardContent,
    RefusalContent,
    ContentFilterResultContent,
    UserInputRequestContent,
    SuggestedActionsContent,
    EventContent,
    TraceContent,
    ActionContent,
    TypingIndicatorContent,
    MessageReactionContent,
    MessageDeleteContent,
    MessageUpdateContent,
    HostedFileContent,
    HostedVectorStoreContent
]
