# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T06:40:43Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from typing import Union, TYPE_CHECKING

if TYPE_CHECKING:
    from .prompt_agent import PromptAgent


AgentDefinition = Union["PromptAgent"]
