# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T00:10:05Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from typing import Union

from .prompt_agent import PromptAgent
from .container_agent import ContainerAgent
from .coming import Coming
from .soon import soon
from .workflow import Workflow
from .coming import Coming
from .soon import soon


AgentDefinition = Union[PromptAgent, ContainerAgent, Coming, soon, Workflow, Coming, soon]
