# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T00:10:07Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any
from datetime import datetime

from .message_filters import MessageFilters


@dataclass
class AgentSubscription:
    # Unique subscription identifier.
GENERATED: Server-generated GUID
    subscription_id: str
    # Agent being subscribed to.
    agent_id: str
    # Webhook URL to POST notifications to.
REQUIRED: Must be HTTPS endpoint

WEBHOOK PAYLOAD EXAMPLE:
{
"type": "agent.activity",
"resourceId": "agent-123",
"subscriptionId": "sub-456",
"eventType": "run.started" | "message.created" | "agent.updated",
"sequenceNumber": 42,
"eventSeq": 1587,
"timestamp": "2026-02-06T10:00:00Z"
}

CLIENT ACTION: GET /agents/{agentId} or GET /runs/{runId} to fetch latest state
    webhook_url: str
    # Secret for webhook signature validation.
OPTIONAL: For webhook authenticity verification

PATTERN: Like GitHub webhook secrets (HMAC-SHA256 signature)
    webhook_secret: Optional[str] = None
    # Event types to subscribe to.
DEFAULT: All agent events if omitted

EVENT TYPES:
- "message.created": New message from agent
- "message.updated": Message streaming chunk
- "message.completed": Message streaming finished
- "run.created": Run created for this agent
- "run.started": Run started
- "run.completed": Run completed
- "run.failed": Run failed
- "run.cancelled": Run cancelled
- "run.timeout": Run timed out
- "run.requires_action": Run needs action
- "run.input_required": Run needs input
- "agent.created": Agent registered
- "agent.updated": Agent config changed
- "agent.deleted": Agent removed
- "agent.enabled": Agent enabled
- "agent.disabled": Agent disabled
- "agent.error": Agent error occurred

RATIONALE: Allow filtering to reduce notification volume
    events: Optional[List[str]] = None
    # Filter by specific thread.
OPTIONAL: Only notify for activity in this thread

RATIONALE: Narrow agent monitoring to specific conversation
    thread_id: Optional[str] = None
    # Message filters for webhook subscriptions.
OPTIONAL: Filter which messages trigger notifications

RATIONALE: Reduce noise by filtering out irrelevant messages
    message_filters: Optional[MessageFilters] = None
    # Subscription expiration time.
OPTIONAL: Subscription automatically deleted after this time

DEFAULT: No expiration (permanent until explicitly deleted)
    expires_at: Optional[datetime] = None
    # Whether subscription is currently active.
DEFAULT: true

RATIONALE: Allows temporary disable without deletion
    active: Optional[bool] = None
    # Timestamp when subscription was created.
    created_at: datetime
    # Timestamp of last successful webhook delivery.
UPDATED: By server after successful POST (HTTP 200-299)
    last_delivered_at: Optional[datetime] = None
    # Number of consecutive failed delivery attempts.
INCREMENTED: On failed webhook POST (timeout, 4xx, 5xx)
RESET: On successful delivery

RATIONALE: Automatic subscription disable after max failures
    failure_count: Optional[int] = None
    # Custom metadata for subscription.
FLEXIBLE: Client can store correlation IDs, user info, etc.
    metadata: Optional[Dict[str, Any]] = None
