# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T06:40:48Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any
from datetime import datetime

from .input_token_details import InputTokenDetails
from .output_token_details import OutputTokenDetails
from .request_usage import RequestUsage


@dataclass
class AggregatedUsage:
    """
    Usage Aggregation
FROM: OpenAI Agents SDK (Usage)
SOURCE: /openai-agents-python/src/agents/usage.py
ADDITION: Not in MAF or Azure Agent API
RATIONALE: Aggregates usage across multiple requests in a run
M365: Run-level cost tracking and quota enforcement
    """
    input_tokens: int
    output_tokens: int
    requests: int
    total_tokens: int
    input_token_details: Optional[InputTokenDetails] = None
    output_token_details: Optional[OutputTokenDetails] = None
    request_usage_entries: Optional[List[RequestUsage]] = None
