# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T06:40:46Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any
from datetime import datetime


@dataclass(kw_only=True)
class ApiKeyConnection:
    """
    API Key Connection
ALIGNED WITH: Agent Schema ApiKeyConnection
SOURCE: https://github.com/microsoft/AgentSchema (agentschema/model/connection.tsp)
RATIONALE: API key-based authentication
MESSAGING APP PATTERN:
- Like Slack/Teams bot tokens
- Simple key-based auth
    """
    # API key value.
    # ALIGNED WITH: Agent Schema ApiKeyConnection.key
    # 
    # EXAMPLES:
    # - "sk-proj-abc123..." (OpenAI)
    # - "xoxb-..." (Slack)
    # - Bearer token
    key: str
    # Connection type discriminator.
    # ALIGNED WITH: Agent Schema Connection.kind
    kind: str
    # Optional header name.
    # DEFAULT: "Authorization"
    # 
    # EXAMPLES:
    # - "Authorization" (most common)
    # - "X-API-Key" (some APIs)
    # - "X-Custom-Auth" (custom auth)
    header_name: Optional[str] = None
    # Usage transparency description.
    # ALIGNED WITH: Agent Schema Connection.usageDescription
    usage_description: Optional[str] = None
