# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T06:40:50Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any
from datetime import datetime


@dataclass
class Assert:
    # CEL expression that evaluates to boolean.
    # 
    # RAW TEXT BLOCK: Content is not XML-escaped (no manual CDATA needed)
    # The @contentType("cel") decorator signals to the serializer that this
    # is a raw text block requiring preprocessing.
    # 
    # EXAMPLES:
    # - "t.passed"
    # - "t.passed && c.passed"
    # - "score >= 0.75 && count > 0"
    # - "run.completed && file.passed"
    expression: str
    # Minimum pass rate for repeated evaluations (0.0-1.0).
    # 
    # RATIONALE: Flaky test tolerance for non-deterministic outputs
    # 
    # DEFAULT: 1.0 (must pass every time)
    # TYPICAL: 0.8 (pass 80% of the time)
    # 
    # REQUIRES: thread.repeat > 1
    # 
    # EXAMPLE: If repeat=5 and minPassRate=0.8, must pass 4/5 runs
    min_pass_rate: Optional[float] = None
