# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T00:10:05Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any
from datetime import datetime

from .run_condition import RunCondition
from .thread_cleanup import ThreadCleanup


@dataclass
class AutoResponseConfig:
    # Condition for when agent should participate.

DEFAULT: If omitted, responds to messages with role="user"

DETERMINES: If/when agent should create run in response to thread activity
    run_condition: Optional[RunCondition] = None
    # Maximum consecutive runs before requiring user message.

DEFAULT: 1 (hard limit to prevent endless loops)

RATIONALE: Prevents agents from getting into endless loops
- 1: Agent runs once, then waits for user message (default)
- 2: Agent can respond to another agent once, then needs user input
- 0: Unlimited (dangerous - can create infinite loops)

COUNTER RESET: Counter resets when a message with role="user" arrives

EXAMPLES:
- maxConsecutiveRuns=1: User → Agent A → [STOP, wait for user]
- maxConsecutiveRuns=2: User → Agent A → Agent B → [STOP, wait for user]
- maxConsecutiveRuns=0: User → Agent A → Agent B → Agent A → ... [INFINITE LOOP]
    max_consecutive_runs: Optional[int] = None
    # Thread cleanup after participation.

@usage

Use Cases:
- Stateful conversations: Use keep (default)
- Ephemeral queries: Use delete
- One-shot tasks: Use delete

    thread_cleanup: Optional[ThreadCleanup] = None
