# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T00:10:04Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any
from datetime import datetime


@dataclass
class AutoToolChoice:
    """
    Tool Choice Behavior
FROM: Azure Agent API (ToolChoiceBehavior)
CONTROLS: How agent uses tools
MESSAGING APP ANALOGY:
- "auto": Bot decides when to use commands
- "required": Bot must use a command
- "none": Bot cannot use commands (text-only response)
- "specific": Force specific command (like /help shortcut)
    """
    kind: str
