# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T06:40:48Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any
from datetime import datetime

from .input_token_details import InputTokenDetails
from .output_token_details import OutputTokenDetails


@dataclass
class CompletionUsage:
    """
    Completion Usage
FROM: Azure Agent API (CompletionUsage) + MAF (UsageDetails)
MERGED: Azure's CompletionUsage with MAF's UsageDetails
- Azure uses camelCase and nested objects for details
- MAF uses PascalCase and flat properties
CHOSEN: Azure's structure (camelCase, nested details) for consistency with TypeSpec conventions
    """
    # Number of input/prompt tokens.
    # BASE: MAF UsageDetails.InputTokenCount (long?)
    # FROM: Azure Agent API CompletionUsage.inputTokens (int64)
    input_tokens: int
    # Number of output/completion tokens.
    # BASE: MAF UsageDetails.OutputTokenCount (long?)
    # FROM: Azure Agent API CompletionUsage.outputTokens (int64)
    output_tokens: int
    # Total tokens (input + output).
    # BASE: MAF UsageDetails.TotalTokenCount (long?)
    # FROM: Azure Agent API CompletionUsage.totalTokens (int64)
    total_tokens: int
    # Additional usage counts (provider-specific).
    # BASE: MAF UsageDetails.AdditionalCounts (AdditionalPropertiesDictionary<long>)
    # 
    # EXAMPLES: Audio tokens, image tokens, etc.
    additional_counts: Optional[Dict[str, Any]] = None
    # Input token details.
    # FROM: Azure Agent API
    input_token_details: Optional[InputTokenDetails] = None
    # Output token details.
    # FROM: Azure Agent API
    output_token_details: Optional[OutputTokenDetails] = None
