# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T06:40:46Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from typing import Union

from .reference_connection import ReferenceConnection
from .remote_connection import RemoteConnection
from .api_key_connection import ApiKeyConnection
from .anonymous_connection import AnonymousConnection


# Connection - Authentication Configuration
# @usage
# Rationale:
# - Agent Schema provides richer connection model
# - Supports multiple connection types (reference, remote, API key, anonymous)
# - Includes authority (user vs system) for consent flows
# - Provides usageDescription for transparency
Connection = Union[ReferenceConnection, RemoteConnection, ApiKeyConnection, AnonymousConnection]
