# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T00:10:11Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any
from datetime import datetime


@dataclass
class ContentCondition:
    """
    Content Condition
RATIONALE: Match based on content types in message
    """
    # Condition type discriminator.
    kind: str
    # Content types that trigger match.

EXAMPLES:
- ["video"]: Match only video messages
- ["image", "file"]: Match media uploads
    content_types: List[str] = field(default_factory=list)
