# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T00:10:10Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any
from datetime import datetime


@dataclass
class CostEstimation:
    """
    Cost Estimation
ADDITION: Not in any framework
RATIONALE: Enables cost estimation and quota enforcement
M365: Critical for cost management and budgeting
    """
    input_cost: float
    output_cost: float
    cached_cost: Optional[float] = None
    reasoning_cost: Optional[float] = None
    total_cost: float
    currency: str
    pricing_model: str
    calculated_at: datetime
