# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T06:40:38Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any
from datetime import datetime

from .ai_content_base import AIContentBase


@dataclass(kw_only=True)
class DataContent(AIContentBase):
    """
    Data Content
BASE: Microsoft.Extensions.AI.DataContent
SOURCE: /extensions/src/Libraries/Microsoft.Extensions.AI.Abstractions/Contents/DataContent.cs
REPRESENTS: Arbitrary structured data
XML: <data uri="..." mime-type="...">base64data</data>
    """
    uri: Optional[str] = None
    mime_type: Optional[str] = None
    value: Optional[str] = None

    @property
    def kind(self) -> str:
        return "data"
