# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T00:09:57Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any
from datetime import datetime

from .ai_content_base import AIContentBase


@dataclass
class EventContent(AIContentBase):
    """
    XML: <event name="..." timestamp="...">{value}</event>
    """
    name: str
    timestamp: Optional[datetime] = None
    value: Optional[str] = None

    @property
    def kind(self) -> str:
        return "event"
