# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T06:40:50Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any
from datetime import datetime

from .thread_element import ThreadElement
from .chat_message import ChatMessage
from .judge import Judge
from .assert_ import Assert


@dataclass(kw_only=True)
class Expect:
    # Reference output for comparison.
    # Expected agent response used by judges.
    # 
    # REQUIRED: All expectations must specify expected behavior
    # - Comparison judges (text_exact_match, semantic_similarity) use it for matching
    # - Other judges (text_contains, tool_call_match) receive it but may ignore it
    # 
    # USAGE: Passed to all judges
    # - Provides expected behavior documentation
    # - Used by comparison judges for evaluation
    # - May be checked by tooling/linters
    # 
    # RATIONALE: Makes test intent explicit and readable
    reference_output: ChatMessage
    # Assertions using CEL expressions.
    # Must all evaluate to true for expect block to pass.
    # 
    # EXECUTION: Evaluated after all judges complete
    # 
    # VARIABLES AVAILABLE:
    # - Judge results: {judge.as}.passed, {judge.as}.score, etc.
    # - Thread context: messages, user, agent, etc.
    asserts: List[Assert] = field(default_factory=list)
    # Judges to evaluate output.
    # Each judge produces a result stored in a variable.
    # 
    # EXECUTION: All judges run in parallel
    # 
    # RESULTS: Stored in variables (judge.as) for use in assertions
    judges: List[Judge] = field(default_factory=list)
    # Optional name for this expectation.
    # Used in error messages and reports.
    # 
    # RATIONALE: Makes test failures easier to diagnose
    # 
    # EXAMPLE: "correct_answer", "calls_weather_tool", "final_response"
    name: Optional[str] = None
