# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T06:40:49Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any
from datetime import datetime

from .run_condition import RunCondition


@dataclass(kw_only=True)
class ExpressionCondition:
    """
    Expression Condition
RATIONALE: In-process evaluation using Power Fx or CEL
    """
    # Expression for in-process evaluation.
    # 
    # @usage
    # 
    # Use Cases:
    # - Keyword matching and pattern detection
    # - Content type and role combinations
    # - Simple boolean logic without external state
    # 
    expression: str
    # Condition type discriminator.
    kind: str
