# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T06:40:38Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any
from datetime import datetime

from .ai_content_base import AIContentBase


@dataclass(kw_only=True)
class FileContent(AIContentBase):
    """
    XML: <file uri="..." filename="..." mime-type="..." size-bytes="1024" />
    """
    uri: Optional[str] = None
    filename: Optional[str] = None
    mime_type: Optional[str] = None
    size_bytes: Optional[int] = None

    @property
    def kind(self) -> str:
        return "file"
