# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T06:40:38Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any
from datetime import datetime

from .ai_content_base import AIContentBase


@dataclass(kw_only=True)
class ImageContent(AIContentBase):
    """
    Image Content
FROM: Azure Agent API (ImageContent)
ADDITION: Not in MAF
Provides three delivery methods: uri, dataUri, or raw data bytes.
M365: Future multi-modal scenarios
XML: <image uri="..." mime-type="..." width="1920" height="1080" />
    """
    uri: Optional[str] = None
    alt: Optional[str] = None
    mime_type: Optional[str] = None
    width: Optional[int] = None
    height: Optional[int] = None

    @property
    def kind(self) -> str:
        return "image"
