# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T00:10:04Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any
from datetime import datetime

from .j_s_o_n_schema import JSONSchema


@dataclass
class JSONSchema:
    """
    JSON Schema
FROM: Azure Agent API + JSON Schema Draft 7
REPRESENTS: Parameter schema for tool validation
UNIVERSAL STANDARD: Used by OpenAI, Anthropic, Azure, etc.
    """
    properties: Optional[Dict[str, Any]] = None
    items: Optional[JSONSchema] = None
    required: Optional[List[str]] = None
    description: Optional[str] = None
    format: Optional[str] = None
    minimum: Optional[float] = None
    maximum: Optional[float] = None
    min_items: Optional[int] = None
    max_items: Optional[int] = None
    pattern: Optional[str] = None
