# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T06:40:50Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from enum import Enum
from typing import Literal


class JudgeScope(str, Enum):
    """
    Judge Scope
Determines what content the judge evaluates.
SCOPES:
- last: Last agent emission only (most common)
- turn: Last agent emission + tool calls in that turn
- thread: Full thread history (all messages)
    """
    LAST = "last"
    TURN = "turn"
    THREAD = "thread"


JudgeScopeType = Literal["last", "turn", "thread"]
