# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T00:10:11Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any
from datetime import datetime


@dataclass
class MentionCondition:
    """
    Mention Condition (RunCondition-specific)
RATIONALE: Agent participates when explicitly mentioned in message
PATTERN: @agent-name or explicit agent reference
NOTE: Only explicit mentions are supported. Context-relevance
cannot be deterministically evaluated.
    """
    # Condition type discriminator.
    kind: str
    # Respond when agent is explicitly mentioned in message.

DEFAULT: true (only respond to explicit @mentions)

EXAMPLES:
- true: Requires "@AgentName" in message
- false: Any reference to agent name triggers participation
    require_explicit_mention: Optional[bool] = None
