# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T00:09:57Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any
from datetime import datetime

from .ai_content_base import AIContentBase

from .message_reaction import MessageReaction


@dataclass
class MessageReactionContent(AIContentBase):
    referenced_message_id: str
    reactions_added: Optional[List[MessageReaction]] = None
    reactions_removed: Optional[List[MessageReaction]] = None

    @property
    def kind(self) -> str:
        return "messageReaction"
