# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T06:40:44Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from typing import Union, TYPE_CHECKING

if TYPE_CHECKING:
    from .message_created_event import MessageCreatedEvent
    from .message_updated_event import MessageUpdatedEvent
    from .message_completed_event import MessageCompletedEvent


# All message-related streaming events.
# @usage
# Use to filter or handle all message events in a unified way.
# Useful for webhook subscriptions and event processing.
# @example Filter message events
# ```typescript
# if (event is MessageEvent) {
# // Handle message-related events
# }
# ```
MessageEvent = Union["MessageCreatedEvent", "MessageUpdatedEvent", "MessageCompletedEvent"]
