# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T06:40:38Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any
from datetime import datetime

from .ai_content_base import AIContentBase


@dataclass(kw_only=True)
class MessageUpdateContent(AIContentBase):
    """
    Message Update Content (Message Edit)
FROM: Activity Protocol messageUpdate activity
ADDITION: Not in MAF or Azure Agent API
REPRESENTS: Update to an existing message
MESSAGING APP PATTERN:
- Like editing a message in Slack or Teams
- Message ID references the message to update
- Updated content provided in separate ChatMessage
XML: <message-update message-id="msg_123" reason="typo_fix" />
    """
    message_id: str
    reason: Optional[str] = None

    @property
    def kind(self) -> str:
        return "messageUpdate"
