# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T00:10:07Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any
from datetime import datetime

from .a_i_content import AIContent
from .completion_usage import CompletionUsage


@dataclass
class MessageUpdatedEvent:
    run_id: Optional[str] = None
    thread_id: Optional[str] = None
    agent_id: Optional[str] = None
    message_id: str
    event_seq: int
    contents: List[AIContent] = field(default_factory=list)
    version: Optional[int] = None
    usage: Optional[CompletionUsage] = None
    updated_at: Optional[datetime] = None
