# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T06:40:45Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any
from datetime import datetime


@dataclass
class MessageFilters:
    """
    Message Filters
@usage
Filter webhook notifications by message characteristics.
Reduces notification volume by subscribing only to relevant messages.
@example Filter user messages only
```json
{
"roles": ["user"]
}
```
@example Filter messages with images or videos
```json
{
"contentTypes": ["image", "video"]
}
```
    """
    agent_ids: Optional[List[str]] = None
    audience: Optional[List[str]] = None
    content_types: Optional[List[str]] = None
    roles: Optional[List[str]] = None
    user_ids: Optional[List[str]] = None
