# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T06:40:43Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any
from datetime import datetime


@dataclass
class ModelCapabilities:
    # Function/tool calling support.
    # 
    # EXAMPLES:
    # - gpt-4o: true
    # - gpt-3.5-turbo: true
    # - claude-3-sonnet: true
    function_calling: bool
    # Maximum input tokens.
    # 
    # RATIONALE: Some models have separate input/output limits
    max_input_tokens: int
    # Maximum output tokens (generation limit).
    # 
    # EXAMPLES:
    # - gpt-4o: 16384
    # - claude-3-sonnet: 4096
    max_output_tokens: int
    # Maximum total tokens (context window).
    # 
    # EXAMPLES:
    # - gpt-4o: 128000
    # - claude-3-sonnet: 200000
    max_tokens: int
    # Model family/series.
    # 
    # EXAMPLES: "gpt-4", "claude-3", "gemini-pro"
    # 
    # RATIONALE: Useful for grouping similar models
    model_family: str
    # Parallel tool calling support (multiple tools in one turn).
    # 
    # EXAMPLES:
    # - gpt-4o: true
    # - claude-3-sonnet: true (default behavior)
    parallel_tool_calls: bool
    # Provider name.
    # 
    # EXAMPLES: "openai", "anthropic", "azure-openai", "google"
    provider: str
    # Streaming support (incremental token generation).
    # 
    # RATIONALE: All modern models support streaming
    streaming: bool
    # Structured output support (JSON schema validation).
    # 
    # EXAMPLES:
    # - gpt-4o: true (native JSON mode)
    # - claude-3-sonnet: true (via tools)
    structured_output: bool
    # Extended thinking/reasoning support.
    # 
    # EXAMPLES:
    # - o1/o3 models: true (reasoning tokens)
    # - claude-3 with extended thinking: true
    # - gpt-4o: false
    thinking: bool
    # Vision support (image understanding).
    # 
    # EXAMPLES:
    # - gpt-4o: true
    # - gpt-3.5-turbo: false
    # - claude-3-sonnet: true
    vision: bool
    # Supported content types.
    # 
    # EXAMPLES:
    # - ["text", "image"]: Vision models
    # - ["text", "image", "audio"]: Multimodal models
    # - ["text"]: Text-only models
    supported_content_types: List[str] = field(default_factory=list)
