# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T06:40:44Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from typing import Union, TYPE_CHECKING

if TYPE_CHECKING:
    from .participant_added_event import ParticipantAddedEvent
    from .participant_removed_event import ParticipantRemovedEvent


# All participant-related streaming events.
# @usage
# Use to track participant changes in threads.
ParticipantEvent = Union["ParticipantAddedEvent", "ParticipantRemovedEvent"]
