# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T06:40:44Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any
from datetime import datetime

from .participant_event import ParticipantEvent


@dataclass(kw_only=True)
class ParticipantRemovedEvent:
    event_seq: int
    participant_id: str
    removed_at: datetime
    thread_id: str
