# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T06:40:46Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any
from datetime import datetime


@dataclass
class Participant:
    # Participant identifier.
    # - For users: Entra User ID (Object ID)
    # - For agents: Agent ID (Service Principal Object ID)
    # - For system: "system"
    # 
    # ALIGNMENT: Maps to ChatMessage.userId (if type=user) or ChatMessage.agentId (if type=agent)
    id: str
    # Participant metadata.
    # FLEXIBLE: Avatar URL, status, preferences, etc.
    metadata: Optional[Dict[str, Any]] = None
    # Display name.
    # 
    # ALIGNMENT: Maps to ChatMessage.authorName
    name: Optional[str] = None
    # Role in the conversation.
    # EXAMPLES: "user", "assistant", "system"
    # 
    # FROM: OpenAI LLM APIs - standard conversation roles
    # 
    # NOTE: This is the same as ChatRole for participants
    # - Participant identifies WHO is in the conversation
    # - role identifies their function (user, assistant, system)
    role: Optional[str] = None
