# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T06:40:43Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any
from datetime import datetime

from .agent_definition import AgentDefinition
from .prompt_template import PromptTemplate
from .j_s_o_n_schema import JSONSchema
from .a_i_tool import AITool
from .tool_choice_behavior import ToolChoiceBehavior
from .auto_response_config import AutoResponseConfig


@dataclass(kw_only=True)
class PromptAgent:
    """
    Prompt Agent (Direct Execution)
ALIGNED WITH: Agent Schema PromptAgent
SOURCE: https://github.com/microsoft/AgentSchema (agentschema/model/agent.tsp)
RATIONALE: Direct execution agent with configured tools and models
    """
    # Agent type discriminator.
    # ALIGNED WITH: Agent Schema PromptAgent.kind
    kind: str
    # Auto-response configuration for thread participation.
    # 
    # @usage
    # 
    # Use Cases:
    # - Support agents: Respond to user messages in support threads
    # - Specialized agents: Respond only when mentioned or when specific content appears
    # - Monitoring agents: React to video, files, or other content types
    # 
    auto_response: Optional[AutoResponseConfig] = None
    # Agent capabilities description.
    # ALIGNED WITH: Agent Schema PromptAgent.description
    description: Optional[str] = None
    # UI display name (human-friendly).
    # ALIGNED WITH: Agent Schema PromptAgent.displayName
    # ADDITION: Not in original design
    display_name: Optional[str] = None
    # Input parameters structure.
    # ALIGNED WITH: Agent Schema PromptAgent.inputSchema
    # ADDITION: Not in original design
    # 
    # RATIONALE: Enables structured inputs with validation
    input_schema: Optional[JSONSchema] = None
    # Custom metadata.
    # ALIGNED WITH: Agent Schema PromptAgent.metadata
    metadata: Optional[Dict[str, Any]] = None
    # Unique agent identifier.
    # ALIGNED WITH: Agent Schema PromptAgent.name
    name: Optional[str] = None
    # Expected output format.
    # ALIGNED WITH: Agent Schema PromptAgent.outputSchema
    # ADDITION: Not in original design
    # 
    # RATIONALE: Enables structured outputs (OpenAI structured outputs, etc.)
    output_schema: Optional[JSONSchema] = None
    # Prompt template rendering configuration.
    # ALIGNED WITH: Agent Schema PromptAgent.template
    # ADDITION: Not in original design
    # 
    # Supports Mustache, Jinja2, and Prompty template formats.
    template: Optional[PromptTemplate] = None
    # Tool calling behavior.
    # FROM: Azure Agent API (ToolChoiceBehavior)
    tool_choice: Optional[ToolChoiceBehavior] = None
    # Available tools.
    # ALIGNED WITH: Agent Schema PromptAgent.tools
    tools: Optional[List[AITool]] = None
