# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T06:40:46Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any
from datetime import datetime


@dataclass(kw_only=True)
class ReferenceConnection:
    """
    Reference Connection
ALIGNED WITH: Agent Schema ReferenceConnection
SOURCE: https://github.com/microsoft/AgentSchema (agentschema/model/connection.tsp)
RATIONALE: Named connection reference to pre-configured connections
MESSAGING APP PATTERN:
- Like referencing a stored bot token by name
- Avoids credential duplication
- Enables connection reuse
    """
    # Connection type discriminator.
    # ALIGNED WITH: Agent Schema Connection.kind
    kind: str
    # Connection reference name.
    # ALIGNED WITH: Agent Schema ReferenceConnection.name
    # 
    # EXAMPLES: "myOpenAIConnection", "productionDB", "mcpServer"
    name: str
    # Usage transparency description.
    # ALIGNED WITH: Agent Schema Connection.usageDescription
    # 
    # RATIONALE: Shown to users for consent/transparency
    # 
    # EXAMPLE: "Access your OneDrive files to search for relevant documents"
    usage_description: Optional[str] = None
