# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T06:40:49Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any
from datetime import datetime

from .run_condition import RunCondition
from .connection import Connection


@dataclass(kw_only=True)
class RemoteCondition:
    """
    Remote Condition
RATIONALE: Custom evaluation logic via remote endpoint
    """
    # Remote endpoint for custom evaluation logic.
    # 
    # @usage
    # 
    # Use Cases:
    # - Complex business logic (checking external state, database queries)
    # - Turn-taking coordination between multiple agents
    # - Time-based or rate-limited participation
    # 
    endpoint: str
    # Condition type discriminator.
    kind: str
    # Authentication for remote endpoint.
    connection: Optional[Connection] = None
