# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T06:40:46Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any
from datetime import datetime


@dataclass(kw_only=True)
class RemoteConnection:
    """
    Remote Connection
ALIGNED WITH: Agent Schema RemoteConnection
SOURCE: https://github.com/microsoft/AgentSchema (agentschema/model/connection.tsp)
RATIONALE: Remote service connection with endpoint and credentials
    """
    # Service endpoint URL.
    # ALIGNED WITH: Agent Schema RemoteConnection.endpoint
    # 
    # EXAMPLES:
    # - "https://api.example.com"
    # - "https://mcp-server.example.com"
    endpoint: str
    # Connection type discriminator.
    # ALIGNED WITH: Agent Schema Connection.kind
    kind: str
    # Authentication credentials.
    # ALIGNED WITH: Agent Schema RemoteConnection.credentials
    # 
    # FLEXIBLE: Arbitrary credential formats
    # 
    # EXAMPLES:
    # - { "token": "Bearer abc123" }
    # - { "username": "user", "password": "pass" }
    # - { "clientId": "...", "clientSecret": "..." }
    credentials: Optional[Dict[str, Any]] = None
    # Usage transparency description.
    # ALIGNED WITH: Agent Schema Connection.usageDescription
    usage_description: Optional[str] = None
