# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T00:10:10Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any
from datetime import datetime

from .input_token_details import InputTokenDetails
from .output_token_details import OutputTokenDetails


@dataclass
class RequestUsage:
    """
    Request Usage
FROM: OpenAI Agents SDK (RequestUsage)
SOURCE: /openai-agents-python/src/agents/usage.py
ADDITION: Not in MAF or Azure Agent API
RATIONALE: Tracks usage for individual LLM API requests within a run
- Useful for per-request cost calculation
- Enables accurate cost attribution when requests have different pricing (batch vs real-time)
M365: Enables detailed cost tracking for multi-turn runs
    """
    input_tokens: int
    output_tokens: int
    total_tokens: int
    input_token_details: Optional[InputTokenDetails] = None
    output_token_details: Optional[OutputTokenDetails] = None
    timestamp: Optional[datetime] = None
    metadata: Optional[Dict[str, Any]] = None
