# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T06:40:49Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any
from datetime import datetime

from .run_condition import RunCondition
from .chat_role import ChatRole


@dataclass(kw_only=True)
class RolesCondition:
    """
    Roles Condition
RATIONALE: Match based on message role (user, assistant, system, etc.)
    """
    # Condition type discriminator.
    kind: str
    # Message roles that trigger match.
    # 
    # EXAMPLES:
    # - ["user"]: Match only user messages
    # - ["user", "system"]: Match user or system messages
    roles: List[ChatRole] = field(default_factory=list)
