# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T06:40:40Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any
from datetime import datetime

from .run_status import RunStatus
from .chat_message import ChatMessage
from .completion_usage import CompletionUsage
from .run_error import RunError
from .agent_definition import AgentDefinition
from .prompt_agent import PromptAgent
from .run_options import RunOptions
from .thread_cleanup import ThreadCleanup


@dataclass
class Run:
    # Unique identifier for the agent that processed this run.
    # FROM: Azure Agent API
    # M365: Maps to Agent ID (Entra Object ID in Phase 2)
    agent_id: str
    # Timestamp when the run was created.
    # FROM: Azure Agent API (createdAt) + OpenAI Agents SDK
    created_at: datetime
    # Unique identifier for this run.
    # FROM: Azure Agent API
    # GENERATED: Server-generated GUID
    run_id: str
    # Current lifecycle status of the run.
    # FROM: Azure Agent API (5 states) + OpenAI Agents SDK (8 states) + A2A Protocol (interruption states)
    # 
    # EXPANDED from Azure's 5 states to OpenAI's 8 states plus A2A interruption states:
    # - queued: Run is waiting to start (from OpenAI)
    # - in_progress: Run is executing (both)
    # - requires_action: Tool execution needed (from OpenAI)
    # - input_required: Human input needed (from A2A - HITL)
    # - auth_required: Authentication needed (from A2A)
    # - cancelling: User requested cancellation, run is stopping (from OpenAI)
    # - cancelled: Run was cancelled by user before completion (both)
    # - failed: Run encountered error (both)
    # - completed: Run finished successfully (both)
    # - incomplete: Run stopped before completion (both)
    # 
    # CANCELLATION STATES:
    # - cancelling: Transitional state while stopping
    # - cancelled: Final state after cancellation complete
    # 
    # M365: Enables orchestration pipeline to track run state
    status: RunStatus
    # Timestamp of last status update.
    # FROM: OpenAI Agents SDK (updated_at)
    # ADDITION: Not in Azure Agent API
    updated_at: datetime
    # Token usage statistics for this run.
    # FROM: Azure Agent API (CompletionUsage) + MAF (UsageDetails)
    # 
    # M365: Tracked for cost management and quotas
    usage: CompletionUsage
    # Agent configuration for this run.
    # FROM: Azure Agent API (agent)
    # ALIGNED WITH: Agent Schema AgentDefinition
    # 
    # OPTIONAL: If omitted, uses existing agent (agentId)
    # If provided, executes with inline agent definition (stateless)
    # 
    # MAPS TO: MAF ExecuteAsync with inline agent configuration
    agent: Optional[AgentDefinition] = None
    # Reason for cancellation (if provided by user).
    # ADDITION: User-initiated cancellation tracking
    # 
    # PURPOSE: Optional reason for analytics/debugging
    # EXAMPLES: "User changed mind", "Cost limit reached", "User navigated away"
    cancellation_reason: Optional[str] = None
    # Timestamp when the run was cancelled (if status=cancelled).
    # ADDITION: User-initiated cancellation tracking
    # 
    # PURPOSE: Tracks when user clicked "stop generating" or cancelled the run
    cancelled_at: Optional[datetime] = None
    # Timestamp when the run finished (completed, failed, or cancelled).
    # FROM: Azure Agent API (completedAt)
    completed_at: Optional[datetime] = None
    # Error details if run failed or completed incompletely.
    # FROM: Azure Agent API (incompleteDetails) - generalized
    # 
    # GENERALIZED: Generic error model with code + message pattern
    # Like HTTP status codes or gRPC status - structured error codes
    # that clients can handle programmatically.
    # 
    # M365: Provides user-facing error messages with machine-readable codes
    error: Optional[RunError] = None
    # Input messages that started this run.
    # FROM: Azure Agent API (input)
    # NOTE: Only included in create requests, not responses
    input: List[ChatMessage] = field(default_factory=list)
    # Optional identifier for the agent's journal.
    # ADDITION: From M365 Agent Platform (cross-conversation memory)
    # 
    # M365 REQUIREMENT: Links run to Agent Journal for memory substrate
    # - Agent Journal stores knowledge across conversations
    # - Different from threadId (single conversation) and sessionId (multi-conversation)
    journal_id: Optional[str] = None
    # Custom metadata for the run.
    # FROM: Azure Agent API (metadata)
    # 
    # M365: Can store tenant ID, department, cost center, etc.
    metadata: Optional[Dict[str, Any]] = None
    # Configuration options for run execution.
    # FROM: Azure Agent API (RunOptions)
    options: Optional[RunOptions] = None
    # Messages generated during this run.
    # FROM: Azure Agent API (output) + MAF (AgentResponse.Messages)
    # 
    # M365: These messages are stored in Conversation Store
    output: List[ChatMessage] = field(default_factory=list)
    # Optional overrides for existing agent configuration.
    # FROM: Azure Agent API (part of agent-based completion)
    # 
    # M365: Enables per-request customization (e.g., different temperature for specific task)
    # 
    # NOTE: Only applicable for PromptAgent types
    overrides: Optional[PromptAgent] = None
    # Underlying provider representation.
    # FROM: MAF (AgentResponse.RawRepresentation)
    # 
    # Stores the original response from OpenAI/Anthropic/etc for debugging
    raw_representation: Optional[Any] = None
    # Thread cleanup strategy for this run.
    # 
    # @usage
    # 
    # Use Cases:
    # - POST /runs/wait with threadCleanup=delete: Ephemeral execution
    # - POST /runs with threadCleanup=keep: Background run with thread persistence
    # - POST /runs with threadCleanup=delete: Background run with auto-cleanup
    # 
    # M365: Controls whether conversation thread is retained in Conversation Store
    # 
    # 
    # Rationale:
    # - keep: Stateful runs, multi-turn conversations (default)
    # - delete: Ephemeral runs, one-shot queries (auto-cleanup)
    # 
    thread_cleanup: Optional[ThreadCleanup] = None
    # Optional identifier for the conversation thread.
    # FROM: Azure Agent API (required) → Made optional for stateless support
    # M365: Links run to conversation in Conversation Store
    # 
    # OPTIONAL: Allows stateless execution when omitted
    thread_id: Optional[str] = None
    # User who initiated this run.
    # FROM: Azure Agent API (userId)
    # 
    # M365: Maps to Entra User ID (Object ID)
    user_id: Optional[str] = None
    # Webhook URL for run completion notification.
    # 
    # @usage
    # 
    # Use Cases:
    # - Background runs: Create run, return immediately, webhook on completion
    # - Long-running tasks: Avoid polling, get notified when done
    # - Serverless architectures: Trigger next step via webhook
    # 
    webhook: Optional[str] = None
