# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T00:10:03Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from enum import Enum
from typing import Literal


class RunStatus(str, Enum):
    """
    Run Status Enum
FROM: OpenAI Agents SDK (8 states) + A2A Protocol (interruption states) + LangChain Agent Protocol
EXPANDED from Azure Agent API (5 states)
    """
    QUEUED = "queued"
    IN_PROGRESS = "in_progress"
    REQUIRES_ACTION = "requires_action"
    INPUT_REQUIRED = "input_required"
    AUTH_REQUIRED = "auth_required"
    CANCELLING = "cancelling"
    CANCELLED = "cancelled"
    FAILED = "failed"
    COMPLETED = "completed"
    INCOMPLETE = "incomplete"
    TIMEOUT = "timeout"


RunStatusType = Literal["queued", "in_progress", "requires_action", "input_required", "auth_required", "cancelling", "cancelled", "failed", "completed", "incomplete", "timeout"]
