# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T06:40:49Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from typing import Union, TYPE_CHECKING

if TYPE_CHECKING:
    from .always_condition import AlwaysCondition
    from .roles_condition import RolesCondition
    from .content_condition import ContentCondition
    from .mention_condition import MentionCondition
    from .expression_condition import ExpressionCondition
    from .remote_condition import RemoteCondition
    from .similarity_condition import SimilarityCondition


RunCondition = Union["AlwaysCondition", "RolesCondition", "ContentCondition", "MentionCondition", "ExpressionCondition", "RemoteCondition", "SimilarityCondition"]
