# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T06:40:44Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from typing import Union, TYPE_CHECKING

if TYPE_CHECKING:
    from .run_created_event import RunCreatedEvent
    from .run_started_event import RunStartedEvent
    from .run_completed_event import RunCompletedEvent
    from .run_failed_event import RunFailedEvent
    from .run_cancelled_event import RunCancelledEvent
    from .run_timeout_event import RunTimeoutEvent
    from .run_requires_action_event import RunRequiresActionEvent
    from .run_input_required_event import RunInputRequiredEvent


# All run lifecycle streaming events.
# @usage
# Use to monitor run state transitions and completion status.
# Covers the full run lifecycle from creation to completion/failure.
# @example Subscribe to run completion
# ```typescript
# if (event is RunEvent) {
# if (event.kind === "run.completed" || event.kind === "run.failed") {
# // Handle run completion
# }
# }
# ```
RunEvent = Union["RunCreatedEvent", "RunStartedEvent", "RunCompletedEvent", "RunFailedEvent", "RunCancelledEvent", "RunTimeoutEvent", "RunRequiresActionEvent", "RunInputRequiredEvent"]
