# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T06:40:44Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any
from datetime import datetime

from .run_event import RunEvent
from .function_call_content import FunctionCallContent


@dataclass(kw_only=True)
class RunRequiresActionEvent:
    event_seq: int
    kind: str
    run_id: str
    status: str
    timestamp: datetime
    agent_id: Optional[str] = None
    thread_id: Optional[str] = None
    tool_calls: List[FunctionCallContent] = field(default_factory=list)
