# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T06:40:44Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any
from datetime import datetime

from .run_event import RunEvent
from .chat_message import ChatMessage
from .completion_usage import CompletionUsage


@dataclass(kw_only=True)
class RunTimeoutEvent:
    event_seq: int
    run_id: str
    status: str
    timed_out_at: datetime
    agent_id: Optional[str] = None
    output: Optional[List[ChatMessage]] = None
    thread_id: Optional[str] = None
    usage: Optional[CompletionUsage] = None
