# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T06:40:45Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any
from datetime import datetime

from .message_filters import MessageFilters


@dataclass
class RunSubscription:
    """
    Run Subscription - Webhook Notification Registration
@usage
Use Cases:
- Monitor long-running executions
- Track run lifecycle for orchestration
- Get notified when specific runs complete
- Build run activity dashboards
@example Subscribe to run completion
```http
POST /runs/{runId}/subscriptions
{
"webhookUrl": "https://example.com/webhook",
"events": ["run.completed", "run.failed"]
}
```
    """
    # Timestamp when subscription was created.
    created_at: datetime
    # Run being subscribed to.
    # FROM: Parent resource relationship
    run_id: str
    # Unique subscription identifier.
    # GENERATED: Server-generated GUID
    subscription_id: str
    # Webhook URL to POST notifications to.
    # REQUIRED: Must be HTTPS endpoint
    # 
    # WEBHOOK PAYLOAD EXAMPLE:
    # {
    # "type": "run.activity",
    # "resourceId": "run-123",
    # "subscriptionId": "sub-456",
    # "eventType": "run.started" | "message.created" | "run.completed",
    # "sequenceNumber": 42,
    # "eventSeq": 10,
    # "timestamp": "2026-02-06T10:00:00Z"
    # }
    # 
    # CLIENT ACTION: GET /runs/{runId} to fetch latest state
    webhook_url: str
    # Whether subscription is currently active.
    # DEFAULT: true
    # 
    # RATIONALE: Allows temporary disable without deletion
    active: Optional[bool] = None
    # Event types to subscribe to.
    # DEFAULT: All run events if omitted
    # 
    # EVENT TYPES:
    # - "run.started": Run started executing
    # - "message.created": New message in run
    # - "message.updated": Message streaming chunk
    # - "message.completed": Message streaming finished
    # - "run.completed": Run finished successfully
    # - "run.failed": Run encountered error
    # - "run.cancelled": Run was cancelled
    # - "run.timeout": Run exceeded time limit
    # - "run.requires_action": Run needs tool execution
    # - "run.input_required": Run needs user input
    # 
    # RATIONALE: Allow filtering to reduce notification volume
    events: Optional[List[str]] = None
    # Subscription expiration time.
    # OPTIONAL: Subscription automatically deleted after this time
    # 
    # DEFAULT: No expiration (permanent until explicitly deleted)
    expires_at: Optional[datetime] = None
    # Number of consecutive failed delivery attempts.
    # INCREMENTED: On failed webhook POST (timeout, 4xx, 5xx)
    # RESET: On successful delivery
    # 
    # RATIONALE: Automatic subscription disable after max failures
    failure_count: Optional[int] = None
    # Timestamp of last successful webhook delivery.
    # UPDATED: By server after successful POST (HTTP 200-299)
    last_delivered_at: Optional[datetime] = None
    # Message filters for webhook subscriptions.
    # OPTIONAL: Filter which messages trigger notifications
    # 
    # RATIONALE: Reduce noise by filtering out irrelevant messages
    message_filters: Optional[MessageFilters] = None
    # Custom metadata for subscription.
    # FLEXIBLE: Client can store correlation IDs, user info, etc.
    metadata: Optional[Dict[str, Any]] = None
    # Secret for webhook signature validation.
    # OPTIONAL: For webhook authenticity verification
    # 
    # PATTERN: Like GitHub webhook secrets (HMAC-SHA256 signature)
    webhook_secret: Optional[str] = None
