# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T00:10:03Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any
from datetime import datetime


@dataclass
class RunOptions:
    """
    Run Options
FROM: Azure Agent API (RunOptions) + OpenAI Agents SDK (RunOptions/RunConfig)
    """
    # Continuation token for resuming background responses.
FROM: MAF (AgentRunOptions.ContinuationToken)
    continuation_token: Optional[str] = None
