# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T00:10:07Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any
from datetime import datetime


@dataclass
class RunCancelledEvent:
    run_id: str
    thread_id: Optional[str] = None
    agent_id: Optional[str] = None
    event_seq: int
    status: str
    reason: Optional[str] = None
    cancelled_at: datetime
