# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T06:40:40Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any
from datetime import datetime


@dataclass
class RunError:
    """
    Run Error
FROM: Azure Agent API (IncompleteDetails) - generalized
GENERALIZED: Standard error model with code + message pattern
Like HTTP status codes, gRPC status codes, or messaging app error codes
    """
    # Machine-readable error code.
    # EXAMPLES:
    # - "max_turns_exceeded": Run hit max_turns limit
    # - "tool_execution_failed": Tool execution error
    # - "rate_limit_exceeded": API rate limit hit
    # - "context_length_exceeded": Token limit exceeded
    # - "auth_required": Authentication needed
    # - "user_cancelled": User cancelled the run
    code: str
    # Human-readable error message.
    message: str
    # Optional additional error details.
    # FLEXIBLE: Can include stack traces, request IDs, etc.
    details: Optional[Dict[str, Any]] = None
