# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T06:40:44Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from typing import Union

from .message_event import MessageEvent
from .participant_event import ParticipantEvent
from .run_event import RunEvent
from .thread_event import ThreadEvent
from .agent_event import AgentEvent


# Union of all streaming events.
# @usage
# Use to handle any streaming event in a type-safe way.
# Webhook handlers can pattern-match on event categories.
# @example Handle all events
# ```typescript
# function handleEvent(event: StreamingEvent) {
# if (event is MessageEvent) {
# // Handle message events
# } else if (event is RunEvent) {
# // Handle run events
# } else if (event is ThreadEvent) {
# // Handle thread events
# }
# }
# ```
StreamingEvent = Union[MessageEvent, ParticipantEvent, RunEvent, ThreadEvent, AgentEvent]
