# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T06:40:39Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from enum import Enum
from typing import Literal


class ThreadCleanup(str, Enum):
    """
    Thread Cleanup Strategy
@usage
Use Cases:
- keep: Chat conversations, multi-turn interactions
- delete: Extraction tasks, one-shot queries, stateless APIs
    """
    KEEP = "keep"
    DELETE = "delete"


ThreadCleanupType = Literal["keep", "delete"]
