# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T06:40:44Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any
from datetime import datetime

from .thread_event import ThreadEvent


@dataclass(kw_only=True)
class ThreadArchivedEvent:
    archived_at: datetime
    event_seq: int
    thread_id: str
    archived_by: Optional[str] = None
