# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T06:40:50Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from typing import Union, TYPE_CHECKING

if TYPE_CHECKING:
    from .chat_message import ChatMessage
    from .expect import Expect
    from .eval_run import EvalRun
    from .review import Review


ThreadElement = Union["ChatMessage", "Expect", "EvalRun", "Review"]
