# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T00:10:03Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any
from datetime import datetime


@dataclass
class ToolOutput:
    """
    Tool Output
@usage
Use Cases:
- Tool approval: Human reviews delete_file before execution
- External execution: Tools executed by external system, results fed back
- Modified execution: Human modifies tool arguments before running
    """
    # Tool call ID this output corresponds to.
MUST: Match callId from FunctionCallContent in required_action.tool_calls
    tool_call_id: str
    # Tool execution result.
FLEXIBLE: String output or structured data (serialized to string)

EXAMPLES:
- Simple: "File deleted successfully"
- JSON: "{\"status\":\"success\",\"files_deleted\":3}"
- Error: "Permission denied: /protected/file.txt"
    output: str
