# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T06:40:42Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from typing import Union, TYPE_CHECKING

if TYPE_CHECKING:
    from .auto_tool_choice import AutoToolChoice
    from .required_tool_choice import RequiredToolChoice
    from .none_tool_choice import NoneToolChoice
    from .specific_tool_choice import SpecificToolChoice


# Tool Choice Behavior
# FROM: Azure Agent API (ToolChoiceBehavior)
# CONTROLS: How agent uses tools
# MESSAGING APP ANALOGY:
# - "auto": Bot decides when to use commands
# - "required": Bot must use a command
# - "none": Bot cannot use commands (text-only response)
# - "specific": Force specific command (like /help shortcut)
ToolChoiceBehavior = Union["AutoToolChoice", "RequiredToolChoice", "NoneToolChoice", "SpecificToolChoice"]
