# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T00:10:04Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any
from datetime import datetime


@dataclass
class ToolCallRequest:
    """
    Tool Call Request
ADDITION: Tool execution request for protocol-level tool calling
REPRESENTS: Request to execute a tool/function with specific arguments
USED BY: Hosting SDKs when LLM requests tool execution
    """
    call_id: str
    tool_name: str
    arguments: str
