# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T06:40:42Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any
from datetime import datetime


@dataclass
class ToolExecutionError:
    """
    Tool Execution Error
ADDITION: Error that occurred during tool execution
REPRESENTS: Structured error information for tool failures
USED BY: Hosting SDKs to report tool execution errors
    """
    code: str
    message: str
    details: Optional[Dict[str, Any]] = None
    stack_trace: Optional[str] = None
