# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T06:40:42Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any
from datetime import datetime

from .lifecycle_hook import LifecycleHook


@dataclass
class ToolLifecycleHooks:
    # Executed after successful tool invocation.
    # EXAMPLES:
    # - Validate output
    # - Persist result to memory
    # - Log completion
    # - Apply output guardrails
    after_execute: Optional[LifecycleHook] = None
    # Executed before tool invocation.
    # EXAMPLES:
    # - Validate parameters
    # - Check permissions
    # - Log invocation
    # - Apply input guardrails
    before_execute: Optional[LifecycleHook] = None
    # Executed when tool invocation fails.
    # EXAMPLES:
    # - Log error
    # - Send alert
    # - Fallback behavior
    on_error: Optional[LifecycleHook] = None
