# <auto-generated>
# This code was generated by TypeSpec Code Generator on 2026-02-10T06:40:38Z.
# Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
# To modify this file, edit the TypeSpec source and regenerate.
# </auto-generated>

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any
from datetime import datetime

from .ai_content_base import AIContentBase


@dataclass(kw_only=True)
class VideoContent(AIContentBase):
    """
    Video Content
FROM: Azure Agent API (VideoContent)
ADDITION: Not in MAF
Represents video data that can be included in messages.
M365: Multi-modal scenarios (video input, video responses, screen recordings)
XML: <video uri="..." mime-type="..." width="1920" height="1080" duration="120" frame-rate="30" />
    """
    uri: Optional[str] = None
    mime_type: Optional[str] = None
    width: Optional[int] = None
    height: Optional[int] = None
    duration: Optional[int] = None
    frame_rate: Optional[int] = None

    @property
    def kind(self) -> str:
        return "video"
