"""
Test Code Generator

Generates C# xUnit and Python pytest test code from TypeSpec models.
"""

from pathlib import Path
from typing import List

from .typespec_parser import Model
from .code_utils import to_kebab_case


def generate_csharp_tests(
    models: List[Model],
    output_file: str,
    start_number: int = 19
) -> None:
    """
    Generate C# xUnit test class.

    Args:
        models: List of Model objects
        output_file: Path to output C# file
        start_number: Starting test number
    """
    # Generate [InlineData] attributes
    inline_data = []
    for i, model in enumerate(models, start=start_number):
        filename = f"{i:02d}-{to_kebab_case(model.name)}.xml"
        inline_data.append(f'    [InlineData("{filename}")]')

    test_code = f'''using System;
using System.IO;
using Xunit;
using FluentAssertions;
using Microsoft.Agents.Xml.Generated.Models;
using Microsoft.Agents.Xml.Core.Serialization;

namespace Microsoft.Agents.Xml.CodeGen.Tests;

/// <summary>
/// AUTO-GENERATED: Round-trip tests for content types.
/// Generated from TypeSpec schema at: {Path.cwd() / "typespec/messages.tsp"}
///
/// DO NOT EDIT THIS FILE MANUALLY.
/// Regenerate with: python scripts/generation/generate-tests.py
/// </summary>
public partial class GeneratedRoundTripTests
{{
    private readonly MessageSerializer _serializer = new();
    private readonly string _testDataPath;

    public GeneratedRoundTripTests()
    {{
        _testDataPath = Path.Combine(
            AppDomain.CurrentDomain.BaseDirectory,
            "..", "..", "..", "TestData", "Input"
        );
        _testDataPath = Path.GetFullPath(_testDataPath);
    }}

    /// <summary>
    /// Tests serialization round-trip for auto-generated test files.
    /// Each test:
    /// 1. Loads XML from TestData/Input/
    /// 2. Deserializes to message object
    /// 3. Serializes back to XML
    /// 4. Compares structure (ignoring whitespace)
    /// </summary>
    [Theory]
{chr(10).join(inline_data)}
    public void RoundTrip_GeneratedTest_PreservesAllData(string filename)
    {{
        // Arrange
        var filePath = Path.Combine(_testDataPath, filename);

        if (!File.Exists(filePath))
        {{
            throw new FileNotFoundException($"Test file not found: {{filePath}}");
        }}

        var originalXml = File.ReadAllText(filePath);

        // Act - Deserialize
        var message = _serializer.Deserialize(originalXml);
        message.Should().NotBeNull($"Failed to deserialize {{filename}}");

        // Act - Serialize back
        var serializedXml = _serializer.Serialize(message);
        serializedXml.Should().NotBeNullOrWhiteSpace($"Failed to serialize {{filename}}");

        // Assert - Compare XMLs (structure, not whitespace)
        CompareXml(originalXml, serializedXml, filename);

        // Output for debugging
        Console.WriteLine($"✅ {{filename}} - Round-trip successful");
        Console.WriteLine($"   Message Type: {{message.GetType().Name}}");
        Console.WriteLine($"   Message ID: {{message.MessageId}}");
    }}

    /// <summary>
    /// Compares two XML strings structurally (ignoring whitespace differences).
    /// </summary>
    private void CompareXml(string expected, string actual, string context)
    {{
        // Load as XML documents
        var expectedDoc = System.Xml.Linq.XDocument.Parse(expected);
        var actualDoc = System.Xml.Linq.XDocument.Parse(actual);

        // Compare root element names
        expectedDoc.Root.Should().NotBeNull($"Expected XML root is null for {{context}}");
        actualDoc.Root.Should().NotBeNull($"Actual XML root is null for {{context}}");

        expectedDoc.Root!.Name.Should().Be(actualDoc.Root!.Name,
            $"Root element mismatch for {{context}}");

        // Compare attributes (order-independent)
        var expectedAttrs = expectedDoc.Root.Attributes()
            .OrderBy(a => a.Name.LocalName)
            .ToList();
        var actualAttrs = actualDoc.Root.Attributes()
            .OrderBy(a => a.Name.LocalName)
            .ToList();

        expectedAttrs.Count.Should().Be(actualAttrs.Count,
            $"Attribute count mismatch for {{context}}");

        for (int i = 0; i < expectedAttrs.Count; i++)
        {{
            expectedAttrs[i].Name.Should().Be(actualAttrs[i].Name,
                $"Attribute name mismatch at position {{i}} for {{context}}");
            expectedAttrs[i].Value.Should().Be(actualAttrs[i].Value,
                $"Attribute value mismatch for {{expectedAttrs[i].Name}} in {{context}}");
        }}

        // Compare child elements recursively
        CompareElements(expectedDoc.Root, actualDoc.Root, context);
    }}

    private void CompareElements(
        System.Xml.Linq.XElement expected,
        System.Xml.Linq.XElement actual,
        string context)
    {{
        // Compare element names
        expected.Name.Should().Be(actual.Name, $"Element name mismatch in {{context}}");

        // Compare text content (trimmed)
        var expectedText = expected.Nodes()
            .OfType<System.Xml.Linq.XText>()
            .Select(t => t.Value.Trim())
            .Where(t => !string.IsNullOrWhiteSpace(t))
            .FirstOrDefault();

        var actualText = actual.Nodes()
            .OfType<System.Xml.Linq.XText>()
            .Select(t => t.Value.Trim())
            .Where(t => !string.IsNullOrWhiteSpace(t))
            .FirstOrDefault();

        if (expectedText != null || actualText != null)
        {{
            expectedText.Should().Be(actualText,
                $"Text content mismatch in {{expected.Name}} for {{context}}");
        }}

        // Compare child elements
        var expectedChildren = expected.Elements().ToList();
        var actualChildren = actual.Elements().ToList();

        expectedChildren.Count.Should().Be(actualChildren.Count,
            $"Child element count mismatch in {{expected.Name}} for {{context}}");

        for (int i = 0; i < expectedChildren.Count; i++)
        {{
            CompareElements(expectedChildren[i], actualChildren[i], context);
        }}
    }}
}}
'''

    # Write to file
    Path(output_file).write_text(test_code)
    print(f"✅ Generated C# tests: {output_file}")


def generate_python_tests(
    models: List[Model],
    output_file: str,
    start_number: int = 19
) -> None:
    """
    Generate Python pytest test module.

    Args:
        models: List of Model objects
        output_file: Path to output Python file
        start_number: Starting test number
    """
    # Generate test parameters
    test_files = []
    for i, model in enumerate(models, start=start_number):
        filename = f"{i:02d}-{to_kebab_case(model.name)}.xml"
        test_files.append(f'    "{filename}"')

    test_code = f'''"""
AUTO-GENERATED: Round-trip tests for content types.
Generated from TypeSpec schema at: {Path.cwd() / "typespec/messages.tsp"}

DO NOT EDIT THIS FILE MANUALLY.
Regenerate with: python scripts/generation/generate-tests.py
"""

import pytest
from pathlib import Path
from lxml import etree
from microsoft.agents.xml.serialization import MessageSerializer


class TestGeneratedRoundTrip:
    """Auto-generated round-trip tests from TypeSpec"""

    @pytest.fixture
    def serializer(self):
        """Create message serializer"""
        return MessageSerializer()

    @pytest.fixture
    def test_data_dir(self):
        """Get test data directory"""
        return Path(__file__).parent / ".." / ".." / ".." / "test-data" / "input"

    @pytest.mark.parametrize("filename", [
{",\n".join(test_files)}
    ])
    def test_roundtrip_generated(self, serializer, test_data_dir, filename):
        """
        Test serialization round-trip for generated test files.

        Each test:
        1. Loads XML from test_data/input/
        2. Deserializes to message object
        3. Serializes back to XML
        4. Compares structure (ignoring whitespace)
        """
        # Arrange
        file_path = test_data_dir / filename
        assert file_path.exists(), f"Test file not found: {{file_path}}"

        original_xml = file_path.read_text()

        # Act - Deserialize
        message = serializer.deserialize(original_xml)
        assert message is not None, f"Failed to deserialize {{filename}}"

        # Act - Serialize back
        serialized_xml = serializer.serialize(message)
        assert serialized_xml, f"Failed to serialize {{filename}}"

        # Assert - Compare XMLs
        self._compare_xml(original_xml, serialized_xml, filename)

        print(f"✅ {{filename}} - Round-trip successful")
        print(f"   Message Type: {{type(message).__name__}}")
        print(f"   Message ID: {{message.message_id}}")

    def _compare_xml(self, expected: str, actual: str, context: str):
        """
        Compare two XML strings structurally (ignoring whitespace).

        Args:
            expected: Expected XML string
            actual: Actual XML string
            context: Test context for error messages
        """
        # Parse both XMLs
        expected_tree = etree.fromstring(expected.encode('utf-8'))
        actual_tree = etree.fromstring(actual.encode('utf-8'))

        # Compare root element names
        assert expected_tree.tag == actual_tree.tag, \\
            f"Root element mismatch for {{context}}: {{expected_tree.tag}} != {{actual_tree.tag}}"

        # Compare attributes (order-independent)
        expected_attrs = sorted(expected_tree.attrib.items())
        actual_attrs = sorted(actual_tree.attrib.items())

        assert len(expected_attrs) == len(actual_attrs), \\
            f"Attribute count mismatch for {{context}}: {{len(expected_attrs)}} != {{len(actual_attrs)}}"

        for (exp_name, exp_value), (act_name, act_value) in zip(expected_attrs, actual_attrs):
            assert exp_name == act_name, \\
                f"Attribute name mismatch in {{context}}: {{exp_name}} != {{act_name}}"
            assert exp_value == act_value, \\
                f"Attribute value mismatch for {{exp_name}} in {{context}}: {{exp_value}} != {{act_value}}"

        # Compare text content (trimmed)
        expected_text = (expected_tree.text or "").strip()
        actual_text = (actual_tree.text or "").strip()

        if expected_text or actual_text:
            assert expected_text == actual_text, \\
                f"Text content mismatch in {{expected_tree.tag}} for {{context}}: {{expected_text}} != {{actual_text}}"

        # Compare child elements recursively
        expected_children = list(expected_tree)
        actual_children = list(actual_tree)

        assert len(expected_children) == len(actual_children), \\
            f"Child element count mismatch in {{expected_tree.tag}} for {{context}}: {{len(expected_children)}} != {{len(actual_children)}}"

        for exp_child, act_child in zip(expected_children, actual_children):
            self._compare_elements(exp_child, act_child, context)

    def _compare_elements(self, expected, actual, context):
        """Recursively compare XML elements"""
        # Compare element names
        assert expected.tag == actual.tag, \\
            f"Element name mismatch in {{context}}: {{expected.tag}} != {{actual.tag}}"

        # Compare attributes
        expected_attrs = sorted(expected.attrib.items())
        actual_attrs = sorted(actual.attrib.items())

        assert expected_attrs == actual_attrs, \\
            f"Attributes mismatch in {{expected.tag}} for {{context}}"

        # Compare text content
        expected_text = (expected.text or "").strip()
        actual_text = (actual.text or "").strip()

        if expected_text or actual_text:
            assert expected_text == actual_text, \\
                f"Text mismatch in {{expected.tag}} for {{context}}"

        # Compare children
        expected_children = list(expected)
        actual_children = list(actual)

        assert len(expected_children) == len(actual_children), \\
            f"Child count mismatch in {{expected.tag}} for {{context}}"

        for exp_child, act_child in zip(expected_children, actual_children):
            self._compare_elements(exp_child, act_child, context)
'''

    # Write to file
    Path(output_file).write_text(test_code)
    print(f"✅ Generated Python tests: {output_file}")
