"""
TypeScript Test Code Generator

Generates TypeScript/Jest test code for round-trip, property validation, and enum tests.
"""

from pathlib import Path
from typing import List
from .typespec_parser import Model, Property
from .code_utils import to_pascal_case, to_camel_case, to_kebab_case
from .property_test_generator import PropertyTestGenerator
from .test_utilities import is_complex_type, get_test_value_for_property


def generate_typescript_roundtrip_tests(
    models: List[Model],
    output_file: str,
    start_number: int = 19
) -> str:
    """
    Generate TypeScript round-trip test code.

    Args:
        models: List of Model objects from TypeSpec parser
        output_file: Path to output test file
        start_number: Starting test number

    Returns:
        Generated TypeScript test code
    """
    # Generate test file list
    test_files = []
    for i, model in enumerate(models, start=start_number):
        filename = f"{i:02d}-{to_kebab_case(model.name)}.xml"
        test_files.append(f'  "{filename}"')

    test_code = f'''/**
 * AUTO-GENERATED: Round-trip tests for content types.
 * Generated from TypeSpec schema at: {Path.cwd() / "typespec/messages.tsp"}
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Regenerate with: python scripts/generation/generate-tests.py
 */

import {{ describe, it, expect, beforeAll }} from '@jest/globals';
import {{ MessageSerializer }} from '../src/serialization/MessageSerializer';
import {{ readFileSync }} from 'fs';
import {{ join }} from 'path';

describe('Generated Round-Trip Tests', () => {{
  let serializer: MessageSerializer;
  const testDataPath = join(__dirname, '../../../../test-data/input');

  beforeAll(() => {{
    serializer = new MessageSerializer();
  }});

  /**
   * Tests serialization round-trip for auto-generated test files.
   * Each test:
   * 1. Loads XML from test-data/input/
   * 2. Deserializes to message object
   * 3. Serializes back to XML
   * 4. Compares structure (ignoring whitespace)
   */
  const testFiles = [
{",\n".join(test_files)}
  ];

  testFiles.forEach((filename) => {{
    it(`should round-trip ${{filename}} preserving all data`, () => {{
      // Arrange
      const filePath = join(testDataPath, filename);
      const originalXml = readFileSync(filePath, 'utf-8');

      // Act - Deserialize
      const message = serializer.deserialize(originalXml);
      expect(message).toBeDefined();

      // Act - Serialize back
      const serializedXml = serializer.serialize(message);
      expect(serializedXml).toBeDefined();
      expect(serializedXml.length).toBeGreaterThan(0);

      // Assert - Compare XMLs (structure, not whitespace)
      compareXml(originalXml, serializedXml, filename);

      // Output for debugging
      console.log(`✅ ${{filename}} - Round-trip successful`);
      console.log(`   Message Type: ${{message.constructor.name}}`);
      console.log(`   Message ID: ${{message.messageId}}`);
    }});
  }});

  /**
   * Compares two XML strings structurally (ignoring whitespace differences).
   */
  function compareXml(expected: string, actual: string, context: string): void {{
    // For now, do basic validation
    // TODO: Implement proper XML comparison using a library like xml2js or fast-xml-parser
    expect(actual).toContain('message-id=');
    expect(actual.length).toBeGreaterThan(0);

    // Parse both XMLs to verify they're well-formed
    const DOMParser = require('xmldom').DOMParser;
    const parser = new DOMParser();

    const expectedDoc = parser.parseFromString(expected, 'text/xml');
    const actualDoc = parser.parseFromString(actual, 'text/xml');

    expect(expectedDoc.documentElement).toBeDefined();
    expect(actualDoc.documentElement).toBeDefined();

    // Compare root element names
    expect(actualDoc.documentElement.tagName).toBe(expectedDoc.documentElement.tagName);
  }}
}});
'''

    # Write to file
    Path(output_file).write_text(test_code)
    print(f"✅ Generated TypeScript round-trip tests: {output_file}")

    return test_code


def generate_typescript_property_tests(models: List[Model], output_file: str) -> str:
    """
    Generate TypeScript test code for property validation.

    Args:
        models: List of Model objects from TypeSpec parser
        output_file: Path to output test file

    Returns:
        Generated TypeScript test code
    """
    content_types = [m for m in models if m.extends == "AIContentBase" and m.xml_root]
    test_generator = PropertyTestGenerator(models)

    lines = []
    lines.append("/**")
    lines.append(" * Auto-generated property validation tests.")
    lines.append(" * Tests that every property serializes and deserializes correctly.")
    lines.append(" */")
    lines.append("")
    lines.append("import { describe, it, expect } from '@jest/globals';")
    lines.append("import { MessageSerializer } from '../src/serialization/MessageSerializer';")
    lines.append("import {")
    for model in content_types:
        lines.append(f"  {model.name},")
    lines.append("} from '../src/models';")
    lines.append("")
    lines.append("")

    # Generate tests for each content type
    for model in content_types:
        lines.extend(_generate_model_property_tests_typescript(model, test_generator))

    # Generate discriminator tests
    lines.append("// Discriminator Tests")
    lines.append("")
    for model in content_types:
        if model.kind:
            lines.extend(_generate_discriminator_test_typescript(model, test_generator))

    # Generate required/optional tests
    lines.append("// Required vs Optional Tests")
    lines.append("")
    for model in content_types:
        lines.extend(_generate_required_optional_tests_typescript(model, test_generator))

    code = "\n".join(lines)

    # Write to file
    with open(output_file, 'w') as f:
        f.write(code)

    return code


def _generate_model_property_tests_typescript(model: Model, test_generator: PropertyTestGenerator) -> List[str]:
    """Generate property tests for a single model (TypeScript)."""
    lines = []
    lines.append(f"describe('{model.name} Property Tests', () => {{")
    lines.append("")

    # Get testable properties (exclude kind, xmlIgnore, arrays, complex types)
    testable_props = [
        p for p in model.properties
        if p.name != "kind"
        and "@xmlIgnore" not in p.decorators
        and not p.type.startswith("List<")
        and not p.type.startswith("Array<")
        and p.type not in ["utcDateTime", "DateTime"]
        and not is_complex_type(p.type)
    ]

    for prop in testable_props:
        test_name = f"{to_camel_case(model.name)}_{to_camel_case(prop.name)}_property"
        test_value = get_test_value_for_property(prop)

        # Generate XML inline
        try:
            xml_content = test_generator.generate_property_test_xml(
                model.name,
                prop.name,
                test_value,
                test_id=f"{test_name}_msg"
            )
            # Escape for TypeScript template literal
            xml_escaped = xml_content.replace('`', '\\`').replace('${', '\\${')
        except Exception as e:
            # Skip properties that can't be tested
            print(f"  ⚠️  Skipping {model.name}.{prop.name}: {e}")
            continue

        lines.append(f"  it('should deserialize {prop.name} property correctly', () => {{")
        lines.append(f"    // Arrange: XML with {prop.name} property set")
        lines.append(f"    const xml = `{xml_escaped}`;")
        lines.append(f"    const testValue = '{test_value}';")
        lines.append("")
        lines.append("    // Act: Deserialize")
        lines.append("    const serializer = new MessageSerializer();")
        lines.append("    const message = serializer.deserialize(xml);")
        lines.append("")
        lines.append("    // Assert: Verify property value")
        lines.append("    expect(message).toBeDefined();")
        lines.append("    expect(message.contents).toBeDefined();")
        lines.append("    expect(message.contents.length).toBeGreaterThan(0);")
        lines.append(f"    const content = message.contents[0] as {model.name};")
        lines.append(f"    expect(content.{to_camel_case(prop.name)}).toBeDefined();")

        # Type-specific assertions
        if prop.type in ["int32", "integer", "int64"]:
            lines.append(f"    expect(content.{to_camel_case(prop.name)}).toBe(parseInt(testValue));")
        elif prop.type in ["float32", "float64", "float"]:
            lines.append(f"    expect(content.{to_camel_case(prop.name)}).toBeCloseTo(parseFloat(testValue), 2);")
        elif prop.type == "boolean":
            lines.append(f"    expect(content.{to_camel_case(prop.name)}).toBe(testValue === 'true');")
        else:
            lines.append(f"    expect(content.{to_camel_case(prop.name)}).toBe(testValue);")

        lines.append("  });")
        lines.append("")

    lines.append("});")
    lines.append("")

    return lines


def _generate_discriminator_test_typescript(model: Model, test_generator: PropertyTestGenerator) -> List[str]:
    """Generate discriminator test for a model (TypeScript)."""
    lines = []

    # Generate XML inline
    try:
        xml_content = test_generator.generate_discriminator_test_xml(
            model.name,
            test_id=f"{to_camel_case(model.name)}_discriminator_msg"
        )
        # Escape for TypeScript template literal
        xml_escaped = xml_content.replace('`', '\\`').replace('${', '\\${')
    except Exception as e:
        # Skip if can't generate
        print(f"  ⚠️  Skipping discriminator test for {model.name}: {e}")
        return []

    lines.append(f"describe('{model.name} Discriminator Test', () => {{")
    lines.append(f"  it('should deserialize with correct discriminator', () => {{")
    lines.append(f"    // Arrange: XML with {model.kind} discriminator")
    lines.append(f"    const xml = `{xml_escaped}`;")
    lines.append("")
    lines.append("    // Act: Deserialize")
    lines.append("    const serializer = new MessageSerializer();")
    lines.append("    const message = serializer.deserialize(xml);")
    lines.append("")
    lines.append("    // Assert: Verify correct type is instantiated")
    lines.append("    expect(message).toBeDefined();")
    lines.append("    expect(message.contents).toBeDefined();")
    lines.append("    expect(message.contents.length).toBeGreaterThan(0);")
    lines.append(f"    const content = message.contents[0] as {model.name};")
    lines.append(f"    expect(content.kind).toBe('{model.kind}');")
    lines.append("  });")
    lines.append("});")
    lines.append("")

    return lines


def _generate_required_optional_tests_typescript(model: Model, test_generator: PropertyTestGenerator) -> List[str]:
    """Generate required/optional field tests for a model (TypeScript)."""
    lines = []

    optional_props = [p for p in model.properties if p.optional and "@xmlIgnore" not in p.decorators]

    # Test optional fields can be omitted
    if optional_props:
        # Generate XML inline with optional fields omitted
        try:
            omitted_field_names = [p.name for p in optional_props[:3]]
            xml_content = test_generator.generate_optional_field_test_xml(
                model.name,
                omitted_field_names,
                test_id=f"{to_camel_case(model.name)}_optional_msg"
            )
            # Escape for TypeScript template literal
            xml_escaped = xml_content.replace('`', '\\`').replace('${', '\\${')
        except Exception as e:
            # Skip if can't generate
            print(f"  ⚠️  Skipping optional field test for {model.name}: {e}")
            return lines

        lines.append(f"describe('{model.name} Optional Fields Test', () => {{")
        lines.append(f"  it('should allow optional fields to be omitted', () => {{")
        lines.append(f"    // Arrange: XML omitting optional fields: {', '.join(omitted_field_names)}")
        lines.append(f"    const xml = `{xml_escaped}`;")
        lines.append("")
        lines.append("    // Act: Deserialize (should succeed)")
        lines.append("    const serializer = new MessageSerializer();")
        lines.append("    const message = serializer.deserialize(xml);")
        lines.append("")
        lines.append("    // Assert: Message deserializes successfully")
        lines.append("    expect(message).toBeDefined();")
        lines.append("    expect(message.contents).toBeDefined();")
        lines.append("    expect(message.contents.length).toBeGreaterThan(0);")
        lines.append(f"    const content = message.contents[0] as {model.name};")
        lines.append("    expect(content).toBeDefined();")
        lines.append("  });")
        lines.append("});")
        lines.append("")

    return lines


def generate_typescript_enum_tests(enums: List, output_file: str) -> str:
    """
    Generate TypeScript test code for enum value validation.

    Args:
        enums: List of EnumInfo objects
        output_file: Path to output test file

    Returns:
        Generated TypeScript test code
    """
    from .enum_test_generator import EnumInfo

    lines = []
    lines.append("/**")
    lines.append(" * Auto-generated enum value tests.")
    lines.append(" * Tests that all enum values serialize and deserialize correctly.")
    lines.append(" */")
    lines.append("")
    lines.append("import { describe, it, expect } from '@jest/globals';")
    lines.append("import {")
    for enum_info in enums:
        lines.append(f"  {enum_info.name},")
    lines.append("} from '../src/models';")
    lines.append("")
    lines.append("")

    for enum_info in enums:
        lines.extend(_generate_enum_tests_typescript(enum_info))

    code = "\n".join(lines)

    # Write to file
    with open(output_file, 'w') as f:
        f.write(code)

    return code


def _generate_enum_tests_typescript(enum_info) -> List[str]:
    """Generate tests for a single enum (TypeScript)."""
    lines = []
    lines.append(f"describe('{enum_info.name} Enum Tests', () => {{")
    lines.append("")

    # Deduplicate values
    seen_test_names = set()

    # Test each enum value
    for value in enum_info.values:
        test_name = f"{to_camel_case(value)}_value"

        # Skip if we've already generated this test
        if test_name in seen_test_names:
            continue
        seen_test_names.add(test_name)

        lines.append(f"  it('should serialize and deserialize {value} correctly', () => {{")
        lines.append(f"    // Arrange: Get enum value")
        lines.append(f"    const enumValue = {enum_info.name}.{to_pascal_case(value)};")
        lines.append("")
        lines.append("    // Act: Serialize to string")
        lines.append(f"    const serialized = enumValue.toString();")
        lines.append("")
        lines.append("    // Assert: Value serializes correctly")
        lines.append(f"    expect(serialized).toBeDefined();")
        lines.append(f"    expect(serialized.length).toBeGreaterThan(0);")
        lines.append("")
        lines.append("    // Act: Parse back")
        lines.append(f"    const parsed = {enum_info.name}[serialized as keyof typeof {enum_info.name}];")
        lines.append("")
        lines.append("    // Assert: Round-trip successful")
        lines.append(f"    expect(parsed).toBe(enumValue);")
        lines.append("  });")
        lines.append("")

    # Test all enum values are valid
    lines.append(f"  it('should have all valid enum values', () => {{")
    lines.append(f"    // Arrange: Get all enum values")
    lines.append(f"    const allValues = Object.values({enum_info.name});")
    lines.append("")
    lines.append("    // Assert: Each value can be serialized and deserialized")
    lines.append("    allValues.forEach(value => {")
    lines.append("      const serialized = value.toString();")
    lines.append("      expect(serialized).toBeDefined();")
    lines.append(f"      const parsed = {enum_info.name}[serialized as keyof typeof {enum_info.name}];")
    lines.append("      expect(parsed).toBe(value);")
    lines.append("    });")
    lines.append("  });")
    lines.append("")

    lines.append("});")
    lines.append("")

    return lines
