"""
Generator for Python validation tests from C# templates.

Converts C# xUnit validation tests to Python pytest equivalents.
"""

from pathlib import Path
from typing import List, Dict, Tuple
import re


class ValidationTestGenerator:
    """Generates Python validation tests from C# test patterns."""

    def __init__(self):
        self.error_code_mapping = {
            # Content validation codes
            "REL_001": "REL_001",  # Missing required relationship ID
            "REL_003": "REL_003",  # Duplicate call ID
            "CNT_003": "CNT_003",  # Invalid function name format
            "CNT_004": "CNT_004",  # Invalid JSON in arguments

            # Message validation codes
            "MSG_001": "MSG_001",  # Missing message ID
            "MSG_004": "MSG_004",  # Future timestamp
            "MSG_005": "MSG_005",  # Author name too long
            "MSG_010": "MSG_010",  # Empty contents

            # Role validation codes
            "ROLE_005": "ROLE_005",  # Invalid content type for role
        }

    def generate_validation_result_tests(self, output_path: str) -> None:
        """Generate Python tests for ValidationResult core functionality."""

        test_content = '''"""
AUTO-GENERATED: ValidationResult core tests.
Generated from C# validation test patterns.

Tests core validation result functionality:
- Success/failure results
- Error combining
- Error filtering
- Exception throwing

DO NOT EDIT THIS FILE MANUALLY.
Regenerate with validation test generator.
"""

import pytest
from microsoft.agents.protocol.validation import (
    ValidationResult,
    ValidationError,
    ValidationException,
    ValidationSeverity,
)


class TestValidationResult:
    """Tests for ValidationResult core functionality."""

    def test_success_returns_valid_result(self):
        """Test that Success() returns a valid result with no errors."""
        # Act
        result = ValidationResult.success()

        # Assert
        assert result.is_valid
        assert len(result.errors) == 0

    def test_failure_returns_invalid_result(self):
        """Test that Failure() returns an invalid result with error."""
        # Act
        result = ValidationResult.failure("TEST-001", "Test error")

        # Assert
        assert not result.is_valid
        assert len(result.errors) == 1
        assert result.errors[0].code == "TEST-001"
        assert result.errors[0].message == "Test error"

    def test_combine_merges_errors(self):
        """Test that combining results merges their errors."""
        # Arrange
        result1 = ValidationResult.failure("TEST-001", "Error 1")
        result2 = ValidationResult.failure("TEST-002", "Error 2")

        # Act
        combined = result1.combine(result2)

        # Assert
        assert not combined.is_valid
        assert len(combined.errors) == 2
        assert any(e.code == "TEST-001" for e in combined.errors)
        assert any(e.code == "TEST-002" for e in combined.errors)

    def test_throw_if_invalid_raises_when_invalid(self):
        """Test that throw_if_invalid raises ValidationException when invalid."""
        # Arrange
        result = ValidationResult.failure("TEST-001", "Test error")

        # Act & Assert
        with pytest.raises(ValidationException) as exc_info:
            result.throw_if_invalid()

        assert exc_info.value.validation_result == result

    def test_throw_if_invalid_does_not_raise_when_valid(self):
        """Test that throw_if_invalid doesn't raise when valid."""
        # Arrange
        result = ValidationResult.success()

        # Act & Assert (should not raise)
        result.throw_if_invalid()

    def test_get_errors_by_code_filters_correctly(self):
        """Test that get_errors_by_code filters errors by code."""
        # Arrange
        errors = [
            ValidationError("TEST-001", "Error 1"),
            ValidationError("TEST-002", "Error 2"),
            ValidationError("TEST-001", "Error 3"),
        ]
        result = ValidationResult(errors)

        # Act
        filtered = result.get_errors_by_code("TEST-001")

        # Assert
        assert len(filtered) == 2
        assert all(e.code == "TEST-001" for e in filtered)

    def test_get_errors_by_severity_filters_correctly(self):
        """Test that get_errors_by_severity filters errors by severity."""
        # Arrange
        error1 = ValidationError("TEST-001", "Error 1")
        error1.severity = ValidationSeverity.ERROR

        error2 = ValidationError("TEST-002", "Warning 1")
        error2.severity = ValidationSeverity.WARNING

        error3 = ValidationError("TEST-003", "Error 2")
        error3.severity = ValidationSeverity.ERROR

        result = ValidationResult([error1, error2, error3])

        # Act
        filtered = result.get_errors_by_severity(ValidationSeverity.ERROR)

        # Assert
        assert len(filtered) == 2
        assert all(e.severity == ValidationSeverity.ERROR for e in filtered)
'''

        Path(output_path).write_text(test_content)

    def generate_function_call_content_tests(self, output_path: str) -> None:
        """Generate Python tests for FunctionCallContent validation."""

        test_content = '''"""
AUTO-GENERATED: FunctionCallContent validation tests.
Generated from C# validation test patterns.

Tests FunctionCallContent validation rules:
- Required CallId field
- Valid function name format
- Valid JSON arguments
- No duplicate CallIds

DO NOT EDIT THIS FILE MANUALLY.
Regenerate with validation test generator.
"""

import pytest
from microsoft.agents.protocol.models import FunctionCallContent
from microsoft.agents.protocol.validation import (
    FunctionCallContentValidator,
    ValidationContext,
    ValidationErrorCode,
)


class TestFunctionCallContentValidation:
    """Tests for FunctionCallContent validation."""

    def setup_method(self):
        """Set up test fixtures."""
        self.validator = FunctionCallContentValidator()

    def test_validate_valid_function_call_returns_success(self):
        """Test that a valid function call passes validation."""
        # Arrange
        content = FunctionCallContent(
            call_id="call_123",
            name="get_weather",
            arguments='{"location": "Seattle"}'
        )

        # Act
        result = self.validator.validate(content)

        # Assert
        assert result.is_valid

    def test_validate_missing_call_id_returns_error_rel001(self):
        """Test that missing CallId returns REL_001 error."""
        # Arrange
        content = FunctionCallContent(
            call_id="",
            name="get_weather",
            arguments="{}"
        )

        # Act
        result = self.validator.validate(content)

        # Assert
        assert not result.is_valid
        assert any(e.code == ValidationErrorCode.REL_001 for e in result.errors)

    @pytest.mark.parametrize("name", [
        "get-weather",
        "get_weather_123",
        "GetWeather",
    ])
    def test_validate_valid_function_name_returns_success(self, name):
        """Test that valid function names pass validation."""
        # Arrange
        content = FunctionCallContent(
            call_id="call_123",
            name=name,
            arguments="{}"
        )

        # Act
        result = self.validator.validate(content)

        # Assert
        assert result.is_valid

    @pytest.mark.parametrize("name", [
        "get weather",
        "get.weather",
        "get@weather",
    ])
    def test_validate_invalid_function_name_returns_error_cnt003(self, name):
        """Test that invalid function names return CNT_003 error."""
        # Arrange
        content = FunctionCallContent(
            call_id="call_123",
            name=name,
            arguments="{}"
        )

        # Act
        result = self.validator.validate(content)

        # Assert
        assert not result.is_valid
        assert any(e.code == ValidationErrorCode.CNT_003 for e in result.errors)

    def test_validate_invalid_json_returns_error_cnt004(self):
        """Test that invalid JSON arguments return CNT_004 error."""
        # Arrange
        content = FunctionCallContent(
            call_id="call_123",
            name="get_weather",
            arguments="{invalid json"
        )

        # Act
        result = self.validator.validate(content)

        # Assert
        assert not result.is_valid
        assert any(e.code == ValidationErrorCode.CNT_004 for e in result.errors)

    def test_validate_duplicate_call_id_returns_error_rel003(self):
        """Test that duplicate CallIds return REL_003 error."""
        # Arrange
        context = ValidationContext()
        content1 = FunctionCallContent(
            call_id="call_123",
            name="get_weather",
            arguments="{}"
        )
        content2 = FunctionCallContent(
            call_id="call_123",
            name="get_forecast",
            arguments="{}"
        )

        # Act
        self.validator.validate(content1, context)  # First call registers it
        result = self.validator.validate(content2, context)  # Second should detect duplicate

        # Assert
        assert not result.is_valid
        assert any(e.code == ValidationErrorCode.REL_003 for e in result.errors)
'''

        Path(output_path).write_text(test_content)

    def generate_text_content_tests(self, output_path: str) -> None:
        """Generate Python tests for TextContent validation."""

        test_content = '''"""
AUTO-GENERATED: TextContent validation tests.
Generated from C# validation test patterns.

Tests TextContent validation rules:
- Non-empty text required
- Text length limits
- Unicode support

DO NOT EDIT THIS FILE MANUALLY.
Regenerate with validation test generator.
"""

import pytest
from microsoft.agents.protocol.models import TextContent
from microsoft.agents.protocol.validation import (
    TextContentValidator,
    ValidationErrorCode,
)


class TestTextContentValidation:
    """Tests for TextContent validation."""

    def setup_method(self):
        """Set up test fixtures."""
        self.validator = TextContentValidator()

    def test_validate_valid_text_content_returns_success(self):
        """Test that valid text content passes validation."""
        # Arrange
        content = TextContent(text="Hello, world!")

        # Act
        result = self.validator.validate(content)

        # Assert
        assert result.is_valid

    def test_validate_empty_text_returns_error(self):
        """Test that empty text returns validation error."""
        # Arrange
        content = TextContent(text="")

        # Act
        result = self.validator.validate(content)

        # Assert
        assert not result.is_valid

    def test_validate_unicode_text_returns_success(self):
        """Test that Unicode text passes validation."""
        # Arrange
        content = TextContent(text="Hello 世界 🌍")

        # Act
        result = self.validator.validate(content)

        # Assert
        assert result.is_valid

    def test_validate_very_long_text_returns_success(self):
        """Test that very long text is handled correctly."""
        # Arrange
        content = TextContent(text="x" * 10000)

        # Act
        result = self.validator.validate(content)

        # Assert
        assert result.is_valid
'''

        Path(output_path).write_text(test_content)

    def generate_user_message_tests(self, output_path: str) -> None:
        """Generate Python tests for UserMessage validation."""

        test_content = '''"""
AUTO-GENERATED: UserMessage validation tests.
Generated from C# validation test patterns.

Tests UserMessage validation rules:
- Required MessageId field
- Required Contents list (non-empty)
- CreatedAt timestamp validation
- AuthorName length limits
- Content type restrictions

DO NOT EDIT THIS FILE MANUALLY.
Regenerate with validation test generator.
"""

import pytest
from datetime import datetime, timedelta
from microsoft.agents.protocol.models import (
    UserMessage,
    TextContent,
    FunctionCallContent,
)
from microsoft.agents.protocol.validation import (
    UserMessageValidator,
    ValidationErrorCode,
)


class TestUserMessageValidation:
    """Tests for UserMessage validation."""

    def setup_method(self):
        """Set up test fixtures."""
        self.validator = UserMessageValidator()

    def test_validate_valid_user_message_returns_success(self):
        """Test that a valid user message passes validation."""
        # Arrange
        message = UserMessage(
            message_id="msg_001",
            user_id="user_123",
            created_at=datetime.utcnow() - timedelta(minutes=1),
            contents=[TextContent(text="Hello!")]
        )

        # Act
        result = self.validator.validate(message)

        # Assert
        assert result.is_valid

    def test_validate_missing_message_id_returns_error_msg001(self):
        """Test that missing MessageId returns MSG_001 error."""
        # Arrange
        message = UserMessage(
            message_id="",
            created_at=datetime.utcnow(),
            contents=[TextContent(text="Hello")]
        )

        # Act
        result = self.validator.validate(message)

        # Assert
        assert not result.is_valid
        assert any(e.code == ValidationErrorCode.MSG_001 for e in result.errors)

    def test_validate_no_contents_returns_error_msg010(self):
        """Test that empty Contents list returns MSG_010 error."""
        # Arrange
        message = UserMessage(
            message_id="msg_001",
            created_at=datetime.utcnow(),
            contents=[]
        )

        # Act
        result = self.validator.validate(message)

        # Assert
        assert not result.is_valid
        assert any(e.code == ValidationErrorCode.MSG_010 for e in result.errors)

    def test_validate_contains_function_call_returns_error_role005(self):
        """Test that UserMessage with FunctionCall returns ROLE_005 error."""
        # Arrange
        message = UserMessage(
            message_id="msg_001",
            created_at=datetime.utcnow(),
            contents=[
                TextContent(text="Call a function"),
                FunctionCallContent(
                    call_id="call_1",
                    name="test",
                    arguments="{}"
                )
            ]
        )

        # Act
        result = self.validator.validate(message)

        # Assert
        assert not result.is_valid
        assert any(e.code == ValidationErrorCode.ROLE_005 for e in result.errors)

    def test_validate_future_created_at_returns_error_msg004(self):
        """Test that future CreatedAt timestamp returns MSG_004 error."""
        # Arrange
        message = UserMessage(
            message_id="msg_001",
            created_at=datetime.utcnow() + timedelta(hours=1),
            contents=[TextContent(text="Hello")]
        )

        # Act
        result = self.validator.validate(message)

        # Assert
        assert not result.is_valid
        assert any(e.code == ValidationErrorCode.MSG_004 for e in result.errors)

    def test_validate_long_author_name_returns_error_msg005(self):
        """Test that very long AuthorName returns MSG_005 error."""
        # Arrange
        message = UserMessage(
            message_id="msg_001",
            author_name="x" * 101,
            created_at=datetime.utcnow(),
            contents=[TextContent(text="Hello")]
        )

        # Act
        result = self.validator.validate(message)

        # Assert
        assert not result.is_valid
        assert any(e.code == ValidationErrorCode.MSG_005 for e in result.errors)
'''

        Path(output_path).write_text(test_content)

    def generate_tool_message_tests(self, output_path: str) -> None:
        """Generate Python tests for ToolMessage validation."""

        test_content = '''"""
AUTO-GENERATED: ToolMessage validation tests.
Generated from C# validation test patterns.

Tests ToolMessage validation rules:
- Required MessageId field
- Required CallId field
- Required Contents list (non-empty)
- Must contain FunctionResultContent
- CallId must match a previous FunctionCallContent

DO NOT EDIT THIS FILE MANUALLY.
Regenerate with validation test generator.
"""

import pytest
from datetime import datetime
from microsoft.agents.protocol.models import (
    ToolMessage,
    FunctionResultContent,
    TextContent,
)
from microsoft.agents.protocol.validation import (
    ToolMessageValidator,
    ValidationContext,
    ValidationErrorCode,
)


class TestToolMessageValidation:
    """Tests for ToolMessage validation."""

    def setup_method(self):
        """Set up test fixtures."""
        self.validator = ToolMessageValidator()

    def test_validate_valid_tool_message_returns_success(self):
        """Test that a valid tool message passes validation."""
        # Arrange
        message = ToolMessage(
            message_id="msg_001",
            call_id="call_123",
            created_at=datetime.utcnow(),
            contents=[
                FunctionResultContent(
                    call_id="call_123",
                    result='{"temp": 72}'
                )
            ]
        )

        # Act
        result = self.validator.validate(message)

        # Assert
        assert result.is_valid

    def test_validate_missing_message_id_returns_error_msg001(self):
        """Test that missing MessageId returns MSG_001 error."""
        # Arrange
        message = ToolMessage(
            message_id="",
            call_id="call_123",
            created_at=datetime.utcnow(),
            contents=[
                FunctionResultContent(
                    call_id="call_123",
                    result="{}"
                )
            ]
        )

        # Act
        result = self.validator.validate(message)

        # Assert
        assert not result.is_valid
        assert any(e.code == ValidationErrorCode.MSG_001 for e in result.errors)

    def test_validate_missing_call_id_returns_error(self):
        """Test that missing CallId returns validation error."""
        # Arrange
        message = ToolMessage(
            message_id="msg_001",
            call_id="",
            created_at=datetime.utcnow(),
            contents=[
                FunctionResultContent(
                    call_id="call_123",
                    result="{}"
                )
            ]
        )

        # Act
        result = self.validator.validate(message)

        # Assert
        assert not result.is_valid

    def test_validate_no_contents_returns_error_msg010(self):
        """Test that empty Contents list returns MSG_010 error."""
        # Arrange
        message = ToolMessage(
            message_id="msg_001",
            call_id="call_123",
            created_at=datetime.utcnow(),
            contents=[]
        )

        # Act
        result = self.validator.validate(message)

        # Assert
        assert not result.is_valid
        assert any(e.code == ValidationErrorCode.MSG_010 for e in result.errors)

    def test_validate_no_function_result_returns_error(self):
        """Test that ToolMessage without FunctionResultContent fails."""
        # Arrange
        message = ToolMessage(
            message_id="msg_001",
            call_id="call_123",
            created_at=datetime.utcnow(),
            contents=[TextContent(text="Just text")]
        )

        # Act
        result = self.validator.validate(message)

        # Assert
        assert not result.is_valid
'''

        Path(output_path).write_text(test_content)

    def generate_thread_validation_tests(self, output_path: str) -> None:
        """Generate Python tests for Thread validation."""

        test_content = '''"""
AUTO-GENERATED: Thread validation tests.
Generated from C# validation test patterns.

Tests Thread validation rules:
- Required ThreadId field
- Message ordering
- Temporal consistency
- Message ID uniqueness

DO NOT EDIT THIS FILE MANUALLY.
Regenerate with validation test generator.
"""

import pytest
from datetime import datetime, timedelta
from microsoft.agents.protocol.models import (
    Thread,
    UserMessage,
    AgentMessage,
    TextContent,
)
from microsoft.agents.protocol.validation import (
    ThreadValidator,
    ValidationErrorCode,
)


class TestThreadValidation:
    """Tests for Thread validation."""

    def setup_method(self):
        """Set up test fixtures."""
        self.validator = ThreadValidator()

    def test_validate_valid_thread_returns_success(self):
        """Test that a valid thread passes validation."""
        # Arrange
        now = datetime.utcnow()
        thread = Thread(
            thread_id="thread_001",
            created_at=now - timedelta(minutes=5),
            messages=[
                UserMessage(
                    message_id="msg_001",
                    created_at=now - timedelta(minutes=4),
                    contents=[TextContent(text="Hello")]
                ),
                AgentMessage(
                    message_id="msg_002",
                    created_at=now - timedelta(minutes=3),
                    contents=[TextContent(text="Hi there!")]
                ),
            ]
        )

        # Act
        result = self.validator.validate(thread)

        # Assert
        assert result.is_valid

    def test_validate_missing_thread_id_returns_error(self):
        """Test that missing ThreadId returns validation error."""
        # Arrange
        thread = Thread(
            thread_id="",
            created_at=datetime.utcnow(),
            messages=[]
        )

        # Act
        result = self.validator.validate(thread)

        # Assert
        assert not result.is_valid

    def test_validate_duplicate_message_ids_returns_error(self):
        """Test that duplicate message IDs return validation error."""
        # Arrange
        now = datetime.utcnow()
        thread = Thread(
            thread_id="thread_001",
            created_at=now,
            messages=[
                UserMessage(
                    message_id="msg_001",
                    created_at=now,
                    contents=[TextContent(text="Hello")]
                ),
                UserMessage(
                    message_id="msg_001",  # Duplicate!
                    created_at=now,
                    contents=[TextContent(text="World")]
                ),
            ]
        )

        # Act
        result = self.validator.validate(thread)

        # Assert
        assert not result.is_valid

    def test_validate_messages_out_of_order_returns_error(self):
        """Test that messages not in chronological order fail validation."""
        # Arrange
        now = datetime.utcnow()
        thread = Thread(
            thread_id="thread_001",
            created_at=now - timedelta(minutes=5),
            messages=[
                UserMessage(
                    message_id="msg_001",
                    created_at=now,  # Later timestamp
                    contents=[TextContent(text="Hello")]
                ),
                UserMessage(
                    message_id="msg_002",
                    created_at=now - timedelta(minutes=1),  # Earlier timestamp
                    contents=[TextContent(text="World")]
                ),
            ]
        )

        # Act
        result = self.validator.validate(thread)

        # Assert
        assert not result.is_valid
'''

        Path(output_path).write_text(test_content)

    def generate_image_content_tests(self, output_path: str) -> None:
        """Generate Python tests for ImageContent validation."""

        test_content = '''"""
AUTO-GENERATED: ImageContent validation tests.
Generated from C# validation test patterns.

Tests ImageContent validation rules:
- Valid image URL or data
- Supported MIME types
- Size constraints
- Alt text requirements

DO NOT EDIT THIS FILE MANUALLY.
Regenerate with validation test generator.
"""

import pytest
from microsoft.agents.protocol.models import ImageContent
from microsoft.agents.protocol.validation import (
    ImageContentValidator,
    ValidationErrorCode,
)


class TestImageContentValidation:
    """Tests for ImageContent validation."""

    def setup_method(self):
        """Set up test fixtures."""
        self.validator = ImageContentValidator()

    def test_validate_valid_image_url_returns_success(self):
        """Test that valid image URL passes validation."""
        # Arrange
        content = ImageContent(
            url="https://example.com/image.jpg",
            mime_type="image/jpeg"
        )

        # Act
        result = self.validator.validate(content)

        # Assert
        assert result.is_valid

    def test_validate_image_data_returns_success(self):
        """Test that valid base64 image data passes validation."""
        # Arrange
        content = ImageContent(
            data="iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==",
            mime_type="image/png"
        )

        # Act
        result = self.validator.validate(content)

        # Assert
        assert result.is_valid

    @pytest.mark.parametrize("mime_type", [
        "image/jpeg",
        "image/png",
        "image/gif",
        "image/webp",
    ])
    def test_validate_supported_mime_types_return_success(self, mime_type):
        """Test that supported MIME types pass validation."""
        # Arrange
        content = ImageContent(
            url="https://example.com/image.jpg",
            mime_type=mime_type
        )

        # Act
        result = self.validator.validate(content)

        # Assert
        assert result.is_valid
'''

        Path(output_path).write_text(test_content)

    def generate_error_content_tests(self, output_path: str) -> None:
        """Generate Python tests for ErrorContent validation."""

        test_content = '''"""
AUTO-GENERATED: ErrorContent validation tests.
Generated from C# validation test patterns.

Tests ErrorContent validation rules:
- Required error code
- Error message length
- Error details structure
- Severity levels

DO NOT EDIT THIS FILE MANUALLY.
Regenerate with validation test generator.
"""

import pytest
from microsoft.agents.protocol.models import ErrorContent
from microsoft.agents.protocol.validation import (
    ErrorContentValidator,
    ValidationErrorCode,
)


class TestErrorContentValidation:
    """Tests for ErrorContent validation."""

    def setup_method(self):
        """Set up test fixtures."""
        self.validator = ErrorContentValidator()

    def test_validate_valid_error_content_returns_success(self):
        """Test that valid error content passes validation."""
        # Arrange
        content = ErrorContent(
            code="ERR_001",
            message="An error occurred",
        )

        # Act
        result = self.validator.validate(content)

        # Assert
        assert result.is_valid

    def test_validate_missing_error_code_returns_error(self):
        """Test that missing error code returns validation error."""
        # Arrange
        content = ErrorContent(
            code="",
            message="Error without code",
        )

        # Act
        result = self.validator.validate(content)

        # Assert
        assert not result.is_valid

    def test_validate_missing_error_message_returns_error(self):
        """Test that missing error message returns validation error."""
        # Arrange
        content = ErrorContent(
            code="ERR_001",
            message="",
        )

        # Act
        result = self.validator.validate(content)

        # Assert
        assert not result.is_valid
'''

        Path(output_path).write_text(test_content)

    def generate_function_result_content_tests(self, output_path: str) -> None:
        """Generate Python tests for FunctionResultContent validation."""

        test_content = '''"""
AUTO-GENERATED: FunctionResultContent validation tests.
Generated from C# validation test patterns.

Tests FunctionResultContent validation rules:
- Required CallId field
- CallId must match previous FunctionCallContent
- Valid JSON result
- Error handling

DO NOT EDIT THIS FILE MANUALLY.
Regenerate with validation test generator.
"""

import pytest
from microsoft.agents.protocol.models import FunctionResultContent
from microsoft.agents.protocol.validation import (
    FunctionResultContentValidator,
    ValidationContext,
    ValidationErrorCode,
)


class TestFunctionResultContentValidation:
    """Tests for FunctionResultContent validation."""

    def setup_method(self):
        """Set up test fixtures."""
        self.validator = FunctionResultContentValidator()

    def test_validate_valid_function_result_returns_success(self):
        """Test that valid function result passes validation."""
        # Arrange
        content = FunctionResultContent(
            call_id="call_123",
            result='{"status": "success"}',
        )

        # Act
        result = self.validator.validate(content)

        # Assert
        assert result.is_valid

    def test_validate_missing_call_id_returns_error(self):
        """Test that missing CallId returns validation error."""
        # Arrange
        content = FunctionResultContent(
            call_id="",
            result="{}",
        )

        # Act
        result = self.validator.validate(content)

        # Assert
        assert not result.is_valid

    def test_validate_invalid_json_result_returns_error(self):
        """Test that invalid JSON result returns validation error."""
        # Arrange
        content = FunctionResultContent(
            call_id="call_123",
            result="{invalid json",
        )

        # Act
        result = self.validator.validate(content)

        # Assert
        assert not result.is_valid
'''

        Path(output_path).write_text(test_content)

    def generate_all_python_validation_tests(self, base_output_dir: str) -> List[str]:
        """Generate all Python validation tests.

        Args:
            base_output_dir: Base directory for test output (e.g., python/microsoft-agents-protocol/tests)

        Returns:
            List of generated file paths
        """
        base_path = Path(base_output_dir)
        generated_files = []

        # Core tests
        core_dir = base_path / "validation" / "core"
        core_dir.mkdir(parents=True, exist_ok=True)

        validation_result_file = core_dir / "test_validation_result.py"
        self.generate_validation_result_tests(str(validation_result_file))
        generated_files.append(str(validation_result_file))

        # Content tests
        content_dir = base_path / "validation" / "content"
        content_dir.mkdir(parents=True, exist_ok=True)

        function_call_file = content_dir / "test_function_call_content_validator.py"
        self.generate_function_call_content_tests(str(function_call_file))
        generated_files.append(str(function_call_file))

        text_content_file = content_dir / "test_text_content_validator.py"
        self.generate_text_content_tests(str(text_content_file))
        generated_files.append(str(text_content_file))

        image_content_file = content_dir / "test_image_content_validator.py"
        self.generate_image_content_tests(str(image_content_file))
        generated_files.append(str(image_content_file))

        error_content_file = content_dir / "test_error_content_validator.py"
        self.generate_error_content_tests(str(error_content_file))
        generated_files.append(str(error_content_file))

        function_result_file = content_dir / "test_function_result_content_validator.py"
        self.generate_function_result_content_tests(str(function_result_file))
        generated_files.append(str(function_result_file))

        # Message tests
        message_dir = base_path / "validation" / "message"
        message_dir.mkdir(parents=True, exist_ok=True)

        user_message_file = message_dir / "test_user_message_validator.py"
        self.generate_user_message_tests(str(user_message_file))
        generated_files.append(str(user_message_file))

        tool_message_file = message_dir / "test_tool_message_validator.py"
        self.generate_tool_message_tests(str(tool_message_file))
        generated_files.append(str(tool_message_file))

        # Thread tests
        thread_file = base_path / "validation" / "test_thread_validator.py"
        self.generate_thread_validation_tests(str(thread_file))
        generated_files.append(str(thread_file))

        # Create __init__.py files
        for subdir in ["validation", "validation/core", "validation/content", "validation/message"]:
            init_file = base_path / subdir / "__init__.py"
            if not init_file.exists():
                init_file.write_text('"""Validation tests."""\n')

        return generated_files


def generate_python_validation_tests(output_dir: str) -> List[str]:
    """Main function to generate Python validation tests.

    Args:
        output_dir: Base output directory for tests

    Returns:
        List of generated file paths
    """
    generator = ValidationTestGenerator()
    return generator.generate_all_python_validation_tests(output_dir)
