// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-08T19:57:10Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents.Abstractions.Models
{
    /// <summary>/// XML: &lt;adaptive-card version="1.5" fallback-text="..."&gt;{"type":"AdaptiveCard",...}&lt;/adaptive-card&gt;/// </summary>
    [XmlRoot("adaptive-card")]
    public partial class AdaptiveCardContent : AIContentBase
    {
        public override string Kind => "adaptiveCard";

        [XmlAttribute("version")]
        [JsonPropertyName("version")]
        public string Version { get; set; }
        [XmlAttribute("fallback-text")]
        [JsonPropertyName("fallbackText")]
        public string FallbackText { get; set; }
        [XmlText]
        [JsonPropertyName("card")]
        public string Card { get; set; }
    }
}