using System;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Base class for all AI content types. Supports polymorphic XML and JSON serialization./// </summary>
    [XmlInclude(typeof(TextContent)), XmlInclude(typeof(FunctionCallContent)), XmlInclude(typeof(FunctionResultContent)), XmlInclude(typeof(ErrorContent)), XmlInclude(typeof(TextReasoningContent)), XmlInclude(typeof(DataContent)), XmlInclude(typeof(UriContent)), XmlInclude(typeof(ImageContent)), XmlInclude(typeof(AudioContent)), XmlInclude(typeof(TranscriptContent)), XmlInclude(typeof(VideoContent)), XmlInclude(typeof(FileContent)), XmlInclude(typeof(SearchResultContent)), XmlInclude(typeof(DocumentContent)), XmlInclude(typeof(AdaptiveCardContent)), XmlInclude(typeof(RefusalContent)), XmlInclude(typeof(ContentFilterResultContent)), XmlInclude(typeof(UserInputRequestContent)), XmlInclude(typeof(SuggestedActionsContent)), XmlInclude(typeof(EventContent)), XmlInclude(typeof(TraceContent)), XmlInclude(typeof(ActionContent)), XmlInclude(typeof(TypingIndicatorContent)), XmlInclude(typeof(MessageReactionContent)), XmlInclude(typeof(MessageDeleteContent)), XmlInclude(typeof(MessageUpdateContent)), XmlInclude(typeof(HostedFileContent)), XmlInclude(typeof(HostedVectorStoreContent)), JsonPolymorphic(TypeDiscriminatorPropertyName = "kind"), JsonDerivedType(typeof(TextContent), "text"), JsonDerivedType(typeof(FunctionCallContent), "function-call"), JsonDerivedType(typeof(FunctionResultContent), "function-result"), JsonDerivedType(typeof(ErrorContent), "error"), JsonDerivedType(typeof(TextReasoningContent), "text-reasoning"), JsonDerivedType(typeof(DataContent), "data"), JsonDerivedType(typeof(UriContent), "uri"), JsonDerivedType(typeof(ImageContent), "image"), JsonDerivedType(typeof(AudioContent), "audio"), JsonDerivedType(typeof(TranscriptContent), "transcript"), JsonDerivedType(typeof(VideoContent), "video"), JsonDerivedType(typeof(FileContent), "file"), JsonDerivedType(typeof(SearchResultContent), "search-result"), JsonDerivedType(typeof(DocumentContent), "document"), JsonDerivedType(typeof(AdaptiveCardContent), "adaptive-card"), JsonDerivedType(typeof(RefusalContent), "refusal"), JsonDerivedType(typeof(ContentFilterResultContent), "filter-result"), JsonDerivedType(typeof(UserInputRequestContent), "user-input-request"), JsonDerivedType(typeof(SuggestedActionsContent), "suggested-actions"), JsonDerivedType(typeof(EventContent), "event"), JsonDerivedType(typeof(TraceContent), "trace"), JsonDerivedType(typeof(ActionContent), "action"), JsonDerivedType(typeof(TypingIndicatorContent), "typing-indicator"), JsonDerivedType(typeof(MessageReactionContent), "message-reaction"), JsonDerivedType(typeof(MessageDeleteContent), "message-delete"), JsonDerivedType(typeof(MessageUpdateContent), "message-update"), JsonDerivedType(typeof(HostedFileContent), "hosted-file"), JsonDerivedType(typeof(HostedVectorStoreContent), "hosted-vector-store")]
    public abstract partial class AIContent
    {
        [XmlAttribute("kind"), JsonPropertyName("kind")]
        public abstract string Kind { get; }
    }
}