// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-08T19:57:10Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents.Abstractions.Models
{
    /// <summary>/// XML: &lt;file uri="..." filename="..." mime-type="..." size-bytes="1024" /&gt;/// </summary>
    [XmlRoot("file")]
    public partial class FileContent : AIContentBase
    {
        public override string Kind => "file";

        [XmlAttribute("uri")]
        [JsonPropertyName("uri")]
        public string Uri { get; set; }
        [XmlAttribute("filename")]
        [JsonPropertyName("filename")]
        public string Filename { get; set; }
        [XmlAttribute("mime-type")]
        [JsonPropertyName("mimeType")]
        public string MimeType { get; set; }
        [XmlAttribute("size-bytes")]
        [JsonPropertyName("sizeBytes")]
        public long SizeBytes { get; set; }
    }
}