// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-08T19:57:10Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents.Abstractions.Models
{
    /// <summary>/// Function Result Content/// BASE: Microsoft.Extensions.AI.FunctionResultContent/// SOURCE: /extensions/src/Libraries/Microsoft.Extensions.AI.Abstractions/Contents/FunctionResultContent.cs/// REPRESENTS: Result of tool execution/// XML: &lt;function-result call-id="..." name="..."&gt;{"result": "value"}&lt;/function-result&gt;/// </summary>
    [XmlRoot("function-result")]
    public partial class FunctionResultContent : AIContentBase
    {
        public override string Kind => "functionResult";

        [XmlAttribute("call-id")]
        [JsonPropertyName("callId")]
        public string CallId { get; set; }
        [XmlAttribute("name")]
        [JsonPropertyName("name")]
        public string Name { get; set; }
        [XmlText]
        [JsonPropertyName("result")]
        public string Result { get; set; }
    }
}