// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-08T19:57:10Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents.Abstractions.Models
{
    /// <summary>/// Image Content/// FROM: Azure Agent API (ImageContent)/// ADDITION: Not in MAF/// Provides three delivery methods: uri, dataUri, or raw data bytes./// M365: Future multi-modal scenarios/// XML: &lt;image uri="..." mime-type="..." width="1920" height="1080" /&gt;/// </summary>
    [XmlRoot("image")]
    public partial class ImageContent : AIContentBase
    {
        public override string Kind => "image";

        [XmlAttribute("uri")]
        [JsonPropertyName("uri")]
        public string Uri { get; set; }
        [XmlAttribute("alt")]
        [JsonPropertyName("alt")]
        public string Alt { get; set; }
        [XmlAttribute("mime-type")]
        [JsonPropertyName("mimeType")]
        public string MimeType { get; set; }
        [XmlAttribute("width")]
        [JsonPropertyName("width")]
        public int Width { get; set; }
        [XmlAttribute("height")]
        [JsonPropertyName("height")]
        public int Height { get; set; }
    }
}