// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-08T19:57:10Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents.Abstractions.Models
{
    [XmlRoot("message-reaction")]
    public partial class MessageReactionContent : AIContentBase
    {
        public override string Kind => "messageReaction";

        [XmlAttribute("referenced-message-id")]
        [JsonPropertyName("referencedMessageId")]
        public string ReferencedMessageId { get; set; }
        [XmlElement("added")]
        [JsonPropertyName("reactionsAdded")]
        public List<MessageReaction> ReactionsAdded { get; set; }
        [XmlElement("removed")]
        [JsonPropertyName("reactionsRemoved")]
        public List<MessageReaction> ReactionsRemoved { get; set; }
    }
}