// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-08T19:57:10Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents.Abstractions.Models
{
    /// <summary>/// Suggested Action/// Represents a single quick reply button/action/// </summary>
    [XmlType("action")]
    public partial class SuggestedAction
    {
        [XmlAttribute("title")]
        [JsonPropertyName("title")]
        public string Title { get; set; }
        [XmlAttribute("type")]
        [JsonPropertyName("actionType")]
        public string ActionType { get; set; }
        [XmlAttribute("value")]
        [JsonPropertyName("value")]
        public string Value { get; set; }
        [XmlAttribute("text")]
        [JsonPropertyName("text")]
        public string Text { get; set; }
    }
}