// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-08T19:57:10Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents.Abstractions.Models
{
    /// <summary>/// Text Reasoning Content/// BASE: Microsoft.Extensions.AI.TextReasoningContent/// SOURCE: /extensions/src/Libraries/Microsoft.Extensions.AI.Abstractions/Contents/TextReasoningContent.cs/// FROM: Extended thinking support (Anthropic, OpenAI o1/o3)/// ADDITION: Added 'exposed' flag from Anthropic/// - exposed = true: Reasoning visible to user/// - exposed = false: Internal reasoning trace/// XML: &lt;thinking exposed="false"&gt;Internal reasoning...&lt;/thinking&gt;/// </summary>
    [XmlRoot("text-reasoning")]
    public partial class TextReasoningContent : AIContentBase
    {
        public override string Kind => "reasoning";

        [XmlText]
        [JsonPropertyName("text")]
        public string Text { get; set; }
        [XmlAttribute("exposed")]
        [JsonPropertyName("exposed")]
        public bool Exposed { get; set; } = false;
    }
}