// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-08T19:57:10Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents.Abstractions.Models
{
    /// <summary>/// Tool message./// </summary>
    [XmlRoot("tool")]
    public partial class ToolMessage : ChatMessage
    {
        public override ChatRole Role => ChatRole.Tool;

        [XmlAttribute("call-id")]
        public string? CallId { get; set; }
        [XmlAttribute("name")]
        public string? Name { get; set; }
        [XmlElement("function-result", Type = typeof(FunctionResultContent)), XmlElement("error", Type = typeof(ErrorContent))]
        public List<AIContent> Contents { get; set; } = new List<AIContent>();
    }
}
// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-08T19:57:10Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

