// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-08T19:57:10Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents.Abstractions.Models
{
    /// <summary>/// XML: &lt;typing-indicator from="user_123" status="typing" timestamp="..." /&gt;/// </summary>
    [XmlRoot("typing-indicator")]
    public partial class TypingIndicatorContent : AIContentBase
    {
        public override string Kind => "typingIndicator";

        [XmlAttribute("from")]
        [JsonPropertyName("from")]
        public string From { get; set; }
        [XmlAttribute("timestamp")]
        [JsonPropertyName("timestamp")]
        public DateTime Timestamp { get; set; }
    }
}