// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-08T19:57:10Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents.Abstractions.Models
{
    /// <summary>/// User message./// </summary>
    [XmlRoot("user")]
    public partial class UserMessage : ChatMessage
    {
        public override ChatRole Role => ChatRole.User;

        [XmlAttribute("user-id")]
        public string? UserId { get; set; }
        [XmlElement("text", Type = typeof(TextContent)), XmlElement("image", Type = typeof(ImageContent)), XmlElement("audio", Type = typeof(AudioContent)), XmlElement("video", Type = typeof(VideoContent)), XmlElement("file", Type = typeof(FileContent)), XmlElement("transcript", Type = typeof(TranscriptContent))]
        public List<AIContent> Contents { get; set; } = new List<AIContent>();
    }
}
// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-08T19:57:10Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

