// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-08T19:57:10Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents.Abstractions.Models
{
    /// <summary>/// Word Timing/// ADDITION: For synchronized transcript playback/// PURPOSE: Word-level timestamps for highlighting during audio/video playback/// </summary>
    public partial class WordTiming
    {
        [XmlElement("word")]
        [JsonPropertyName("word")]
        public string Word { get; set; }
        [XmlElement("start")]
        [JsonPropertyName("start")]
        public float Start { get; set; }
        [XmlElement("end")]
        [JsonPropertyName("end")]
        public float End { get; set; }
        [XmlElement("confidence")]
        [JsonPropertyName("confidence")]
        public float? Confidence { get; set; }
    }
}