"""
AUTO-GENERATED: ErrorContent validation tests.
Generated from C# validation test patterns.

Tests ErrorContent validation rules:
- Required error code
- Error message length
- Error details structure
- Severity levels

DO NOT EDIT THIS FILE MANUALLY.
Regenerate with validation test generator.
"""

import pytest
from microsoft.agents.protocol.models import ErrorContent
from microsoft.agents.protocol.validation import (
    ErrorContentValidator,
    ValidationErrorCode,
)


class TestErrorContentValidation:
    """Tests for ErrorContent validation."""

    def setup_method(self):
        """Set up test fixtures."""
        self.validator = ErrorContentValidator()

    def test_validate_valid_error_content_returns_success(self):
        """Test that valid error content passes validation."""
        # Arrange
        content = ErrorContent(
            code="ERR_001",
            message="An error occurred",
        )

        # Act
        result = self.validator.validate(content)

        # Assert
        assert result.is_valid

    def test_validate_missing_error_code_returns_error(self):
        """Test that missing error code returns validation error."""
        # Arrange
        content = ErrorContent(
            code="",
            message="Error without code",
        )

        # Act
        result = self.validator.validate(content)

        # Assert
        assert not result.is_valid

    def test_validate_missing_error_message_returns_error(self):
        """Test that missing error message returns validation error."""
        # Arrange
        content = ErrorContent(
            code="ERR_001",
            message="",
        )

        # Act
        result = self.validator.validate(content)

        # Assert
        assert not result.is_valid
