"""
AUTO-GENERATED: ImageContent validation tests.
Generated from C# validation test patterns.

Tests ImageContent validation rules:
- Valid image URL or data
- Supported MIME types
- Size constraints
- Alt text requirements

DO NOT EDIT THIS FILE MANUALLY.
Regenerate with validation test generator.
"""

import pytest
from microsoft.agents.protocol.models import ImageContent
from microsoft.agents.protocol.validation import (
    ImageContentValidator,
    ValidationErrorCode,
)


class TestImageContentValidation:
    """Tests for ImageContent validation."""

    def setup_method(self):
        """Set up test fixtures."""
        self.validator = ImageContentValidator()

    def test_validate_valid_image_url_returns_success(self):
        """Test that valid image URL passes validation."""
        # Arrange
        content = ImageContent(
            url="https://example.com/image.jpg",
            mime_type="image/jpeg"
        )

        # Act
        result = self.validator.validate(content)

        # Assert
        assert result.is_valid

    def test_validate_image_data_returns_success(self):
        """Test that valid base64 image data passes validation."""
        # Arrange
        content = ImageContent(
            data="iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==",
            mime_type="image/png"
        )

        # Act
        result = self.validator.validate(content)

        # Assert
        assert result.is_valid

    @pytest.mark.parametrize("mime_type", [
        "image/jpeg",
        "image/png",
        "image/gif",
        "image/webp",
    ])
    def test_validate_supported_mime_types_return_success(self, mime_type):
        """Test that supported MIME types pass validation."""
        # Arrange
        content = ImageContent(
            url="https://example.com/image.jpg",
            mime_type=mime_type
        )

        # Act
        result = self.validator.validate(content)

        # Assert
        assert result.is_valid
