"""
AUTO-GENERATED: FunctionCallContent validation tests.
Generated from C# validation test patterns.

Tests FunctionCallContent validation rules:
- Required CallId field
- Valid function name format
- Valid JSON arguments
- No duplicate CallIds

DO NOT EDIT THIS FILE MANUALLY.
Regenerate with validation test generator.
"""

import pytest
from microsoft.agents.protocol.models import FunctionCallContent
from microsoft.agents.protocol.validation import (
    FunctionCallContentValidator,
    ValidationContext,
    ValidationErrorCode,
)


class TestFunctionCallContentValidation:
    """Tests for FunctionCallContent validation."""

    def setup_method(self):
        """Set up test fixtures."""
        self.validator = FunctionCallContentValidator()

    def test_validate_valid_function_call_returns_success(self):
        """Test that a valid function call passes validation."""
        # Arrange
        content = FunctionCallContent(
            call_id="call_123",
            name="get_weather",
            arguments='{"location": "Seattle"}'
        )

        # Act
        result = self.validator.validate(content)

        # Assert
        assert result.is_valid

    def test_validate_missing_call_id_returns_error_rel001(self):
        """Test that missing CallId returns REL_001 error."""
        # Arrange
        content = FunctionCallContent(
            call_id="",
            name="get_weather",
            arguments="{}"
        )

        # Act
        result = self.validator.validate(content)

        # Assert
        assert not result.is_valid
        assert any(e.code == ValidationErrorCode.REL_001 for e in result.errors)

    @pytest.mark.parametrize("name", [
        "get-weather",
        "get_weather_123",
        "GetWeather",
    ])
    def test_validate_valid_function_name_returns_success(self, name):
        """Test that valid function names pass validation."""
        # Arrange
        content = FunctionCallContent(
            call_id="call_123",
            name=name,
            arguments="{}"
        )

        # Act
        result = self.validator.validate(content)

        # Assert
        assert result.is_valid

    @pytest.mark.parametrize("name", [
        "get weather",
        "get.weather",
        "get@weather",
    ])
    def test_validate_invalid_function_name_returns_error_cnt003(self, name):
        """Test that invalid function names return CNT_003 error."""
        # Arrange
        content = FunctionCallContent(
            call_id="call_123",
            name=name,
            arguments="{}"
        )

        # Act
        result = self.validator.validate(content)

        # Assert
        assert not result.is_valid
        assert any(e.code == ValidationErrorCode.CNT_003 for e in result.errors)

    def test_validate_invalid_json_returns_error_cnt004(self):
        """Test that invalid JSON arguments return CNT_004 error."""
        # Arrange
        content = FunctionCallContent(
            call_id="call_123",
            name="get_weather",
            arguments="{invalid json"
        )

        # Act
        result = self.validator.validate(content)

        # Assert
        assert not result.is_valid
        assert any(e.code == ValidationErrorCode.CNT_004 for e in result.errors)

    def test_validate_duplicate_call_id_returns_error_rel003(self):
        """Test that duplicate CallIds return REL_003 error."""
        # Arrange
        context = ValidationContext()
        content1 = FunctionCallContent(
            call_id="call_123",
            name="get_weather",
            arguments="{}"
        )
        content2 = FunctionCallContent(
            call_id="call_123",
            name="get_forecast",
            arguments="{}"
        )

        # Act
        self.validator.validate(content1, context)  # First call registers it
        result = self.validator.validate(content2, context)  # Second should detect duplicate

        # Assert
        assert not result.is_valid
        assert any(e.code == ValidationErrorCode.REL_003 for e in result.errors)
