"""
AUTO-GENERATED: UserMessage validation tests.
Generated from C# validation test patterns.

Tests UserMessage validation rules:
- Required MessageId field
- Required Contents list (non-empty)
- CreatedAt timestamp validation
- AuthorName length limits
- Content type restrictions

DO NOT EDIT THIS FILE MANUALLY.
Regenerate with validation test generator.
"""

import pytest
from datetime import datetime, timedelta
from microsoft.agents.protocol.models import (
    UserMessage,
    TextContent,
    FunctionCallContent,
)
from microsoft.agents.protocol.validation import (
    UserMessageValidator,
    ValidationErrorCode,
)


class TestUserMessageValidation:
    """Tests for UserMessage validation."""

    def setup_method(self):
        """Set up test fixtures."""
        self.validator = UserMessageValidator()

    def test_validate_valid_user_message_returns_success(self):
        """Test that a valid user message passes validation."""
        # Arrange
        message = UserMessage(
            message_id="msg_001",
            user_id="user_123",
            created_at=datetime.utcnow() - timedelta(minutes=1),
            contents=[TextContent(text="Hello!")]
        )

        # Act
        result = self.validator.validate(message)

        # Assert
        assert result.is_valid

    def test_validate_missing_message_id_returns_error_msg001(self):
        """Test that missing MessageId returns MSG_001 error."""
        # Arrange
        message = UserMessage(
            message_id="",
            created_at=datetime.utcnow(),
            contents=[TextContent(text="Hello")]
        )

        # Act
        result = self.validator.validate(message)

        # Assert
        assert not result.is_valid
        assert any(e.code == ValidationErrorCode.MSG_001 for e in result.errors)

    def test_validate_no_contents_returns_error_msg010(self):
        """Test that empty Contents list returns MSG_010 error."""
        # Arrange
        message = UserMessage(
            message_id="msg_001",
            created_at=datetime.utcnow(),
            contents=[]
        )

        # Act
        result = self.validator.validate(message)

        # Assert
        assert not result.is_valid
        assert any(e.code == ValidationErrorCode.MSG_010 for e in result.errors)

    def test_validate_contains_function_call_returns_error_role005(self):
        """Test that UserMessage with FunctionCall returns ROLE_005 error."""
        # Arrange
        message = UserMessage(
            message_id="msg_001",
            created_at=datetime.utcnow(),
            contents=[
                TextContent(text="Call a function"),
                FunctionCallContent(
                    call_id="call_1",
                    name="test",
                    arguments="{}"
                )
            ]
        )

        # Act
        result = self.validator.validate(message)

        # Assert
        assert not result.is_valid
        assert any(e.code == ValidationErrorCode.ROLE_005 for e in result.errors)

    def test_validate_future_created_at_returns_error_msg004(self):
        """Test that future CreatedAt timestamp returns MSG_004 error."""
        # Arrange
        message = UserMessage(
            message_id="msg_001",
            created_at=datetime.utcnow() + timedelta(hours=1),
            contents=[TextContent(text="Hello")]
        )

        # Act
        result = self.validator.validate(message)

        # Assert
        assert not result.is_valid
        assert any(e.code == ValidationErrorCode.MSG_004 for e in result.errors)

    def test_validate_long_author_name_returns_error_msg005(self):
        """Test that very long AuthorName returns MSG_005 error."""
        # Arrange
        message = UserMessage(
            message_id="msg_001",
            author_name="x" * 101,
            created_at=datetime.utcnow(),
            contents=[TextContent(text="Hello")]
        )

        # Act
        result = self.validator.validate(message)

        # Assert
        assert not result.is_valid
        assert any(e.code == ValidationErrorCode.MSG_005 for e in result.errors)
