// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:27:44Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// XML: &lt;action name="button_clicked" text="Refresh" timestamp="..."&gt;{value}&lt;/action&gt;/// </summary>
    [XmlRoot("action")]
    public partial class ActionContent : AIContentBase
    {
        [JsonIgnore]
#pragma warning disable CS1591, CS1587
        public override string Kind => "action";
#pragma warning restore CS1591, CS1587
        /// <summary>/// Gets or sets the name./// </summary>
        [XmlAttribute("name")]
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>/// Gets or sets the text./// </summary>
        [XmlAttribute("text")]
        [JsonPropertyName("text")]
        public string Text { get; set; }

        /// <summary>/// Gets or sets the timestamp./// </summary>
        [XmlAttribute("timestamp")]
        [JsonPropertyName("timestamp")]
        public DateTime Timestamp { get; set; }

        /// <summary>/// Gets or sets the value./// </summary>
        [XmlText]
        [JsonPropertyName("value")]
        public string Value { get; set; }
    }
}