// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:18:38Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// XML: &lt;adaptive-card version="1.5" fallback-text="..."&gt;{"type":"AdaptiveCard",...}&lt;/adaptive-card&gt;/// </summary>
    [XmlRoot("adaptive-card")]
    public partial class AdaptiveCardContent : AIContentBase
    {
        [JsonIgnore]
#pragma warning disable CS1591, CS1587
        public override string Kind => "adaptiveCard";
#pragma warning restore CS1591, CS1587
        /// <summary>/// Gets or sets the version./// </summary>
        [XmlAttribute("version")]
        [JsonPropertyName("version")]
        public string Version { get; set; }

        /// <summary>/// Gets or sets the fallback-text./// </summary>
        [XmlAttribute("fallback-text")]
        [JsonPropertyName("fallbackText")]
        public string FallbackText { get; set; }

        /// <summary>/// Gets or sets the card./// </summary>
        [XmlText]
        [JsonPropertyName("card")]
        public string Card { get; set; }
    }
}