// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:27:47Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Agent Model Configuration/// FROM: Azure Agent API/// ALIGNED WITH: Agent Schema Model/// SOURCE: https://github.com/microsoft/AgentSchema (agentschema/model/model.tsp)/// </summary>
    public partial class AgentModel
    {
        /// <summary>/// Model identifier (e.g., "gpt-4o", "claude-sonnet-4")./// ALIGNED WITH: Agent Schema Model.id/// </summary>
        [XmlElement("id")]
        [JsonPropertyName("id")]
        public string Id { get; set; }

        /// <summary>/// Provider name (e.g., "openai", "azure", "anthropic", "google")./// ALIGNED WITH: Agent Schema Model.provider/// </summary>
        [XmlElement("provider")]
        [JsonPropertyName("provider")]
        public string Provider { get; set; }

        /// <summary>/// API type (e.g., "chat", "responses")./// ALIGNED WITH: Agent Schema Model.apiType/// ADDITION: Not in original design/// RATIONALE: Distinguishes between API patterns (chat completion vs response stream)/// </summary>
        [XmlElement("api-type")]
        [JsonPropertyName("apiType")]
        public string ApiType { get; set; }

        /// <summary>/// Model service authentication./// ALIGNED WITH: Agent Schema Model.connection/// RENAMED FROM: endpoint (now part of connection)/// RATIONALE: Connection includes both endpoint and authentication/// </summary>
        [XmlElement("connection")]
        [JsonPropertyName("connection")]
        public Connection? Connection { get; set; }

        /// <summary>/// Model behavior parameters./// ALIGNED WITH: Agent Schema Model.options/// </summary>
        [XmlElement("options")]
        [JsonPropertyName("options")]
        public ModelOptions? Options { get; set; }
    }
}