// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:15:45Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Represents a agent-created-event./// </summary>
    public partial class AgentCreatedEvent : AgentEvent
    {
        /// <summary>/// Gets or sets the agent-id./// </summary>
        [XmlElement("agent-id")]
        [JsonPropertyName("agentId")]
        public string AgentId { get; set; }

        /// <summary>/// Gets or sets the event-seq./// </summary>
        [XmlElement("event-seq")]
        [JsonPropertyName("eventSeq")]
        public long EventSeq { get; set; }

        /// <summary>/// Gets or sets the name./// </summary>
        [XmlElement("name")]
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>/// Gets or sets the created-at./// </summary>
        [XmlElement("created-at")]
        [JsonPropertyName("createdAt")]
        public DateTime CreatedAt { get; set; }
    }
}