// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:15:44Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Documentation type for categorization/// </summary>
    public partial class AgentCard
    {
        /// <summary>/// Unique agent identifier./// FROM: Agent Schema PromptAgent.name/// USAGE: Client uses this to reference agent in Run.agentId/// M365/ENTRA: This is also the Entra ID Application (Client) ID for the agent/// EXAMPLE: "12345678-1234-1234-1234-123456789012"/// </summary>
        [XmlElement("agent-id")]
        [JsonPropertyName("agentId")]
        public string AgentId { get; set; }

        /// <summary>/// Human-readable agent name./// A2A EQUIVALENT: Agent Card "name"/// </summary>
        [XmlElement("name")]
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>/// UI display name (localized, friendly)./// ADDITION: Not in A2A/// </summary>
        [XmlElement("display-name")]
        [JsonPropertyName("displayName")]
        public string DisplayName { get; set; }

        /// <summary>/// Agent capabilities description./// A2A EQUIVALENT: Agent Card "description"/// GUIDANCE: 1-3 sentences explaining what agent does/// </summary>
        [XmlElement("description")]
        [JsonPropertyName("description")]
        public string Description { get; set; }

        /// <summary>/// Agent version (semantic versioning)./// A2A EQUIVALENT: Agent Card "version"/// EXAMPLES: "1.0.0", "2.1.3-beta"/// </summary>
        [XmlElement("version")]
        [JsonPropertyName("version")]
        public string Version { get; set; }

        /// <summary>/// Agent icon/logo URL./// A2A EQUIVALENT: Agent Card "iconUrl"/// </summary>
        [XmlElement("icon-url")]
        [JsonPropertyName("iconUrl")]
        public string IconUrl { get; set; }

        /// <summary>/// Contact information for agent support./// @usage/// Use Cases:/// - Report bugs or issues with the agent/// - Request features or enhancements/// - Get help with agent integration/// - Contact agent maintainers/// </summary>
        [XmlElement("contact")]
        [JsonPropertyName("contact")]
        public ContactInfo? Contact { get; set; }

        /// <summary>/// External documentation resources./// @usage/// Rationale:/// - More discoverable than single URL/// - Categorized by type (reference, guide, tutorial, video)/// - Descriptions help users find relevant docs/// EXAMPLES:/// - { url: "https://docs.example.com/api", description: "API Reference", type: "reference" }/// - { url: "https://docs.example.com/guide", description: "User Guide", type: "guide" }/// - { url: "https://youtube.com/watch?v=...", description: "Tutorial Video", type: "video" }/// </summary>
        [XmlElement("external-docs")]
        [JsonPropertyName("externalDocs")]
        public List<ExternalDocLink> ExternalDocs { get; set; }

        /// <summary>/// Supported input content types./// ALIGNED WITH: AIContent union type discriminators/// A2A INSPIRED BY: Agent Card "defaultInputModes" (but using our content types)/// EXAMPLES:/// - ["text"] - Text-only agent/// - ["text", "image", "audio"] - Multi-modal agent/// - ["text", "image", "video", "file"] - Rich media agent/// REFERENCE: See AIContent union in messages.tsp for all content types:/// text, image, audio, video, file, data, uri, adaptiveCard, etc./// </summary>
        [XmlArray("input-modes"), XmlArrayItem("string")]
        [JsonPropertyName("inputModes")]
        public List<string> InputModes { get; set; }

        /// <summary>/// Supported output content types./// ALIGNED WITH: AIContent union type discriminators/// A2A INSPIRED BY: Agent Card "defaultOutputModes" (but using our content types)/// EXAMPLES:/// - ["text"] - Text-only responses/// - ["text", "image"] - Can generate images/// - ["text", "audio", "video"] - Multi-modal outputs/// - ["text", "adaptiveCard", "suggestedActions"] - Rich UX responses/// REFERENCE: See AIContent union in messages.tsp for all content types/// </summary>
        [XmlArray("output-modes"), XmlArrayItem("string")]
        [JsonPropertyName("outputModes")]
        public List<string> OutputModes { get; set; }

        /// <summary>/// Required connections for this agent./// ALIGNED WITH: Connection union (common.tsp)/// RATIONALE: Uses existing TypeSpec Connection pattern instead of A2A's securitySchemes/// EXAMPLES:/// - Reference connection to pre-configured service/// - API key connection for external API/// - Remote connection with endpoint and credentials/// - Anonymous connection (no auth required)/// USAGE: Agent declares what connections it needs; runtime validates access/// </summary>
        [XmlArray("connections"), XmlArrayItem("connection")]
        [JsonPropertyName("connections")]
        public List<Connection> Connections { get; set; }

        /// <summary>/// Tags for discovery and filtering./// A2A INSPIRED: Similar to skill tags/// EXAMPLES: ["productivity", "calendar", "scheduling", "teams"]/// </summary>
        [XmlArray("tags"), XmlArrayItem("string")]
        [JsonPropertyName("tags")]
        public List<string> Tags { get; set; }

        /// <summary>/// M365/Entra Blueprint ID./// ADDITION: M365-specific/// PURPOSE: Links to Copilot Studio/M365 Agent Blueprint/// EXAMPLE: "blueprint-abc123"/// </summary>
        [XmlElement("blueprint-id")]
        [JsonPropertyName("blueprintId")]
        public string BlueprintId { get; set; }

        /// <summary>/// M365/Entra Agent User ID./// ADDITION: M365-specific/// PURPOSE: Entra ID Object ID for the agent's service principal/managed identity/// EXAMPLE: "87654321-4321-4321-4321-210987654321"/// USAGE: For agent-to-agent auth, permission grants, audit trails/// NOTE: Different from agentId (Application/Client ID) - this is the Object ID/// </summary>
        [XmlElement("agent-user-id")]
        [JsonPropertyName("agentUserId")]
        public string AgentUserId { get; set; }

        /// <summary>/// OAuth2 scopes this agent requires./// @usage/// Rationale:/// - Scopes communicate what the agent can do/// - Follows OpenAPI 3.0 OAuth2 security scheme format/// - Fully-qualified URIs prevent scope name collisions/// - Descriptions aid consent UI and documentation/// - Simpler than advertising individual tools/// EXAMPLES:/// - { "https://graph.microsoft.com/Calendars.Read": "Read user calendar events" }/// - { "https://graph.microsoft.com/Mail.Send": "Send mail as the signed-in user" }/// - { "https://graph.microsoft.com/User.Read.All": "Read all users' profiles" }/// - { "read:pets": "Read pet information", "write:pets": "Modify pet information" }/// </summary>
        [XmlElement("scopes")]
        [JsonPropertyName("scopes")]
        public Dictionary<string, object> Scopes { get; set; }

        /// <summary>/// Model capabilities (computed from agent's model configuration)./// @usage/// - Enables clients to validate requests before sending/// - Allows programmatic feature discovery/// - Supports intelligent model selection/// Rationale:/// - Capabilities are part of agent discovery, not a separate endpoint/// - Computed from AgentModel when AgentCard is retrieved/// - Single source of truth for what the agent can do/// EXAMPLES:/// - gpt-4o agent: vision=true, thinking=false, maxTokens=128000/// - claude-3-sonnet agent: vision=true, thinking=true, maxTokens=200000/// - gpt-3.5-turbo agent: vision=false, thinking=false, maxTokens=16385/// </summary>
        [XmlElement("capabilities")]
        [JsonPropertyName("capabilities")]
        public ModelCapabilities? Capabilities { get; set; }

        /// <summary>/// Custom metadata./// </summary>
        [XmlElement("metadata")]
        [JsonPropertyName("metadata")]
        public Dictionary<string, object> Metadata { get; set; }

        /// <summary>/// Timestamp when agent was registered./// </summary>
        [XmlElement("created-at")]
        [JsonPropertyName("createdAt")]
        public DateTime? CreatedAt { get; set; }

        /// <summary>/// Timestamp of last update to agent card./// </summary>
        [XmlElement("updated-at")]
        [JsonPropertyName("updatedAt")]
        public DateTime? UpdatedAt { get; set; }
    }
}