// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:27:44Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Agent message./// </summary>
    [XmlRoot("agent")]
    public partial class AgentMessage : ChatMessage
    {
        [JsonIgnore]
#pragma warning disable CS1591
        public override ChatRole Role => ChatRole.Agent;
#pragma warning restore CS1591
        /// <summary>/// Gets or sets the agent-id./// </summary>
        [XmlAttribute("agent-id")]
        public new string? AgentId { get; set; }

        /// <summary>/// Gets or sets the completion-id./// </summary>
        [XmlAttribute("completion-id")]
        public new string? CompletionId { get; set; }

        /// <summary>/// Gets or sets the completed-at./// </summary>
        [XmlAttribute("completed-at")]
        public new DateTime CompletedAt { get; set; }
        [XmlIgnore]
        public new bool CompletedAtSpecified { get; set; }

        /// <summary>/// Gets or sets the content items for this agent message./// </summary>
        [XmlElement("text", Type = typeof(TextContent)), XmlElement("thinking", Type = typeof(TextReasoningContent)), XmlElement("function-call", Type = typeof(FunctionCallContent)), XmlElement("image", Type = typeof(ImageContent)), XmlElement("adaptive-card", Type = typeof(AdaptiveCardContent)), XmlElement("user-input-request", Type = typeof(UserInputRequestContent)), XmlElement("suggested-actions", Type = typeof(SuggestedActionsContent)), XmlElement("document", Type = typeof(DocumentContent))]
        public new List<AIContent> Contents { get; set; } = new List<AIContent>();
    }
}
// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:27:44Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

