// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:27:44Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// AI Annotation/// BASE: Microsoft.Extensions.AI.AIAnnotation (base class for annotations)/// SOURCE: /extensions/src/Libraries/Microsoft.Extensions.AI.Abstractions/Contents/AIAnnotation.cs/// REPRESENTS: Metadata attached to content (e.g., citations)/// </summary>
    public partial class AIAnnotation
    {
        /// <summary>/// Gets or sets the type./// </summary>
        [XmlElement("type")]
        [JsonPropertyName("type")]
        public string Type { get; set; }

        /// <summary>/// Gets or sets the data./// </summary>
        [XmlElement("data")]
        [JsonPropertyName("data")]
        public Dictionary<string, object> Data { get; set; }
    }
}