// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:15:44Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Represents a a-i-tool./// </summary>
    public partial class AITool
    {
        /// <summary>/// Tool name (unique identifier)./// BASE: MAF AITool.Name (virtual, defaults to GetType().Name)/// EXAMPLES: "search_memory", "send_email", "get_calendar", "web_search"/// </summary>
        [XmlElement("name")]
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>/// Tool description for LLM./// BASE: MAF AITool.Description (virtual, defaults to empty string)/// IMPORTANT: This is shown to the LLM to decide when to call the tool/// GUIDANCE: Be specific about:/// - What the tool does/// - When to use it/// - What parameters it expects/// EXAMPLE: "Search the agent's long-term memory for relevant information/// from previous conversations. Use this when the user asks about past/// interactions or stored preferences."/// </summary>
        [XmlElement("description")]
        [JsonPropertyName("description")]
        public string Description { get; set; }

        /// <summary>/// Tool parameters (JSON Schema)./// FROM: Azure Agent API (FunctionTool.parameters)/// RATIONALE: JSON Schema is universal standard for describing parameters/// - Used by OpenAI, Anthropic, Azure, etc./// - Enables validation and IDE autocomplete/// MESSAGING APP PATTERN:/// Like command syntax: /command &lt;required&gt; [optional]/// </summary>
        [XmlElement("parameters")]
        [JsonPropertyName("parameters")]
        public JSONSchema? Parameters { get; set; }

        /// <summary>/// Strict schema validation (OpenAI-specific)./// FROM: OpenAI structured outputs/// When true, enforces exact schema adherence (no additional properties)/// </summary>
        [XmlElement("strict")]
        [JsonPropertyName("strict")]
        public bool? Strict { get; set; }

        /// <summary>/// Execution endpoint for remote tools./// @usage/// Rationale:/// - Local tools: endpoint is omitted (executed in-process)/// - Remote tools: endpoint specifies URL (like MCP server, webhooks, APIs)/// - No need for separate MCPTool type - just a tool with an endpoint/// EXAMPLES:/// - "https://mcp-server.example.com/tools/search" (MCP)/// - "https://api.example.com/webhooks/action" (Webhook)/// - null (local execution)/// </summary>
        [XmlElement("endpoint")]
        [JsonPropertyName("endpoint")]
        public string Endpoint { get; set; }

        /// <summary>/// Authentication for remote endpoint./// FROM: MCP pattern + A2A Protocol/// ALIGNED WITH: Agent Schema Tool.connection/// RATIONALE: Remote tools need authentication/// </summary>
        [XmlElement("connection")]
        [JsonPropertyName("connection")]
        public Connection? Connection { get; set; }

        /// <summary>/// OAuth2 scopes required for this tool./// @usage/// Rationale:/// - Fine-grained permissions per tool (vs agent-wide scopes)/// - Runtime can validate if agent has required scopes before tool execution/// - Enables dynamic consent flows (request scopes only when tool is used)/// - Follows OpenAPI 3.0 OAuth2 security scheme format/// EXAMPLES:/// - { "https://graph.microsoft.com/Calendars.ReadWrite": "Read and write calendar events" }/// - { "https://graph.microsoft.com/Mail.Send": "Send mail as the signed-in user" }/// - { "read:pets": "Read pet information", "write:pets": "Modify pet information" }/// </summary>
        [XmlElement("scopes")]
        [JsonPropertyName("scopes")]
        public Dictionary<string, object> Scopes { get; set; }

        /// <summary>/// Lifecycle hooks for this tool./// @usage/// Rationale:/// - Some tools need lifecycle hooks (before_execute, after_execute, on_error)/// - Enables guardrails, memory persistence, audit logging/// - Generic pattern vs separate GuardrailTool/MemoryTool types/// EXAMPLES:/// - Guardrails: before_execute validates parameters, after_execute validates output/// - Memory: after_execute persists result to journal/// - Audit: before_execute logs invocation/// </summary>
        [XmlElement("lifecycle-hooks")]
        [JsonPropertyName("lifecycleHooks")]
        public ToolLifecycleHooks? LifecycleHooks { get; set; }

        /// <summary>/// Requires user approval before execution (HITL)./// FROM: AG-UI pattern/// RATIONALE: Sensitive operations need human-in-the-loop approval/// M365: Critical for operations like:/// - Sending emails/// - Deleting files/// - Making purchases/// - Modifying permissions/// </summary>
        [XmlElement("requires-approval")]
        [JsonPropertyName("requiresApproval")]
        public bool? RequiresApproval { get; set; }

        /// <summary>/// Additional properties./// BASE: MAF AITool.AdditionalProperties (IReadOnlyDictionary&lt;string, object?&gt;)/// FLEXIBLE: Store tool-specific metadata/// EXAMPLES:/// - { "category": "productivity", "icon": "calendar" }/// - { "rateLimit": 10, "rateLimitPeriod": "1m" }/// - { "journalThreadId": "thread-123" } (for recall tool)/// </summary>
        [XmlElement("metadata")]
        [JsonPropertyName("metadata")]
        public Dictionary<string, object> Metadata { get; set; }
    }
}