// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:27:49Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Anonymous Connection/// ALIGNED WITH: Agent Schema AnonymousConnection/// SOURCE: https://github.com/microsoft/AgentSchema (agentschema/model/connection.tsp)/// RATIONALE: No authentication required (public endpoints)/// </summary>
    public partial class AnonymousConnection : Connection
    {
        /// <summary>/// Connection type discriminator./// ALIGNED WITH: Agent Schema Connection.kind/// </summary>
        [XmlElement("kind")]
        [JsonPropertyName("kind")]
        public override string Kind { get; }

        /// <summary>/// Usage transparency description./// ALIGNED WITH: Agent Schema Connection.usageDescription/// </summary>
        [XmlElement("usage-description")]
        [JsonPropertyName("usageDescription")]
        public string UsageDescription { get; set; }
    }
}