// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:18:40Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Cancel Action/// @usage/// Use Cases:/// - interrupt: User stops generation, wants to see partial output/// - rollback: Clean up failed/unwanted run completely (like "undo")/// </summary>
    public enum CancelAction
    {
        Interrupt,
        Rollback
    }
}