// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:27:44Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Channel message./// </summary>
    [XmlRoot("channel")]
    public partial class ChannelMessage : ChatMessage
    {
        [JsonIgnore]
#pragma warning disable CS1591
        public override ChatRole Role => ChatRole.Channel;
#pragma warning restore CS1591
        /// <summary>/// Gets or sets the content items for this channel message./// </summary>
        [XmlElement("event", Type = typeof(EventContent)), XmlElement("trace", Type = typeof(TraceContent)), XmlElement("action", Type = typeof(ActionContent))]
        public new List<AIContent> Contents { get; set; } = new List<AIContent>();
    }
}
// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:27:44Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

