// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:18:40Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Represents a chat-history-provider-config./// </summary>
    public partial class ChatHistoryProviderConfig
    {
        /// <summary>/// Connection configuration (for database/service providers)./// ALIGNED WITH: Agent Schema Connection system/// </summary>
        [XmlElement("connection")]
        [JsonPropertyName("connection")]
        public Connection? Connection { get; set; }

        /// <summary>/// History retrieval options./// </summary>
        [XmlElement("retrieval-options")]
        [JsonPropertyName("retrievalOptions")]
        public HistoryRetrievalOptions? RetrievalOptions { get; set; }

        /// <summary>/// Custom provider configuration./// </summary>
        [XmlElement("config")]
        [JsonPropertyName("config")]
        public Dictionary<string, object> Config { get; set; }
    }
}