// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:15:42Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Content Filter Result Content/// FROM: Azure Agent API (ContentFilterResultContent)/// ADDITION: Not in MAF/// RATIONALE: Azure content moderation results/// M365: Compliance and audit requirements/// XML: &lt;content-filter-result filtered="true" category="hate" severity="medium" /&gt;/// </summary>
    [XmlRoot("filter-result")]
    public partial class ContentFilterResultContent : AIContentBase
    {
        [JsonIgnore]
#pragma warning disable CS1591, CS1587
        public override string Kind => "contentFilterResult";
#pragma warning restore CS1591, CS1587
        /// <summary>/// Gets or sets the filtered./// </summary>
        [XmlAttribute("filtered")]
        [JsonPropertyName("filtered")]
        public bool Filtered { get; set; }

        /// <summary>/// Gets or sets the category./// </summary>
        [XmlAttribute("category")]
        [JsonPropertyName("category")]
        public string Category { get; set; }

        /// <summary>/// Gets or sets the severity./// </summary>
        [XmlAttribute("severity")]
        [JsonPropertyName("severity")]
        public string Severity { get; set; }
    }
}