// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:18:44Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Cost Estimation/// ADDITION: Not in any framework/// RATIONALE: Enables cost estimation and quota enforcement/// M365: Critical for cost management and budgeting/// </summary>
    public partial class CostEstimation
    {
        /// <summary>/// Gets or sets the input-cost./// </summary>
        [XmlElement("input-cost")]
        [JsonPropertyName("inputCost")]
        public double InputCost { get; set; }

        /// <summary>/// Gets or sets the output-cost./// </summary>
        [XmlElement("output-cost")]
        [JsonPropertyName("outputCost")]
        public double OutputCost { get; set; }

        /// <summary>/// Gets or sets the cached-cost./// </summary>
        [XmlElement("cached-cost")]
        [JsonPropertyName("cachedCost")]
        public double? CachedCost { get; set; }

        /// <summary>/// Gets or sets the reasoning-cost./// </summary>
        [XmlElement("reasoning-cost")]
        [JsonPropertyName("reasoningCost")]
        public double? ReasoningCost { get; set; }

        /// <summary>/// Gets or sets the total-cost./// </summary>
        [XmlElement("total-cost")]
        [JsonPropertyName("totalCost")]
        public double TotalCost { get; set; }

        /// <summary>/// Gets or sets the currency./// </summary>
        [XmlElement("currency")]
        [JsonPropertyName("currency")]
        public string Currency { get; set; }

        /// <summary>/// Gets or sets the pricing-model./// </summary>
        [XmlElement("pricing-model")]
        [JsonPropertyName("pricingModel")]
        public string PricingModel { get; set; }

        /// <summary>/// Gets or sets the calculated-at./// </summary>
        [XmlElement("calculated-at")]
        [JsonPropertyName("calculatedAt")]
        public DateTime CalculatedAt { get; set; }
    }
}