// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:15:42Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Data Content/// BASE: Microsoft.Extensions.AI.DataContent/// SOURCE: /extensions/src/Libraries/Microsoft.Extensions.AI.Abstractions/Contents/DataContent.cs/// REPRESENTS: Arbitrary structured data/// XML: &lt;data uri="..." mime-type="..."&gt;base64data&lt;/data&gt;/// </summary>
    [XmlRoot("data")]
    public partial class DataContent : AIContentBase
    {
        [JsonIgnore]
#pragma warning disable CS1591, CS1587
        public override string Kind => "data";
#pragma warning restore CS1591, CS1587
        /// <summary>/// Gets or sets the uri./// </summary>
        [XmlAttribute("uri")]
        [JsonPropertyName("uri")]
        public string Uri { get; set; }

        /// <summary>/// Gets or sets the mime-type./// </summary>
        [XmlAttribute("mime-type")]
        [JsonPropertyName("mimeType")]
        public string MimeType { get; set; }

        /// <summary>/// Gets or sets the value./// </summary>
        [XmlText]
        [JsonPropertyName("value")]
        public string Value { get; set; }
    }
}