// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:18:38Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// XML: &lt;document title="..." document-id="..." source="..." mime-type="..."&gt;&lt;content&gt;...&lt;/content&gt;&lt;/document&gt;/// </summary>
    [XmlRoot("document")]
    public partial class DocumentContent : AIContentBase
    {
        [JsonIgnore]
#pragma warning disable CS1591, CS1587
        public override string Kind => "document";
#pragma warning restore CS1591, CS1587
        /// <summary>/// Gets or sets the title./// </summary>
        [XmlAttribute("title")]
        [JsonPropertyName("title")]
        public string Title { get; set; }

        /// <summary>/// Gets or sets the document-id./// </summary>
        [XmlAttribute("document-id")]
        [JsonPropertyName("documentId")]
        public string DocumentId { get; set; }

        /// <summary>/// Gets or sets the source./// </summary>
        [XmlAttribute("source")]
        [JsonPropertyName("source")]
        public string Source { get; set; }

        /// <summary>/// Gets or sets the mime-type./// </summary>
        [XmlAttribute("mime-type")]
        [JsonPropertyName("mimeType")]
        public string MimeType { get; set; }

        /// <summary>/// Gets or sets the content./// </summary>
        [XmlElement("content")]
        [JsonPropertyName("content")]
        public string Content { get; set; }
    }
}