// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:15:48Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Evaluation Result/// Complete result from running evaluation thread./// </summary>
    public partial class EvalResult
    {
        /// <summary>/// Gets or sets the thread-id./// </summary>
        [XmlElement("thread-id")]
        [JsonPropertyName("threadId")]
        public string ThreadId { get; set; }

        /// <summary>/// Gets or sets the description./// </summary>
        [XmlElement("description")]
        [JsonPropertyName("description")]
        public string Description { get; set; }

        /// <summary>/// Gets or sets the passed./// </summary>
        [XmlElement("passed")]
        [JsonPropertyName("passed")]
        public bool Passed { get; set; }

        /// <summary>/// Gets or sets the runs./// </summary>
        [XmlArray("runs"), XmlArrayItem("eval-run-result")]
        [JsonPropertyName("runs")]
        public List<EvalRunResult> Runs { get; set; }

        /// <summary>/// Gets or sets the total-runs./// </summary>
        [XmlElement("total-runs")]
        [JsonPropertyName("totalRuns")]
        public int TotalRuns { get; set; }

        /// <summary>/// Gets or sets the passed-runs./// </summary>
        [XmlElement("passed-runs")]
        [JsonPropertyName("passedRuns")]
        public int PassedRuns { get; set; }

        /// <summary>/// Gets or sets the failed-runs./// </summary>
        [XmlElement("failed-runs")]
        [JsonPropertyName("failedRuns")]
        public int FailedRuns { get; set; }

        /// <summary>/// Gets or sets the total-asserts./// </summary>
        [XmlElement("total-asserts")]
        [JsonPropertyName("totalAsserts")]
        public int TotalAsserts { get; set; }

        /// <summary>/// Gets or sets the passed-asserts./// </summary>
        [XmlElement("passed-asserts")]
        [JsonPropertyName("passedAsserts")]
        public int PassedAsserts { get; set; }

        /// <summary>/// Gets or sets the failed-asserts./// </summary>
        [XmlElement("failed-asserts")]
        [JsonPropertyName("failedAsserts")]
        public int FailedAsserts { get; set; }

        /// <summary>/// Gets or sets the avg-duration-ms./// </summary>
        [XmlElement("avg-duration-ms")]
        [JsonPropertyName("avgDurationMs")]
        public float AvgDurationMs { get; set; }

        /// <summary>/// Gets or sets the timestamp./// </summary>
        [XmlElement("timestamp")]
        [JsonPropertyName("timestamp")]
        public DateTime Timestamp { get; set; }

        /// <summary>/// Gets or sets the total-duration-ms./// </summary>
        [XmlElement("total-duration-ms")]
        [JsonPropertyName("totalDurationMs")]
        public int TotalDurationMs { get; set; }
    }
}