// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:18:45Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Evaluation Run Result/// Result from a single run of the evaluation./// </summary>
    public partial class EvalRunResult
    {
        /// <summary>/// Gets or sets the run-number./// </summary>
        [XmlElement("run-number")]
        [JsonPropertyName("runNumber")]
        public int RunNumber { get; set; }

        /// <summary>/// Gets or sets the passed./// </summary>
        [XmlElement("passed")]
        [JsonPropertyName("passed")]
        public bool Passed { get; set; }

        /// <summary>/// Gets or sets the expects./// </summary>
        [XmlArray("expects"), XmlArrayItem("expect-result")]
        [JsonPropertyName("expects")]
        public List<ExpectResult> Expects { get; set; }

        /// <summary>/// Gets or sets the review./// </summary>
        [XmlElement("review")]
        [JsonPropertyName("review")]
        public ReviewResult? Review { get; set; }

        /// <summary>/// Gets or sets the duration-ms./// </summary>
        [XmlElement("duration-ms")]
        [JsonPropertyName("durationMs")]
        public int DurationMs { get; set; }

        /// <summary>/// Gets or sets the error./// </summary>
        [XmlElement("error")]
        [JsonPropertyName("error")]
        public string Error { get; set; }
    }
}