// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:27:51Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Represents a eval-run./// </summary>
    [XmlType("run")]
    public partial class EvalRun : ThreadElement
    {
        /// <summary>/// Maximum steps before stopping./// Prevents infinite loops./// RATIONALE: Safety limit for agent execution/// DEFAULT: 10/// TYPICAL: 10-20 for most tasks/// </summary>
        [XmlAttribute("maxSteps")]
        [JsonPropertyName("maxSteps")]
        public int? MaxSteps { get; set; }

        /// <summary>/// Timeout in milliseconds./// Stops execution if time limit exceeded./// RATIONALE: Prevent hanging on external dependencies/// TYPICAL: 30000 (30 seconds)/// </summary>
        [XmlAttribute("timeoutMs")]
        [JsonPropertyName("timeoutMs")]
        public int? TimeoutMs { get; set; }

        public bool ShouldSerializeMaxSteps() => MaxSteps.HasValue;
        public bool ShouldSerializeTimeoutMs() => TimeoutMs.HasValue;
    }
}