// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:27:51Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Represents a eval-thread./// </summary>
    [XmlRoot("thread")]
    public partial class EvalThread : ThreadBase
    {
        /// <summary>/// Evaluation description./// Describes what this test validates./// </summary>
        [XmlAttribute("desc")]
        [JsonPropertyName("description")]
        public string Description { get; set; }

        /// <summary>/// Number of times to repeat this evaluation./// Used for flaky test tolerance with per-assertion pass rate thresholds./// </summary>
        [XmlAttribute("repeat")]
        [JsonPropertyName("repeat")]
        public int? Repeat { get; set; }

        /// <summary>/// Ordered thread content./// Heterogeneous array of messages and eval blocks in execution order./// CONTAINS: ChatMessage (user, agent, tool) + Expect + EvalRun + Review/// XML: All elements are direct children of &lt;thread&gt; in document order/// </summary>
        [XmlArray("elements"), XmlArrayItem("thread-element")]
        [JsonPropertyName("elements")]
        public List<ThreadElement> Elements { get; set; }

        public bool ShouldSerializeRepeat() => Repeat.HasValue;
    }
}