// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:18:45Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Represents a expect./// </summary>
    [XmlType("expect")]
    public partial class Expect : ThreadElement
    {
        /// <summary>/// Optional name for this expectation./// Used in error messages and reports./// RATIONALE: Makes test failures easier to diagnose/// EXAMPLE: "correct_answer", "calls_weather_tool", "final_response"/// </summary>
        [XmlAttribute("name")]
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>/// Reference output for comparison./// Expected agent response used by judges./// REQUIRED: All expectations must specify expected behavior/// - Comparison judges (text_exact_match, semantic_similarity) use it for matching/// - Other judges (text_contains, tool_call_match) receive it but may ignore it/// USAGE: Passed to all judges/// - Provides expected behavior documentation/// - Used by comparison judges for evaluation/// - May be checked by tooling/linters/// RATIONALE: Makes test intent explicit and readable/// </summary>
        [XmlElement("reference-output")]
        [JsonPropertyName("referenceOutput")]
        public ChatMessage ReferenceOutput { get; set; }

        /// <summary>/// Judges to evaluate output./// Each judge produces a result stored in a variable./// EXECUTION: All judges run in parallel/// RESULTS: Stored in variables (judge.as) for use in assertions/// </summary>
        [XmlArray("judges"), XmlArrayItem("judge")]
        [JsonPropertyName("judges")]
        public List<Judge> Judges { get; set; }

        /// <summary>/// Assertions using CEL expressions./// Must all evaluate to true for expect block to pass./// EXECUTION: Evaluated after all judges complete/// VARIABLES AVAILABLE:/// - Judge results: {judge.as}.passed, {judge.as}.score, etc./// - Thread context: messages, user, agent, etc./// </summary>
        [XmlArray("asserts"), XmlArrayItem("assert")]
        [JsonPropertyName("asserts")]
        public List<Assert> Asserts { get; set; }
    }
}