// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:27:51Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Expect Result/// Result from evaluating an expect block./// </summary>
    public partial class ExpectResult
    {
        /// <summary>/// Gets or sets the name./// </summary>
        [XmlElement("name")]
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>/// Gets or sets the passed./// </summary>
        [XmlElement("passed")]
        [JsonPropertyName("passed")]
        public bool Passed { get; set; }

        /// <summary>/// Gets or sets the judges./// </summary>
        [XmlArray("judges"), XmlArrayItem("judge-result")]
        [JsonPropertyName("judges")]
        public List<JudgeResult> Judges { get; set; }

        /// <summary>/// Gets or sets the asserts./// </summary>
        [XmlArray("asserts"), XmlArrayItem("assert-result")]
        [JsonPropertyName("asserts")]
        public List<AssertResult> Asserts { get; set; }
    }
}