// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:27:50Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Expression Condition/// RATIONALE: In-process evaluation using Power Fx or CEL/// </summary>
    public partial class ExpressionCondition : RunCondition
    {
        /// <summary>/// Condition type discriminator./// </summary>
        [XmlElement("kind")]
        [JsonPropertyName("kind")]
        public override string Kind { get; }

        /// <summary>/// Expression for in-process evaluation./// @usage/// Use Cases:/// - Keyword matching and pattern detection/// - Content type and role combinations/// - Simple boolean logic without external state/// </summary>
        [XmlElement("expression")]
        [JsonPropertyName("expression")]
        public string Expression { get; set; }
    }
}