// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:27:47Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// External Documentation Link/// </summary>
    public partial class ExternalDocLink
    {
        /// <summary>/// Gets or sets the url./// </summary>
        [XmlElement("url")]
        [JsonPropertyName("url")]
        public string Url { get; set; }

        /// <summary>/// Gets or sets the description./// </summary>
        [XmlElement("description")]
        [JsonPropertyName("description")]
        public string Description { get; set; }
    }
}