// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:27:44Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// XML: &lt;file uri="..." filename="..." mime-type="..." size-bytes="1024" /&gt;/// </summary>
    [XmlRoot("file")]
    public partial class FileContent : AIContentBase
    {
        [JsonIgnore]
#pragma warning disable CS1591, CS1587
        public override string Kind => "file";
#pragma warning restore CS1591, CS1587
        /// <summary>/// Gets or sets the uri./// </summary>
        [XmlAttribute("uri")]
        [JsonPropertyName("uri")]
        public string Uri { get; set; }

        /// <summary>/// Gets or sets the filename./// </summary>
        [XmlAttribute("filename")]
        [JsonPropertyName("filename")]
        public string Filename { get; set; }

        /// <summary>/// Gets or sets the mime-type./// </summary>
        [XmlAttribute("mime-type")]
        [JsonPropertyName("mimeType")]
        public string MimeType { get; set; }

        /// <summary>/// Gets or sets the size-bytes./// </summary>
        [XmlAttribute("size-bytes")]
        [JsonPropertyName("sizeBytes")]
        public long SizeBytes { get; set; }
    }
}