// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:18:38Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Function Result Content/// BASE: Microsoft.Extensions.AI.FunctionResultContent/// SOURCE: /extensions/src/Libraries/Microsoft.Extensions.AI.Abstractions/Contents/FunctionResultContent.cs/// REPRESENTS: Result of tool execution/// XML: &lt;function-result call-id="..." name="..."&gt;{"result": "value"}&lt;/function-result&gt;/// </summary>
    [XmlRoot("function-result")]
    public partial class FunctionResultContent : AIContentBase
    {
        [JsonIgnore]
#pragma warning disable CS1591, CS1587
        public override string Kind => "functionResult";
#pragma warning restore CS1591, CS1587
        /// <summary>/// Gets or sets the call-id./// </summary>
        [XmlAttribute("call-id")]
        [JsonPropertyName("callId")]
        public string CallId { get; set; }

        /// <summary>/// Gets or sets the name./// </summary>
        [XmlAttribute("name")]
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>/// Gets or sets the result./// </summary>
        [XmlText]
        [JsonPropertyName("result")]
        public string Result { get; set; }
    }
}