// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:15:42Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Function Call Content/// BASE: Microsoft.Extensions.AI.FunctionCallContent/// SOURCE: /extensions/src/Libraries/Microsoft.Extensions.AI.Abstractions/Contents/FunctionCallContent.cs/// REPRESENTS: Agent's request to execute a tool/// XML: &lt;function-call call-id="..." name="..."&gt;{"arg": "value"}&lt;/function-call&gt;/// </summary>
    [XmlRoot("function-call")]
    public partial class FunctionCallContent : AIContentBase
    {
        [JsonIgnore]
#pragma warning disable CS1591, CS1587
        public override string Kind => "functionCall";
#pragma warning restore CS1591, CS1587
        /// <summary>/// Gets or sets the call-id./// </summary>
        [XmlAttribute("call-id")]
        [JsonPropertyName("callId")]
        public string CallId { get; set; }

        /// <summary>/// Gets or sets the name./// </summary>
        [XmlAttribute("name")]
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>/// Gets or sets the arguments./// </summary>
        [XmlText]
        [JsonPropertyName("arguments")]
        public string Arguments { get; set; }
    }
}