// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:18:40Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// History Retrieval Options/// FROM: MAF ChatHistoryProvider filters/// SOURCE: /agent-framework/dotnet/src/Microsoft.Agents.AI.Abstractions/ChatHistoryProvider.cs/// REPRESENTS: Filters applied when retrieving conversation history/// MAF PATTERN: Filter chain to control which history is included/// </summary>
    public partial class HistoryRetrievalOptions
    {
        /// <summary>/// Maximum messages to retrieve./// MAF: Message count filter/// </summary>
        [XmlElement("max-messages")]
        [JsonPropertyName("maxMessages")]
        public int? MaxMessages { get; set; }

        /// <summary>/// Maximum tokens to include (context window management)./// MAF: Token budget filter/// </summary>
        [XmlElement("max-tokens")]
        [JsonPropertyName("maxTokens")]
        public int? MaxTokens { get; set; }

        /// <summary>/// Time range filter./// MAF: Time-based filter/// </summary>
        [XmlElement("start")]
        [JsonPropertyName("start")]
        public DateTime? Start { get; set; }

        /// <summary>/// Gets or sets the end./// </summary>
        [XmlElement("end")]
        [JsonPropertyName("end")]
        public DateTime? End { get; set; }

        /// <summary>/// Filter by message roles./// EXAMPLES: Only include user/assistant messages, exclude system/// </summary>
        [XmlArray("include-roles"), XmlArrayItem("chat-role")]
        [JsonPropertyName("includeRoles")]
        public List<ChatRole> IncludeRoles { get; set; }

        /// <summary>/// Filter by message roles to exclude./// </summary>
        [XmlArray("exclude-roles"), XmlArrayItem("chat-role")]
        [JsonPropertyName("excludeRoles")]
        public List<ChatRole> ExcludeRoles { get; set; }
    }
}