// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:18:38Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Represents hosted-vector-store-content content./// </summary>
    [XmlRoot("hosted-vector-store")]
    public partial class HostedVectorStoreContent : AIContentBase
    {
        [JsonIgnore]
#pragma warning disable CS1591, CS1587
        public override string Kind => "hostedVectorStore";
#pragma warning restore CS1591, CS1587
        /// <summary>/// Provider's vector store identifier./// EXAMPLES:/// - OpenAI: "vs_abc123"/// - Azure: "https://search.azure.com/indexes/my-index"/// </summary>
        [XmlAttribute("vector-store-id")]
        [JsonPropertyName("vectorStoreId")]
        public string VectorStoreId { get; set; }

        /// <summary>/// Vector store name (optional)./// </summary>
        [XmlAttribute("name")]
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>/// Number of vectors/documents in store (optional)./// </summary>
        [XmlAttribute("document-count")]
        [JsonPropertyName("documentCount")]
        public int DocumentCount { get; set; }
    }
}