// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:15:42Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Image Content/// FROM: Azure Agent API (ImageContent)/// ADDITION: Not in MAF/// Provides three delivery methods: uri, dataUri, or raw data bytes./// M365: Future multi-modal scenarios/// XML: &lt;image uri="..." mime-type="..." width="1920" height="1080" /&gt;/// </summary>
    [XmlRoot("image")]
    public partial class ImageContent : AIContentBase
    {
        [JsonIgnore]
#pragma warning disable CS1591, CS1587
        public override string Kind => "image";
#pragma warning restore CS1591, CS1587
        /// <summary>/// Gets or sets the uri./// </summary>
        [XmlAttribute("uri")]
        [JsonPropertyName("uri")]
        public string Uri { get; set; }

        /// <summary>/// Gets or sets the alt./// </summary>
        [XmlAttribute("alt")]
        [JsonPropertyName("alt")]
        public string Alt { get; set; }

        /// <summary>/// Gets or sets the mime-type./// </summary>
        [XmlAttribute("mime-type")]
        [JsonPropertyName("mimeType")]
        public string MimeType { get; set; }

        /// <summary>/// Gets or sets the width./// </summary>
        [XmlAttribute("width")]
        [JsonPropertyName("width")]
        public int Width { get; set; }

        /// <summary>/// Gets or sets the height./// </summary>
        [XmlAttribute("height")]
        [JsonPropertyName("height")]
        public int Height { get; set; }
    }
}