// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:15:44Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// JSON Schema/// FROM: Azure Agent API + JSON Schema Draft 7/// REPRESENTS: Parameter schema for tool validation/// UNIVERSAL STANDARD: Used by OpenAI, Anthropic, Azure, etc./// </summary>
    public partial class JSONSchema
    {
        /// <summary>/// Gets or sets the properties./// </summary>
        [XmlElement("properties")]
        [JsonPropertyName("properties")]
        public Dictionary<string, object> Properties { get; set; }

        /// <summary>/// Gets or sets the items./// </summary>
        [XmlElement("items")]
        [JsonPropertyName("items")]
        public JSONSchema? Items { get; set; }

        /// <summary>/// Gets or sets the required./// </summary>
        [XmlArray("required"), XmlArrayItem("string")]
        [JsonPropertyName("required")]
        public List<string> Required { get; set; }

        /// <summary>/// Gets or sets the description./// </summary>
        [XmlElement("description")]
        [JsonPropertyName("description")]
        public string Description { get; set; }

        /// <summary>/// Gets or sets the format./// </summary>
        [XmlElement("format")]
        [JsonPropertyName("format")]
        public string Format { get; set; }

        /// <summary>/// Gets or sets the minimum./// </summary>
        [XmlElement("minimum")]
        [JsonPropertyName("minimum")]
        public double? Minimum { get; set; }

        /// <summary>/// Gets or sets the maximum./// </summary>
        [XmlElement("maximum")]
        [JsonPropertyName("maximum")]
        public double? Maximum { get; set; }

        /// <summary>/// Gets or sets the min-items./// </summary>
        [XmlElement("min-items")]
        [JsonPropertyName("minItems")]
        public int? MinItems { get; set; }

        /// <summary>/// Gets or sets the max-items./// </summary>
        [XmlElement("max-items")]
        [JsonPropertyName("maxItems")]
        public int? MaxItems { get; set; }

        /// <summary>/// Gets or sets the pattern./// </summary>
        [XmlElement("pattern")]
        [JsonPropertyName("pattern")]
        public string Pattern { get; set; }
    }
}