// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:18:45Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Judge Result/// Result from judge evaluation./// </summary>
    public partial class JudgeResult
    {
        /// <summary>/// Gets or sets the agent./// </summary>
        [XmlElement("agent")]
        [JsonPropertyName("agent")]
        public string Agent { get; set; }

        /// <summary>/// Gets or sets the as./// </summary>
        [XmlElement("as")]
        [JsonPropertyName("as")]
        public string As { get; set; }

        /// <summary>/// Gets or sets the passed./// </summary>
        [XmlElement("passed")]
        [JsonPropertyName("passed")]
        public bool Passed { get; set; }

        /// <summary>/// Gets or sets the score./// </summary>
        [XmlElement("score")]
        [JsonPropertyName("score")]
        public float Score { get; set; }

        /// <summary>/// Gets or sets the details./// </summary>
        [XmlElement("details")]
        [JsonPropertyName("details")]
        public Dictionary<string, object> Details { get; set; }

        /// <summary>/// Gets or sets the error./// </summary>
        [XmlElement("error")]
        [JsonPropertyName("error")]
        public string Error { get; set; }
    }
}