// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:15:48Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Judge Scope/// Determines what content the judge evaluates./// SCOPES:/// - last: Last agent emission only (most common)/// - turn: Last agent emission + tool calls in that turn/// - thread: Full thread history (all messages)/// </summary>
    public enum JudgeScope
    {
        Last,
        Turn,
        Thread
    }
}