// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:27:46Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Lifecycle Hook/// ADDITION: Not in any framework (generic pattern)/// REPRESENTS: Executable hook in tool lifecycle/// PATTERN: Same as AITool - callable function with parameters/// </summary>
    public partial class LifecycleHook
    {
        /// <summary>/// Hook name (for debugging/logging)./// </summary>
        [XmlElement("name")]
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>/// Hook implementation endpoint./// - Local hooks: omitted (executed in-process)/// - Remote hooks: URL to hook implementation/// EXAMPLES:/// - null: In-process guardrail function/// - "https://guardrails.example.com/validate": Remote guardrail service/// </summary>
        [XmlElement("endpoint")]
        [JsonPropertyName("endpoint")]
        public string Endpoint { get; set; }

        /// <summary>/// Authentication for remote hook./// </summary>
        [XmlElement("connection")]
        [JsonPropertyName("connection")]
        public Connection? Connection { get; set; }

        /// <summary>/// Hook-specific configuration./// FLEXIBLE: Each hook can have its own config/// EXAMPLES:/// - { "maxTokens": 1000 } for output validator/// - { "journalThreadId": "thread-123" } for memory persistence/// - { "policyId": "policy-456" } for guardrail/// </summary>
        [XmlElement("config")]
        [JsonPropertyName("config")]
        public Dictionary<string, object> Config { get; set; }
    }
}