// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:15:48Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Lint Error/// Error from linting operation./// </summary>
    public partial class LintError
    {
        /// <summary>/// Gets or sets the message./// </summary>
        [XmlElement("message")]
        [JsonPropertyName("message")]
        public string Message { get; set; }

        /// <summary>/// Gets or sets the line./// </summary>
        [XmlElement("line")]
        [JsonPropertyName("line")]
        public int? Line { get; set; }

        /// <summary>/// Gets or sets the element./// </summary>
        [XmlElement("element")]
        [JsonPropertyName("element")]
        public string Element { get; set; }

        /// <summary>/// Gets or sets the fix./// </summary>
        [XmlElement("fix")]
        [JsonPropertyName("fix")]
        public string Fix { get; set; }
    }
}