// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:15:48Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Mention Condition (RunCondition-specific)/// RATIONALE: Agent participates when explicitly mentioned in message/// PATTERN: @agent-name or explicit agent reference/// NOTE: Only explicit mentions are supported. Context-relevance/// cannot be deterministically evaluated./// </summary>
    public partial class MentionCondition : RunCondition
    {
        /// <summary>/// Condition type discriminator./// </summary>
        [XmlElement("kind")]
        [JsonPropertyName("kind")]
        public override string Kind { get; }

        /// <summary>/// Respond when agent is explicitly mentioned in message./// DEFAULT: true (only respond to explicit @mentions)/// EXAMPLES:/// - true: Requires "@AgentName" in message/// - false: Any reference to agent name triggers participation/// </summary>
        [XmlElement("require-explicit-mention")]
        [JsonPropertyName("requireExplicitMention")]
        public bool? RequireExplicitMention { get; set; }
    }
}