// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:15:45Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// All message-related streaming events./// @usage/// Use to filter or handle all message events in a unified way./// Useful for webhook subscriptions and event processing./// @example Filter message events/// ```typescript/// if (event is MessageEvent) {/// // Handle message-related events/// }/// ```/// </summary>
    public abstract partial class MessageEvent
    {
    }
}