// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:18:42Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Message Filters/// @usage/// Filter webhook notifications by message characteristics./// Reduces notification volume by subscribing only to relevant messages./// @example Filter user messages only/// ```json/// {/// "roles": ["user"]/// }/// ```/// @example Filter messages with images or videos/// ```json/// {/// "contentTypes": ["image", "video"]/// }/// ```/// </summary>
    public partial class MessageFilters
    {
        /// <summary>/// Gets or sets the roles./// </summary>
        [XmlArray("roles"), XmlArrayItem("string")]
        [JsonPropertyName("roles")]
        public List<string> Roles { get; set; }

        /// <summary>/// Gets or sets the user-ids./// </summary>
        [XmlArray("user-ids"), XmlArrayItem("string")]
        [JsonPropertyName("userIds")]
        public List<string> UserIds { get; set; }

        /// <summary>/// Gets or sets the agent-ids./// </summary>
        [XmlArray("agent-ids"), XmlArrayItem("string")]
        [JsonPropertyName("agentIds")]
        public List<string> AgentIds { get; set; }

        /// <summary>/// Gets or sets the content-types./// </summary>
        [XmlArray("content-types"), XmlArrayItem("string")]
        [JsonPropertyName("contentTypes")]
        public List<string> ContentTypes { get; set; }

        /// <summary>/// Gets or sets the audience./// </summary>
        [XmlArray("audience"), XmlArrayItem("string")]
        [JsonPropertyName("audience")]
        public List<string> Audience { get; set; }
    }
}