// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:18:38Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Represents message-reaction-content content./// </summary>
    [XmlRoot("message-reaction")]
    public partial class MessageReactionContent : AIContentBase
    {
        [JsonIgnore]
#pragma warning disable CS1591, CS1587
        public override string Kind => "messageReaction";
#pragma warning restore CS1591, CS1587
        /// <summary>/// Gets or sets the referenced-message-id./// </summary>
        [XmlAttribute("referenced-message-id")]
        [JsonPropertyName("referencedMessageId")]
        public string ReferencedMessageId { get; set; }

        /// <summary>/// Gets or sets the reactions-added./// </summary>
        [XmlElement("added")]
        [JsonPropertyName("reactionsAdded")]
        public List<MessageReaction> ReactionsAdded { get; set; }

        /// <summary>/// Gets or sets the reactions-removed./// </summary>
        [XmlElement("removed")]
        [JsonPropertyName("reactionsRemoved")]
        public List<MessageReaction> ReactionsRemoved { get; set; }
    }
}