// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:27:44Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Message Reaction (Individual Reaction)/// </summary>
    [XmlType("removed")]
    public partial class MessageReaction
    {
        /// <summary>/// Gets or sets the type./// </summary>
        [XmlElement("type")]
        [JsonPropertyName("type")]
        public string Type { get; set; }

        /// <summary>/// Gets or sets the user-id./// </summary>
        [XmlElement("user-id")]
        [JsonPropertyName("userId")]
        public string UserId { get; set; }

        /// <summary>/// Gets or sets the timestamp./// </summary>
        [XmlElement("timestamp")]
        [JsonPropertyName("timestamp")]
        public DateTime? Timestamp { get; set; }
    }
}