// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:15:44Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Represents a model-options./// </summary>
    public partial class ModelOptions
    {
        /// <summary>/// Sampling temperature (0-2)./// ALIGNED WITH: Agent Schema ModelOptions.temperature/// GUIDANCE: 0 = deterministic, 1 = balanced, 2 = creative/// </summary>
        [XmlElement("temperature")]
        [JsonPropertyName("temperature")]
        public float? Temperature { get; set; }

        /// <summary>/// Top-P sampling (nucleus sampling, 0-1)./// ALIGNED WITH: Agent Schema ModelOptions.topP/// GUIDANCE: Probability mass threshold/// </summary>
        [XmlElement("top-p")]
        [JsonPropertyName("topP")]
        public float? TopP { get; set; }

        /// <summary>/// Top-K sampling./// ALIGNED WITH: Agent Schema ModelOptions.topK/// GUIDANCE: Consider top K tokens (Anthropic, Gemini)/// </summary>
        [XmlElement("top-k")]
        [JsonPropertyName("topK")]
        public int? TopK { get; set; }

        /// <summary>/// Maximum generation length (tokens)./// ALIGNED WITH: Agent Schema ModelOptions.maxOutputTokens/// NOTE: Replaces maxTokens (Anthropic) and maxOutputTokens (OpenAI)/// </summary>
        [XmlElement("max-output-tokens")]
        [JsonPropertyName("maxOutputTokens")]
        public int? MaxOutputTokens { get; set; }

        /// <summary>/// Frequency penalty (-2 to 2)./// ALIGNED WITH: Agent Schema ModelOptions.frequencyPenalty/// GUIDANCE: Penalizes token frequency (OpenAI, Azure)/// </summary>
        [XmlElement("frequency-penalty")]
        [JsonPropertyName("frequencyPenalty")]
        public float? FrequencyPenalty { get; set; }

        /// <summary>/// Presence penalty (-2 to 2)./// ALIGNED WITH: Agent Schema ModelOptions.presencePenalty/// GUIDANCE: Penalizes token presence (OpenAI, Azure)/// </summary>
        [XmlElement("presence-penalty")]
        [JsonPropertyName("presencePenalty")]
        public float? PresencePenalty { get; set; }

        /// <summary>/// Deterministic generation seed./// ALIGNED WITH: Agent Schema ModelOptions.seed/// GUIDANCE: Same seed + params = same output/// </summary>
        [XmlElement("seed")]
        [JsonPropertyName("seed")]
        public int? Seed { get; set; }

        /// <summary>/// Stop sequences./// ALIGNED WITH: Agent Schema ModelOptions.stopSequences/// NOTE: Unified name (was stop for OpenAI, stopSequences for Anthropic/Gemini)/// </summary>
        [XmlArray("stop-sequences"), XmlArrayItem("string")]
        [JsonPropertyName("stopSequences")]
        public List<string> StopSequences { get; set; }

        /// <summary>/// Enable parallel tool calling./// ALIGNED WITH: Agent Schema ModelOptions.allowMultipleToolCalls/// GUIDANCE: Multiple tools in single turn (OpenAI)/// </summary>
        [XmlElement("allow-multiple-tool-calls")]
        [JsonPropertyName("allowMultipleToolCalls")]
        public bool? AllowMultipleToolCalls { get; set; }
    }
}