// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:15:45Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Represents a participant-added-event./// </summary>
    public partial class ParticipantAddedEvent : ParticipantEvent
    {
        /// <summary>/// Gets or sets the thread-id./// </summary>
        [XmlElement("thread-id")]
        [JsonPropertyName("threadId")]
        public string ThreadId { get; set; }

        /// <summary>/// Gets or sets the event-seq./// </summary>
        [XmlElement("event-seq")]
        [JsonPropertyName("eventSeq")]
        public long EventSeq { get; set; }

        /// <summary>/// Gets or sets the participant./// </summary>
        [XmlElement("participant")]
        [JsonPropertyName("participant")]
        public Participant Participant { get; set; }

        /// <summary>/// Gets or sets the added-at./// </summary>
        [XmlElement("added-at")]
        [JsonPropertyName("addedAt")]
        public DateTime AddedAt { get; set; }
    }
}