// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:27:48Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// All participant-related streaming events./// @usage/// Use to track participant changes in threads./// </summary>
    public abstract partial class ParticipantEvent
    {
    }
}