// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:15:44Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Prompt Agent (Direct Execution)/// ALIGNED WITH: Agent Schema PromptAgent/// SOURCE: https://github.com/microsoft/AgentSchema (agentschema/model/agent.tsp)/// RATIONALE: Direct execution agent with configured tools and models/// </summary>
    public partial class PromptAgent : AgentDefinition
    {
        /// <summary>/// Agent type discriminator./// ALIGNED WITH: Agent Schema PromptAgent.kind/// </summary>
        [XmlElement("kind")]
        [JsonPropertyName("kind")]
        public override string Kind { get; }

        /// <summary>/// Unique agent identifier./// ALIGNED WITH: Agent Schema PromptAgent.name/// </summary>
        [XmlElement("name")]
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>/// UI display name (human-friendly)./// ALIGNED WITH: Agent Schema PromptAgent.displayName/// ADDITION: Not in original design/// </summary>
        [XmlElement("display-name")]
        [JsonPropertyName("displayName")]
        public string DisplayName { get; set; }

        /// <summary>/// Agent capabilities description./// ALIGNED WITH: Agent Schema PromptAgent.description/// </summary>
        [XmlElement("description")]
        [JsonPropertyName("description")]
        public string Description { get; set; }

        /// <summary>/// Prompt template rendering configuration./// ALIGNED WITH: Agent Schema PromptAgent.template/// ADDITION: Not in original design/// Supports Mustache, Jinja2, and Prompty template formats./// </summary>
        [XmlElement("template")]
        [JsonPropertyName("template")]
        public PromptTemplate? Template { get; set; }

        /// <summary>/// Input parameters structure./// ALIGNED WITH: Agent Schema PromptAgent.inputSchema/// ADDITION: Not in original design/// RATIONALE: Enables structured inputs with validation/// </summary>
        [XmlElement("input-schema")]
        [JsonPropertyName("inputSchema")]
        public JSONSchema? InputSchema { get; set; }

        /// <summary>/// Expected output format./// ALIGNED WITH: Agent Schema PromptAgent.outputSchema/// ADDITION: Not in original design/// RATIONALE: Enables structured outputs (OpenAI structured outputs, etc.)/// </summary>
        [XmlElement("output-schema")]
        [JsonPropertyName("outputSchema")]
        public JSONSchema? OutputSchema { get; set; }

        /// <summary>/// Available tools./// ALIGNED WITH: Agent Schema PromptAgent.tools/// </summary>
        [XmlArray("tools"), XmlArrayItem("a-i-tool")]
        [JsonPropertyName("tools")]
        public List<AITool> Tools { get; set; }

        /// <summary>/// Tool calling behavior./// FROM: Azure Agent API (ToolChoiceBehavior)/// </summary>
        [XmlElement("tool-choice")]
        [JsonPropertyName("toolChoice")]
        public ToolChoiceBehavior? ToolChoice { get; set; }

        /// <summary>/// Custom metadata./// ALIGNED WITH: Agent Schema PromptAgent.metadata/// </summary>
        [XmlElement("metadata")]
        [JsonPropertyName("metadata")]
        public Dictionary<string, object> Metadata { get; set; }

        /// <summary>/// Auto-response configuration for thread participation./// @usage/// Use Cases:/// - Support agents: Respond to user messages in support threads/// - Specialized agents: Respond only when mentioned or when specific content appears/// - Monitoring agents: React to video, files, or other content types/// </summary>
        [XmlElement("auto-response")]
        [JsonPropertyName("autoResponse")]
        public AutoResponseConfig? AutoResponse { get; set; }
    }
}