// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:27:47Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Prompt Template/// ALIGNED WITH: Agent Schema Template/// SOURCE: https://github.com/microsoft/AgentSchema (agentschema/model/template.tsp)/// RATIONALE: Specifies how to render and parse instructions/additionalInstructions/// NOTE: The template content itself is in the instructions/additionalInstructions fields./// This object specifies the rendering engine and parser./// </summary>
    public partial class PromptTemplate
    {
        /// <summary>/// Template rendering engine for slot filling prompts./// ALIGNED WITH: Agent Schema Template.format/// SUPPORTED FORMATS:/// - mustache: Handlebars-style {{variable}}/// - jinja2: Python Jinja2 templates/// - prompty: Prompty format (.prompty files)/// USAGE: Specifies how to render the instructions/additionalInstructions strings/// </summary>
        [XmlElement("format")]
        [JsonPropertyName("format")]
        public string Format { get; set; }

        /// <summary>/// Parser to process the rendered template into API-compatible format./// ALIGNED WITH: Agent Schema Template.parser/// RATIONALE: After rendering the template with variable substitution,/// the parser processes the result into the format expected by the LLM API./// EXAMPLES:/// - prompty: Parse Prompty format into messages/// - markdown: Parse markdown sections into structured content/// - json: Parse JSON structure/// </summary>
        [XmlElement("parser")]
        [JsonPropertyName("parser")]
        public string Parser { get; set; }
    }
}