// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:27:44Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Refusal Content/// FROM: Azure Agent API (RefusalContent)/// ADDITION: Not in MAF/// RATIONALE: Model refuses to complete request (safety/policy)/// M365: Compliance and content policy tracking/// XML: &lt;refusal reason="..."&gt;Detailed refusal message&lt;/refusal&gt;/// </summary>
    [XmlRoot("refusal")]
    public partial class RefusalContent : AIContentBase
    {
        [JsonIgnore]
#pragma warning disable CS1591, CS1587
        public override string Kind => "refusal";
#pragma warning restore CS1591, CS1587
        /// <summary>/// Gets or sets the reason./// </summary>
        [XmlAttribute("reason")]
        [JsonPropertyName("reason")]
        public string Reason { get; set; }
    }
}