// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:27:50Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Remote Condition/// RATIONALE: Custom evaluation logic via remote endpoint/// </summary>
    public partial class RemoteCondition : RunCondition
    {
        /// <summary>/// Condition type discriminator./// </summary>
        [XmlElement("kind")]
        [JsonPropertyName("kind")]
        public override string Kind { get; }

        /// <summary>/// Remote endpoint for custom evaluation logic./// @usage/// Use Cases:/// - Complex business logic (checking external state, database queries)/// - Turn-taking coordination between multiple agents/// - Time-based or rate-limited participation/// </summary>
        [XmlElement("endpoint")]
        [JsonPropertyName("endpoint")]
        public string Endpoint { get; set; }

        /// <summary>/// Authentication for remote endpoint./// </summary>
        [XmlElement("connection")]
        [JsonPropertyName("connection")]
        public Connection? Connection { get; set; }
    }
}