// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:27:50Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Request Usage/// FROM: OpenAI Agents SDK (RequestUsage)/// SOURCE: /openai-agents-python/src/agents/usage.py/// ADDITION: Not in MAF or Azure Agent API/// RATIONALE: Tracks usage for individual LLM API requests within a run/// - Useful for per-request cost calculation/// - Enables accurate cost attribution when requests have different pricing (batch vs real-time)/// M365: Enables detailed cost tracking for multi-turn runs/// </summary>
    public partial class RequestUsage
    {
        /// <summary>/// Gets or sets the input-tokens./// </summary>
        [XmlElement("input-tokens")]
        [JsonPropertyName("inputTokens")]
        public int InputTokens { get; set; }

        /// <summary>/// Gets or sets the output-tokens./// </summary>
        [XmlElement("output-tokens")]
        [JsonPropertyName("outputTokens")]
        public int OutputTokens { get; set; }

        /// <summary>/// Gets or sets the total-tokens./// </summary>
        [XmlElement("total-tokens")]
        [JsonPropertyName("totalTokens")]
        public int TotalTokens { get; set; }

        /// <summary>/// Gets or sets the input-token-details./// </summary>
        [XmlElement("input-token-details")]
        [JsonPropertyName("inputTokenDetails")]
        public InputTokenDetails? InputTokenDetails { get; set; }

        /// <summary>/// Gets or sets the output-token-details./// </summary>
        [XmlElement("output-token-details")]
        [JsonPropertyName("outputTokenDetails")]
        public OutputTokenDetails? OutputTokenDetails { get; set; }

        /// <summary>/// Gets or sets the timestamp./// </summary>
        [XmlElement("timestamp")]
        [JsonPropertyName("timestamp")]
        public DateTime? Timestamp { get; set; }

        /// <summary>/// Gets or sets the metadata./// </summary>
        [XmlElement("metadata")]
        [JsonPropertyName("metadata")]
        public Dictionary<string, object> Metadata { get; set; }
    }
}