// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:27:51Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Represents a review./// </summary>
    [XmlType("review")]
    public partial class Review : ThreadElement
    {
        /// <summary>/// Judges to evaluate final state./// </summary>
        [XmlArray("judges"), XmlArrayItem("judge")]
        [JsonPropertyName("judges")]
        public List<Judge> Judges { get; set; }

        /// <summary>/// Assertions using CEL expressions./// </summary>
        [XmlArray("asserts"), XmlArrayItem("assert")]
        [JsonPropertyName("asserts")]
        public List<Assert> Asserts { get; set; }
    }
}