// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:15:48Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Roles Condition/// RATIONALE: Match based on message role (user, assistant, system, etc.)/// </summary>
    public partial class RolesCondition : RunCondition
    {
        /// <summary>/// Condition type discriminator./// </summary>
        [XmlElement("kind")]
        [JsonPropertyName("kind")]
        public override string Kind { get; }

        /// <summary>/// Message roles that trigger match./// EXAMPLES:/// - ["user"]: Match only user messages/// - ["user", "system"]: Match user or system messages/// </summary>
        [XmlArray("roles"), XmlArrayItem("chat-role")]
        [JsonPropertyName("roles")]
        public List<ChatRole> Roles { get; set; }
    }
}