// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:18:40Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Represents a run./// </summary>
    public partial class Run
    {
        /// <summary>/// Unique identifier for this run./// FROM: Azure Agent API/// GENERATED: Server-generated GUID/// </summary>
        [XmlElement("run-id")]
        [JsonPropertyName("runId")]
        public string RunId { get; set; }

        /// <summary>/// Unique identifier for the agent that processed this run./// FROM: Azure Agent API/// M365: Maps to Agent ID (Entra Object ID in Phase 2)/// </summary>
        [XmlElement("agent-id")]
        [JsonPropertyName("agentId")]
        public string AgentId { get; set; }

        /// <summary>/// Optional identifier for the conversation thread./// FROM: Azure Agent API (required) → Made optional for stateless support/// M365: Links run to conversation in Conversation Store/// OPTIONAL: Allows stateless execution when omitted/// </summary>
        [XmlElement("thread-id")]
        [JsonPropertyName("threadId")]
        public string ThreadId { get; set; }

        /// <summary>/// Optional identifier for the agent's journal./// ADDITION: From M365 Agent Platform (cross-conversation memory)/// M365 REQUIREMENT: Links run to Agent Journal for memory substrate/// - Agent Journal stores knowledge across conversations/// - Different from threadId (single conversation) and sessionId (multi-conversation)/// </summary>
        [XmlElement("journal-id")]
        [JsonPropertyName("journalId")]
        public string JournalId { get; set; }

        /// <summary>/// Current lifecycle status of the run./// FROM: Azure Agent API (5 states) + OpenAI Agents SDK (8 states) + A2A Protocol (interruption states)/// EXPANDED from Azure's 5 states to OpenAI's 8 states plus A2A interruption states:/// - queued: Run is waiting to start (from OpenAI)/// - in_progress: Run is executing (both)/// - requires_action: Tool execution needed (from OpenAI)/// - input_required: Human input needed (from A2A - HITL)/// - auth_required: Authentication needed (from A2A)/// - cancelling: User requested cancellation, run is stopping (from OpenAI)/// - cancelled: Run was cancelled by user before completion (both)/// - failed: Run encountered error (both)/// - completed: Run finished successfully (both)/// - incomplete: Run stopped before completion (both)/// CANCELLATION STATES:/// - cancelling: Transitional state while stopping/// - cancelled: Final state after cancellation complete/// M365: Enables orchestration pipeline to track run state/// </summary>
        [XmlElement("status")]
        [JsonPropertyName("status")]
        public RunStatus Status { get; set; }

        /// <summary>/// Messages generated during this run./// FROM: Azure Agent API (output) + MAF (AgentResponse.Messages)/// M365: These messages are stored in Conversation Store/// </summary>
        [XmlArray("output"), XmlArrayItem("chat-message")]
        [JsonPropertyName("output")]
        public List<ChatMessage> Output { get; set; }

        /// <summary>/// Token usage statistics for this run./// FROM: Azure Agent API (CompletionUsage) + MAF (UsageDetails)/// M365: Tracked for cost management and quotas/// </summary>
        [XmlElement("usage")]
        [JsonPropertyName("usage")]
        public CompletionUsage Usage { get; set; }

        /// <summary>/// Timestamp when the run was created./// FROM: Azure Agent API (createdAt) + OpenAI Agents SDK/// </summary>
        [XmlElement("created-at")]
        [JsonPropertyName("createdAt")]
        public DateTime CreatedAt { get; set; }

        /// <summary>/// Timestamp of last status update./// FROM: OpenAI Agents SDK (updated_at)/// ADDITION: Not in Azure Agent API/// </summary>
        [XmlElement("updated-at")]
        [JsonPropertyName("updatedAt")]
        public DateTime UpdatedAt { get; set; }

        /// <summary>/// Timestamp when the run finished (completed, failed, or cancelled)./// FROM: Azure Agent API (completedAt)/// </summary>
        [XmlElement("completed-at")]
        [JsonPropertyName("completedAt")]
        public DateTime? CompletedAt { get; set; }

        /// <summary>/// Timestamp when the run was cancelled (if status=cancelled)./// ADDITION: User-initiated cancellation tracking/// PURPOSE: Tracks when user clicked "stop generating" or cancelled the run/// </summary>
        [XmlElement("cancelled-at")]
        [JsonPropertyName("cancelledAt")]
        public DateTime? CancelledAt { get; set; }

        /// <summary>/// Reason for cancellation (if provided by user)./// ADDITION: User-initiated cancellation tracking/// PURPOSE: Optional reason for analytics/debugging/// EXAMPLES: "User changed mind", "Cost limit reached", "User navigated away"/// </summary>
        [XmlElement("cancellation-reason")]
        [JsonPropertyName("cancellationReason")]
        public string CancellationReason { get; set; }

        /// <summary>/// Error details if run failed or completed incompletely./// FROM: Azure Agent API (incompleteDetails) - generalized/// GENERALIZED: Generic error model with code + message pattern/// Like HTTP status codes or gRPC status - structured error codes/// that clients can handle programmatically./// M365: Provides user-facing error messages with machine-readable codes/// </summary>
        [XmlElement("error")]
        [JsonPropertyName("error")]
        public RunError? Error { get; set; }

        /// <summary>/// Input messages that started this run./// FROM: Azure Agent API (input)/// NOTE: Only included in create requests, not responses/// </summary>
        [XmlArray("input"), XmlArrayItem("chat-message")]
        [JsonPropertyName("input")]
        public List<ChatMessage> Input { get; set; }

        /// <summary>/// Agent configuration for this run./// FROM: Azure Agent API (agent)/// ALIGNED WITH: Agent Schema AgentDefinition/// OPTIONAL: If omitted, uses existing agent (agentId)/// If provided, executes with inline agent definition (stateless)/// MAPS TO: MAF ExecuteAsync with inline agent configuration/// </summary>
        [XmlElement("agent")]
        [JsonPropertyName("agent")]
        public AgentDefinition? Agent { get; set; }

        /// <summary>/// Optional overrides for existing agent configuration./// FROM: Azure Agent API (part of agent-based completion)/// M365: Enables per-request customization (e.g., different temperature for specific task)/// NOTE: Only applicable for PromptAgent types/// </summary>
        [XmlElement("overrides")]
        [JsonPropertyName("overrides")]
        public PromptAgent? Overrides { get; set; }

        /// <summary>/// Configuration options for run execution./// FROM: Azure Agent API (RunOptions)/// </summary>
        [XmlElement("options")]
        [JsonPropertyName("options")]
        public RunOptions? Options { get; set; }

        /// <summary>/// User who initiated this run./// FROM: Azure Agent API (userId)/// M365: Maps to Entra User ID (Object ID)/// </summary>
        [XmlElement("user-id")]
        [JsonPropertyName("userId")]
        public string UserId { get; set; }

        /// <summary>/// Thread cleanup strategy for this run./// @usage/// Use Cases:/// - POST /runs/wait with threadCleanup=delete: Ephemeral execution/// - POST /runs with threadCleanup=keep: Background run with thread persistence/// - POST /runs with threadCleanup=delete: Background run with auto-cleanup/// M365: Controls whether conversation thread is retained in Conversation Store/// Rationale:/// - keep: Stateful runs, multi-turn conversations (default)/// - delete: Ephemeral runs, one-shot queries (auto-cleanup)/// </summary>
        [XmlElement("thread-cleanup")]
        [JsonPropertyName("threadCleanup")]
        public ThreadCleanup? ThreadCleanup { get; set; }

        /// <summary>/// Webhook URL for run completion notification./// @usage/// Use Cases:/// - Background runs: Create run, return immediately, webhook on completion/// - Long-running tasks: Avoid polling, get notified when done/// - Serverless architectures: Trigger next step via webhook/// </summary>
        [XmlElement("webhook")]
        [JsonPropertyName("webhook")]
        public string Webhook { get; set; }

        /// <summary>/// Custom metadata for the run./// FROM: Azure Agent API (metadata)/// M365: Can store tenant ID, department, cost center, etc./// </summary>
        [XmlElement("metadata")]
        [JsonPropertyName("metadata")]
        public Dictionary<string, object> Metadata { get; set; }

        /// <summary>/// Underlying provider representation./// FROM: MAF (AgentResponse.RawRepresentation)/// Stores the original response from OpenAI/Anthropic/etc for debugging/// </summary>
        [XmlElement("raw-representation")]
        [JsonPropertyName("rawRepresentation")]
        public object RawRepresentation { get; set; }
    }
}