// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:27:46Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Run Options/// FROM: Azure Agent API (RunOptions) + OpenAI Agents SDK (RunOptions/RunConfig)/// </summary>
    public partial class RunOptions
    {
        /// <summary>/// Continuation token for resuming background responses./// FROM: MAF (AgentRunOptions.ContinuationToken)/// </summary>
        [XmlElement("continuation-token")]
        [JsonPropertyName("continuationToken")]
        public string ContinuationToken { get; set; }
    }
}