// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:15:43Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Run Status Enum/// FROM: OpenAI Agents SDK (8 states) + A2A Protocol (interruption states) + LangChain Agent Protocol/// EXPANDED from Azure Agent API (5 states)/// </summary>
    public enum RunStatus
    {
        Queued,
        In_progress,
        Requires_action,
        Input_required,
        Auth_required,
        Cancelling,
        Cancelled,
        Failed,
        Completed,
        Incomplete,
        Timeout
    }
}