// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:18:42Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Run Subscription - Webhook Notification Registration/// @usage/// Use Cases:/// - Monitor long-running executions/// - Track run lifecycle for orchestration/// - Get notified when specific runs complete/// - Build run activity dashboards/// @example Subscribe to run completion/// ```http/// POST /runs/{runId}/subscriptions/// {/// "webhookUrl": "https://example.com/webhook",/// "events": ["run.completed", "run.failed"]/// }/// ```/// </summary>
    public partial class RunSubscription
    {
        /// <summary>/// Unique subscription identifier./// GENERATED: Server-generated GUID/// </summary>
        [XmlElement("subscription-id")]
        [JsonPropertyName("subscriptionId")]
        public string SubscriptionId { get; set; }

        /// <summary>/// Run being subscribed to./// FROM: Parent resource relationship/// </summary>
        [XmlElement("run-id")]
        [JsonPropertyName("runId")]
        public string RunId { get; set; }

        /// <summary>/// Webhook URL to POST notifications to./// REQUIRED: Must be HTTPS endpoint/// WEBHOOK PAYLOAD EXAMPLE:/// {/// "type": "run.activity",/// "resourceId": "run-123",/// "subscriptionId": "sub-456",/// "eventType": "run.started" | "message.created" | "run.completed",/// "sequenceNumber": 42,/// "eventSeq": 10,/// "timestamp": "2026-02-06T10:00:00Z"/// }/// CLIENT ACTION: GET /runs/{runId} to fetch latest state/// </summary>
        [XmlElement("webhook-url")]
        [JsonPropertyName("webhookUrl")]
        public string WebhookUrl { get; set; }

        /// <summary>/// Secret for webhook signature validation./// OPTIONAL: For webhook authenticity verification/// PATTERN: Like GitHub webhook secrets (HMAC-SHA256 signature)/// </summary>
        [XmlElement("webhook-secret")]
        [JsonPropertyName("webhookSecret")]
        public string WebhookSecret { get; set; }

        /// <summary>/// Event types to subscribe to./// DEFAULT: All run events if omitted/// EVENT TYPES:/// - "run.started": Run started executing/// - "message.created": New message in run/// - "message.updated": Message streaming chunk/// - "message.completed": Message streaming finished/// - "run.completed": Run finished successfully/// - "run.failed": Run encountered error/// - "run.cancelled": Run was cancelled/// - "run.timeout": Run exceeded time limit/// - "run.requires_action": Run needs tool execution/// - "run.input_required": Run needs user input/// RATIONALE: Allow filtering to reduce notification volume/// </summary>
        [XmlArray("events"), XmlArrayItem("string")]
        [JsonPropertyName("events")]
        public List<string> Events { get; set; }

        /// <summary>/// Message filters for webhook subscriptions./// OPTIONAL: Filter which messages trigger notifications/// RATIONALE: Reduce noise by filtering out irrelevant messages/// </summary>
        [XmlElement("message-filters")]
        [JsonPropertyName("messageFilters")]
        public MessageFilters? MessageFilters { get; set; }

        /// <summary>/// Subscription expiration time./// OPTIONAL: Subscription automatically deleted after this time/// DEFAULT: No expiration (permanent until explicitly deleted)/// </summary>
        [XmlElement("expires-at")]
        [JsonPropertyName("expiresAt")]
        public DateTime? ExpiresAt { get; set; }

        /// <summary>/// Whether subscription is currently active./// DEFAULT: true/// RATIONALE: Allows temporary disable without deletion/// </summary>
        [XmlElement("active")]
        [JsonPropertyName("active")]
        public bool? Active { get; set; }

        /// <summary>/// Timestamp when subscription was created./// </summary>
        [XmlElement("created-at")]
        [JsonPropertyName("createdAt")]
        public DateTime CreatedAt { get; set; }

        /// <summary>/// Timestamp of last successful webhook delivery./// UPDATED: By server after successful POST (HTTP 200-299)/// </summary>
        [XmlElement("last-delivered-at")]
        [JsonPropertyName("lastDeliveredAt")]
        public DateTime? LastDeliveredAt { get; set; }

        /// <summary>/// Number of consecutive failed delivery attempts./// INCREMENTED: On failed webhook POST (timeout, 4xx, 5xx)/// RESET: On successful delivery/// RATIONALE: Automatic subscription disable after max failures/// </summary>
        [XmlElement("failure-count")]
        [JsonPropertyName("failureCount")]
        public int? FailureCount { get; set; }

        /// <summary>/// Custom metadata for subscription./// FLEXIBLE: Client can store correlation IDs, user info, etc./// </summary>
        [XmlElement("metadata")]
        [JsonPropertyName("metadata")]
        public Dictionary<string, object> Metadata { get; set; }
    }
}