// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:15:43Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Represents a run-wait-response./// </summary>
    public partial class RunWaitResponse
    {
        /// <summary>/// Unique identifier for the completed run./// </summary>
        [XmlElement("run-id")]
        [JsonPropertyName("runId")]
        public string RunId { get; set; }

        /// <summary>/// Thread ID if run was stateful (null for ephemeral runs)./// OPTIONAL: Omitted when threadCleanup=delete/// </summary>
        [XmlElement("thread-id")]
        [JsonPropertyName("threadId")]
        public string ThreadId { get; set; }

        /// <summary>/// Final run status (completed, failed, cancelled, timeout, incomplete)./// </summary>
        [XmlElement("status")]
        [JsonPropertyName("status")]
        public RunStatus Status { get; set; }

        /// <summary>/// Messages generated during the run./// </summary>
        [XmlArray("output"), XmlArrayItem("chat-message")]
        [JsonPropertyName("output")]
        public List<ChatMessage> Output { get; set; }

        /// <summary>/// Token usage statistics./// </summary>
        [XmlElement("usage")]
        [JsonPropertyName("usage")]
        public CompletionUsage? Usage { get; set; }

        /// <summary>/// Error details if run failed or completed incompletely./// </summary>
        [XmlElement("error")]
        [JsonPropertyName("error")]
        public RunError? Error { get; set; }

        /// <summary>/// Timestamp when run was created./// </summary>
        [XmlElement("created-at")]
        [JsonPropertyName("createdAt")]
        public DateTime CreatedAt { get; set; }

        /// <summary>/// Timestamp when run finished./// </summary>
        [XmlElement("completed-at")]
        [JsonPropertyName("completedAt")]
        public DateTime? CompletedAt { get; set; }
    }
}