// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:18:38Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// XML: &lt;search-result title="..." url="..." score="0.94"&gt;&lt;snippet&gt;...&lt;/snippet&gt;&lt;/search-result&gt;/// </summary>
    [XmlRoot("search-result")]
    public partial class SearchResultContent : AIContentBase
    {
        [JsonIgnore]
#pragma warning disable CS1591, CS1587
        public override string Kind => "searchResult";
#pragma warning restore CS1591, CS1587
        /// <summary>/// Gets or sets the title./// </summary>
        [XmlAttribute("title")]
        [JsonPropertyName("title")]
        public string Title { get; set; }

        /// <summary>/// Gets or sets the url./// </summary>
        [XmlAttribute("url")]
        [JsonPropertyName("url")]
        public string Url { get; set; }

        /// <summary>/// Gets or sets the score./// </summary>
        [XmlAttribute("score")]
        [JsonPropertyName("score")]
        public float Score { get; set; }

        /// <summary>/// Gets or sets the snippet./// </summary>
        [XmlElement("snippet")]
        [JsonPropertyName("snippet")]
        public string Snippet { get; set; }
    }
}