// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:15:48Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Similarity Condition/// RATIONALE: Match content based on similarity to reference texts/// USE CASES: Intent matching, topic detection, semantic filtering/// </summary>
    public partial class SimilarityCondition : RunCondition
    {
        /// <summary>/// Condition type discriminator./// </summary>
        [XmlElement("kind")]
        [JsonPropertyName("kind")]
        public override string Kind { get; }

        /// <summary>/// Reference texts for similarity comparison./// EXAMPLES:/// - ["help", "support", "assistance"] for help intent/// - ["urgent", "critical", "emergency"] for priority detection/// </summary>
        [XmlArray("reference-texts"), XmlArrayItem("string")]
        [JsonPropertyName("referenceTexts")]
        public List<string> ReferenceTexts { get; set; }

        /// <summary>/// Similarity threshold (0.0 to 1.0)./// DEFAULT: 0.7/// EXAMPLES:/// - 0.9: Very high similarity required (strict matching)/// - 0.7: Moderate similarity (recommended)/// - 0.5: Low similarity (loose matching)/// </summary>
        [XmlElement("threshold")]
        [JsonPropertyName("threshold")]
        public float Threshold { get; set; }
    }
}