// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:27:44Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Suggested Action/// Represents a single quick reply button/action/// </summary>
    [XmlType("action")]
    public partial class SuggestedAction
    {
        /// <summary>/// Gets or sets the title./// </summary>
        [XmlAttribute("title")]
        [JsonPropertyName("title")]
        public string Title { get; set; }

        /// <summary>/// Gets or sets the action-type./// </summary>
        [XmlAttribute("type")]
        [JsonPropertyName("actionType")]
        public string ActionType { get; set; }

        /// <summary>/// Gets or sets the value./// </summary>
        [XmlAttribute("value")]
        [JsonPropertyName("value")]
        public string Value { get; set; }

        /// <summary>/// Gets or sets the text./// </summary>
        [XmlAttribute("text")]
        [JsonPropertyName("text")]
        public string Text { get; set; }
    }
}