// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:15:42Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// XML: &lt;suggested-actions&gt;&lt;action title="Yes" type="message" value="yes" /&gt;&lt;/suggested-actions&gt;/// </summary>
    [XmlRoot("suggested-actions")]
    public partial class SuggestedActionsContent : AIContentBase
    {
        [JsonIgnore]
#pragma warning disable CS1591, CS1587
        public override string Kind => "suggestedActions";
#pragma warning restore CS1591, CS1587
        /// <summary>/// Gets or sets the actions./// </summary>
        [XmlElement("action")]
        [JsonPropertyName("actions")]
        public List<SuggestedAction> Actions { get; set; }
    }
}