// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:27:45Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Thread Base/// Common properties shared by all thread types./// SHARED BY:/// - Thread: Runtime conversation threads/// - EvalThread: Evaluation test threads/// PROPERTIES:/// - threadId: Unique identifier/// - status: Lifecycle state (active, closed, archived)/// - createdAt: Creation timestamp/// - metadata: Custom key-value data/// </summary>
    public partial class ThreadBase
    {
        /// <summary>/// Unique thread identifier./// FROM: Azure Agent API/// GENERATED: Server-generated GUID/// M365: Maps to Conversation Key in Conversation Store/// </summary>
        [XmlAttribute("thread-id")]
        [JsonPropertyName("threadId")]
        public string ThreadId { get; set; }

        /// <summary>/// Thread lifecycle status./// FROM: Activity Protocol (EndOfConversation, ConversationUpdate patterns)/// STATES:/// - active: Thread is active and accepting messages (default)/// - closed: Conversation ended but retained for history/// - archived: Thread archived and not accepting new messages/// </summary>
        [XmlAttribute("status")]
        [JsonPropertyName("status")]
        public ThreadStatus? Status { get; set; }

        /// <summary>/// Timestamp when thread was created./// </summary>
        [XmlAttribute("created-at")]
        [JsonPropertyName("createdAt")]
        public DateTime CreatedAt { get; set; }

        /// <summary>/// Custom metadata for the thread./// FROM: Azure Agent API/// M365: Can store conversation metadata (topic, participants, etc.)/// NOT SERIALIZED: Used for API metadata only/// </summary>
        [XmlIgnore]
        [JsonIgnore]
        public Dictionary<string, object> Metadata { get; set; }
    }
}