// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:15:45Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Represents a thread-closed-event./// </summary>
    public partial class ThreadClosedEvent : ThreadEvent
    {
        /// <summary>/// Gets or sets the thread-id./// </summary>
        [XmlElement("thread-id")]
        [JsonPropertyName("threadId")]
        public string ThreadId { get; set; }

        /// <summary>/// Gets or sets the event-seq./// </summary>
        [XmlElement("event-seq")]
        [JsonPropertyName("eventSeq")]
        public long EventSeq { get; set; }

        /// <summary>/// Gets or sets the closed-by./// </summary>
        [XmlElement("closed-by")]
        [JsonPropertyName("closedBy")]
        public string ClosedBy { get; set; }

        /// <summary>/// Gets or sets the reason./// </summary>
        [XmlElement("reason")]
        [JsonPropertyName("reason")]
        public string Reason { get; set; }

        /// <summary>/// Gets or sets the closed-at./// </summary>
        [XmlElement("closed-at")]
        [JsonPropertyName("closedAt")]
        public DateTime ClosedAt { get; set; }
    }
}