// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:18:39Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Thread Watch - Agent Participation Tracking/// @usage/// Use Cases:/// - Support agents: Watch support threads for user messages/// - Monitoring agents: Watch threads for specific content types/// - Multi-agent: Multiple agents watching same thread with different conditions/// </summary>
    public partial class ThreadWatch
    {
        /// <summary>/// Unique watch identifier./// GENERATED: Server-generated GUID/// </summary>
        [XmlElement("watch-id")]
        [JsonPropertyName("watchId")]
        public string WatchId { get; set; }

        /// <summary>/// Thread being watched./// REQUIRED: Must be valid threadId/// </summary>
        [XmlElement("thread-id")]
        [JsonPropertyName("threadId")]
        public string ThreadId { get; set; }

        /// <summary>/// Agent watching the thread./// REQUIRED: Must be valid agentId with autoResponse configuration/// VALIDATION:/// - Agent must exist/// - Agent must have AutoResponseConfig defined/// - AutoResponseConfig.runCondition determines when agent participates/// </summary>
        [XmlElement("agent-id")]
        [JsonPropertyName("agentId")]
        public string AgentId { get; set; }

        /// <summary>/// Whether watch is currently active./// DEFAULT: true/// RATIONALE: Allows temporary disable without deletion/// - false: Watch exists but agent doesn't evaluate for participation/// - true: Agent actively watching and evaluating conditions/// </summary>
        [XmlElement("active")]
        [JsonPropertyName("active")]
        public bool? Active { get; set; }

        /// <summary>/// Timestamp when watch was created./// </summary>
        [XmlElement("created-at")]
        [JsonPropertyName("createdAt")]
        public DateTime CreatedAt { get; set; }

        /// <summary>/// Timestamp of last activation (last time agent created run for this thread)./// UPDATED: By server after each automatic run creation/// </summary>
        [XmlElement("last-activated-at")]
        [JsonPropertyName("lastActivatedAt")]
        public DateTime? LastActivatedAt { get; set; }

        /// <summary>/// Number of runs created by this watch./// INCREMENTED: Each time agent automatically creates run/// RATIONALE: Analytics and monitoring/// </summary>
        [XmlElement("activation-count")]
        [JsonPropertyName("activationCount")]
        public int? ActivationCount { get; set; }

        /// <summary>/// Custom metadata for watch./// FLEXIBLE: Client can store correlation IDs, user info, etc./// </summary>
        [XmlElement("metadata")]
        [JsonPropertyName("metadata")]
        public Dictionary<string, object> Metadata { get; set; }
    }
}