// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:18:42Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Represents a thread-reopened-event./// </summary>
    public partial class ThreadReopenedEvent : ThreadEvent
    {
        /// <summary>/// Gets or sets the thread-id./// </summary>
        [XmlElement("thread-id")]
        [JsonPropertyName("threadId")]
        public string ThreadId { get; set; }

        /// <summary>/// Gets or sets the event-seq./// </summary>
        [XmlElement("event-seq")]
        [JsonPropertyName("eventSeq")]
        public long EventSeq { get; set; }

        /// <summary>/// Gets or sets the reopened-by./// </summary>
        [XmlElement("reopened-by")]
        [JsonPropertyName("reopenedBy")]
        public string ReopenedBy { get; set; }

        /// <summary>/// Gets or sets the reopened-at./// </summary>
        [XmlElement("reopened-at")]
        [JsonPropertyName("reopenedAt")]
        public DateTime ReopenedAt { get; set; }
    }
}