// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:15:42Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Thread Status Enum/// RATIONALE: Type-safe status values for thread lifecycle/// ALIGNED WITH: Messaging app conversation states/// - active: Thread is ongoing (like WhatsApp/Teams active chat)/// - closed: Thread is completed but archived (like closed ticket)/// - archived: Thread is hidden from active view (like archived email)/// </summary>
    public enum ThreadStatus
    {
        Active,
        Closed,
        Archived
    }
}