// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:27:46Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Tool Call Result/// ADDITION: Tool execution result for protocol-level tool calling/// REPRESENTS: Result from executing a tool/function/// USED BY: Hosting SDKs to return tool execution results to LLM/// </summary>
    public partial class ToolCallResult
    {
        /// <summary>/// Gets or sets the call-id./// </summary>
        [XmlElement("call-id")]
        [JsonPropertyName("callId")]
        public string CallId { get; set; }

        /// <summary>/// Gets or sets the result./// </summary>
        [XmlElement("result")]
        [JsonPropertyName("result")]
        public string Result { get; set; }

        /// <summary>/// Gets or sets the error./// </summary>
        [XmlElement("error")]
        [JsonPropertyName("error")]
        public ToolExecutionError? Error { get; set; }
    }
}