// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:15:44Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Tool Call Request/// ADDITION: Tool execution request for protocol-level tool calling/// REPRESENTS: Request to execute a tool/function with specific arguments/// USED BY: Hosting SDKs when LLM requests tool execution/// </summary>
    public partial class ToolCallRequest
    {
        /// <summary>/// Gets or sets the call-id./// </summary>
        [XmlElement("call-id")]
        [JsonPropertyName("callId")]
        public string CallId { get; set; }

        /// <summary>/// Gets or sets the tool-name./// </summary>
        [XmlElement("tool-name")]
        [JsonPropertyName("toolName")]
        public string ToolName { get; set; }

        /// <summary>/// Gets or sets the arguments./// </summary>
        [XmlElement("arguments")]
        [JsonPropertyName("arguments")]
        public string Arguments { get; set; }
    }
}