// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:18:38Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Tool message./// </summary>
    [XmlRoot("tool")]
    public partial class ToolMessage : ChatMessage
    {
        [JsonIgnore]
#pragma warning disable CS1591
        public override ChatRole Role => ChatRole.Tool;
#pragma warning restore CS1591
        /// <summary>/// Gets or sets the call-id./// </summary>
        [XmlAttribute("call-id")]
        public new string? CallId { get; set; }

        /// <summary>/// Gets or sets the name./// </summary>
        [XmlAttribute("name")]
        public new string? Name { get; set; }

        /// <summary>/// Gets or sets the content items for this tool message./// </summary>
        [XmlElement("function-result", Type = typeof(FunctionResultContent)), XmlElement("error", Type = typeof(ErrorContent))]
        public new List<AIContent> Contents { get; set; } = new List<AIContent>();
    }
}
// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:18:38Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

