// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:27:46Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Tool Execution Error/// ADDITION: Error that occurred during tool execution/// REPRESENTS: Structured error information for tool failures/// USED BY: Hosting SDKs to report tool execution errors/// </summary>
    public partial class ToolExecutionError
    {
        /// <summary>/// Gets or sets the code./// </summary>
        [XmlElement("code")]
        [JsonPropertyName("code")]
        public string Code { get; set; }

        /// <summary>/// Gets or sets the message./// </summary>
        [XmlElement("message")]
        [JsonPropertyName("message")]
        public string Message { get; set; }

        /// <summary>/// Gets or sets the details./// </summary>
        [XmlElement("details")]
        [JsonPropertyName("details")]
        public Dictionary<string, object> Details { get; set; }

        /// <summary>/// Gets or sets the stack-trace./// </summary>
        [XmlElement("stack-trace")]
        [JsonPropertyName("stackTrace")]
        public string StackTrace { get; set; }
    }
}