// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:27:46Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Represents a tool-lifecycle-hooks./// </summary>
    public partial class ToolLifecycleHooks
    {
        /// <summary>/// Executed before tool invocation./// EXAMPLES:/// - Validate parameters/// - Check permissions/// - Log invocation/// - Apply input guardrails/// </summary>
        [XmlElement("before-execute")]
        [JsonPropertyName("beforeExecute")]
        public LifecycleHook? BeforeExecute { get; set; }

        /// <summary>/// Executed after successful tool invocation./// EXAMPLES:/// - Validate output/// - Persist result to memory/// - Log completion/// - Apply output guardrails/// </summary>
        [XmlElement("after-execute")]
        [JsonPropertyName("afterExecute")]
        public LifecycleHook? AfterExecute { get; set; }

        /// <summary>/// Executed when tool invocation fails./// EXAMPLES:/// - Log error/// - Send alert/// - Fallback behavior/// </summary>
        [XmlElement("on-error")]
        [JsonPropertyName("onError")]
        public LifecycleHook? OnError { get; set; }
    }
}