// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:15:43Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Tool Output/// @usage/// Use Cases:/// - Tool approval: Human reviews delete_file before execution/// - External execution: Tools executed by external system, results fed back/// - Modified execution: Human modifies tool arguments before running/// </summary>
    public partial class ToolOutput
    {
        /// <summary>/// Tool call ID this output corresponds to./// MUST: Match callId from FunctionCallContent in required_action.tool_calls/// </summary>
        [XmlElement("tool_call_id")]
        [JsonPropertyName("tool_call_id")]
        public string Tool_call_id { get; set; }

        /// <summary>/// Tool execution result./// FLEXIBLE: String output or structured data (serialized to string)/// EXAMPLES:/// - Simple: "File deleted successfully"/// - JSON: "{\"status\":\"success\",\"files_deleted\":3}"/// - Error: "Permission denied: /protected/file.txt"/// </summary>
        [XmlElement("output")]
        [JsonPropertyName("output")]
        public string Output { get; set; }
    }
}