// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:18:38Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// XML: &lt;trace name="..." label="..." severity="information" timestamp="..."&gt;{value}&lt;/trace&gt;/// </summary>
    [XmlRoot("trace")]
    public partial class TraceContent : AIContentBase
    {
        [JsonIgnore]
#pragma warning disable CS1591, CS1587
        public override string Kind => "trace";
#pragma warning restore CS1591, CS1587
        /// <summary>/// Gets or sets the name./// </summary>
        [XmlAttribute("name")]
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>/// Gets or sets the label./// </summary>
        [XmlAttribute("label")]
        [JsonPropertyName("label")]
        public string Label { get; set; }

        /// <summary>/// Gets or sets the severity./// </summary>
        [XmlAttribute("severity")]
        [JsonPropertyName("severity")]
        public string Severity { get; set; }

        /// <summary>/// Gets or sets the timestamp./// </summary>
        [XmlAttribute("timestamp")]
        [JsonPropertyName("timestamp")]
        public DateTime Timestamp { get; set; }

        /// <summary>/// Gets or sets the value./// </summary>
        [XmlText]
        [JsonPropertyName("value")]
        public string Value { get; set; }
    }
}