// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:15:42Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// XML: &lt;typing-indicator from="user_123" status="typing" timestamp="..." /&gt;/// </summary>
    [XmlRoot("typing-indicator")]
    public partial class TypingIndicatorContent : AIContentBase
    {
        [JsonIgnore]
#pragma warning disable CS1591, CS1587
        public override string Kind => "typingIndicator";
#pragma warning restore CS1591, CS1587
        /// <summary>/// Gets or sets the from./// </summary>
        [XmlAttribute("from")]
        [JsonPropertyName("from")]
        public string From { get; set; }

        /// <summary>/// Gets or sets the timestamp./// </summary>
        [XmlAttribute("timestamp")]
        [JsonPropertyName("timestamp")]
        public DateTime Timestamp { get; set; }
    }
}