// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:15:42Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// URI Content/// BASE: Microsoft.Extensions.AI.UriContent/// SOURCE: /extensions/src/Libraries/Microsoft.Extensions.AI.Abstractions/Contents/UriContent.cs/// REPRESENTS: Reference to external content via URI/// XML: &lt;uri&gt;https://example.com&lt;/uri&gt;/// </summary>
    [XmlRoot("uri")]
    public partial class UriContent : AIContentBase
    {
        [JsonIgnore]
#pragma warning disable CS1591, CS1587
        public override string Kind => "uri";
#pragma warning restore CS1591, CS1587
        /// <summary>/// Gets or sets the uri./// </summary>
        [XmlText]
        [JsonPropertyName("uri")]
        public string Uri { get; set; }
    }
}