// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:27:50Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Usage Details (MAF-Compatible)/// BASE: Microsoft.Extensions.AI.UsageDetails/// SOURCE: /extensions/src/Libraries/Microsoft.Extensions.AI.Abstractions/UsageDetails.cs/// RATIONALE: Provides compatibility with MAF's usage tracking pattern/// while maintaining TypeSpec naming conventions/// NOTE: This is essentially an alias/wrapper for CompletionUsage/// </summary>
    public partial class UsageDetails
    {
        /// <summary>/// Input token count./// BASE: MAF UsageDetails.InputTokenCount/// </summary>
        [XmlElement("input-token-count")]
        [JsonPropertyName("inputTokenCount")]
        public long? InputTokenCount { get; set; }

        /// <summary>/// Output token count./// BASE: MAF UsageDetails.OutputTokenCount/// </summary>
        [XmlElement("output-token-count")]
        [JsonPropertyName("outputTokenCount")]
        public long? OutputTokenCount { get; set; }

        /// <summary>/// Total token count./// BASE: MAF UsageDetails.TotalTokenCount/// </summary>
        [XmlElement("total-token-count")]
        [JsonPropertyName("totalTokenCount")]
        public long? TotalTokenCount { get; set; }

        /// <summary>/// Cached input token count./// BASE: MAF UsageDetails.CachedInputTokenCount/// </summary>
        [XmlElement("cached-input-token-count")]
        [JsonPropertyName("cachedInputTokenCount")]
        public long? CachedInputTokenCount { get; set; }

        /// <summary>/// Reasoning token count./// BASE: MAF UsageDetails.ReasoningTokenCount/// </summary>
        [XmlElement("reasoning-token-count")]
        [JsonPropertyName("reasoningTokenCount")]
        public long? ReasoningTokenCount { get; set; }

        /// <summary>/// Additional counts./// BASE: MAF UsageDetails.AdditionalCounts/// </summary>
        [XmlElement("additional-counts")]
        [JsonPropertyName("additionalCounts")]
        public Dictionary<string, object> AdditionalCounts { get; set; }
    }
}