// <auto-generated>
// This code was generated by TypeSpec Code Generator on 2026-02-10T09:27:48Z.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Text.Json.Serialization;

namespace Microsoft.Agents
{
    /// <summary>/// Represents a webhook-notification./// </summary>
    public partial class WebhookNotification
    {
        /// <summary>/// Gets or sets the resource-id./// </summary>
        [XmlElement("resource-id")]
        [JsonPropertyName("resourceId")]
        public string ResourceId { get; set; }

        /// <summary>/// Gets or sets the subscription-id./// </summary>
        [XmlElement("subscription-id")]
        [JsonPropertyName("subscriptionId")]
        public string SubscriptionId { get; set; }

        /// <summary>/// Gets or sets the event-type./// </summary>
        [XmlElement("event-type")]
        [JsonPropertyName("eventType")]
        public string EventType { get; set; }

        /// <summary>/// Gets or sets the sequence-number./// </summary>
        [XmlElement("sequence-number")]
        [JsonPropertyName("sequenceNumber")]
        public long SequenceNumber { get; set; }

        /// <summary>/// Gets or sets the event-seq./// </summary>
        [XmlElement("event-seq")]
        [JsonPropertyName("eventSeq")]
        public long EventSeq { get; set; }

        /// <summary>/// Gets or sets the timestamp./// </summary>
        [XmlElement("timestamp")]
        [JsonPropertyName("timestamp")]
        public DateTime Timestamp { get; set; }

        /// <summary>/// Gets or sets the message-id./// </summary>
        [XmlElement("message-id")]
        [JsonPropertyName("messageId")]
        public string MessageId { get; set; }

        /// <summary>/// Gets or sets the run-id./// </summary>
        [XmlElement("run-id")]
        [JsonPropertyName("runId")]
        public string RunId { get; set; }

        /// <summary>/// Gets or sets the status./// </summary>
        [XmlElement("status")]
        [JsonPropertyName("status")]
        public string Status { get; set; }
    }
}