using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using Xunit;
using FluentAssertions;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.Agents;
using Microsoft.Agents.Abstractions.Models;
using Microsoft.Agents.Xml.Serialization;
using QuickStart;

namespace Microsoft.Agents.Protocol.Tests.EchoM365.Compliance;

/// <summary>
/// AUTO-GENERATED: EchoM365 TypeSpec compliance tests.
/// Generated from: specs/typespec/messages.tsp
///
/// Verifies that EchoM365 conforms to Agent Framework Protocol specification.
/// Tests cover:
/// - Message structure (ChatMessage, role, contents)
/// - Required properties (messageId, role, contents)
/// - XML/JSON serialization
/// - Content type support
/// - Message ID preservation
///
/// DO NOT EDIT THIS FILE MANUALLY.
/// Regenerate with: python scripts/generation/generate-tests.py --compliance
/// </summary>
public class EchoM365ComplianceTests : IClassFixture<WebApplicationFactory<Program>>
{
    private readonly HttpClient _client;
    private readonly MessageSerializer _serializer;

    public EchoM365ComplianceTests(WebApplicationFactory<Program> factory)
    {
        _client = factory.CreateClient();
        _serializer = new MessageSerializer();
    }

    #region Message Structure Tests

    [Fact]
    public async Task EchoM365_AcceptsValidUserMessage()
    {
        // Arrange: Create valid UserMessage per TypeSpec
        var message = new UserMessage
        {
            MessageId = "msg_compliance_001",
            UserId = "user_test_123",
            CreatedAt = DateTime.UtcNow,
            Contents = new List<AIContent>
            {
                new TextContent { Text = "Hello EchoM365" }
            }
        };

        var xml = _serializer.Serialize(message);
        var content = new StringContent(xml, Encoding.UTF8, "application/xml");

        // Act: POST to /api/messages
        var response = await _client.PostAsync("/api/messages", content);

        // Assert: 200 OK with AgentMessage
        response.StatusCode.Should().Be(HttpStatusCode.OK);

        var responseXml = await response.Content.ReadAsStringAsync();
        var responseMessage = _serializer.Deserialize(responseXml);

        responseMessage.Should().NotBeNull();
        responseMessage.Should().BeOfType<AgentMessage>();

        var agentMsg = (AgentMessage)responseMessage;
        agentMsg.MessageId.Should().NotBeNullOrEmpty();
        agentMsg.Role.Should().Be(ChatRole.Agent);
        agentMsg.Contents.Should().NotBeEmpty();
    }

    [Fact]
    public async Task EchoM365_RequiresMessageId()
    {
        // Arrange: Create UserMessage WITHOUT messageId (invalid per TypeSpec)
        var xml = @"
            <user user-id=""user_123"">
                <text>Hello</text>
            </user>";

        var content = new StringContent(xml, Encoding.UTF8, "application/xml");

        // Act: POST to /api/messages
        var response = await _client.PostAsync("/api/messages", content);

        // Assert: 400 Bad Request (messageId is required per TypeSpec)
        response.StatusCode.Should().Be(HttpStatusCode.BadRequest,
            "messageId is marked as required (@key) in TypeSpec");
    }

    [Fact]
    public async Task EchoM365_PreservesMessageStructure()
    {
        // Arrange
        var message = new UserMessage
        {
            MessageId = "msg_preserve_001",
            UserId = "user_test_456",
            AuthorName = "Test User",
            CreatedAt = new DateTime(2026, 2, 7, 10, 0, 0, DateTimeKind.Utc),
            Contents = new List<AIContent>
            {
                new TextContent { Text = "Test message" }
            }
        };

        var xml = _serializer.Serialize(message);
        var content = new StringContent(xml, Encoding.UTF8, "application/xml");

        // Act
        var response = await _client.PostAsync("/api/messages", content);
        var responseXml = await response.Content.ReadAsStringAsync();
        var responseMessage = (AgentMessage)_serializer.Deserialize(responseXml);

        // Assert: AgentMessage has all required ChatMessage properties
        responseMessage.MessageId.Should().NotBeNullOrEmpty(
            "messageId is required per TypeSpec @key annotation");
        responseMessage.Role.Should().Be(ChatRole.Agent,
            "role must match message type");
        responseMessage.Contents.Should().NotBeEmpty(
            "contents array is required per TypeSpec");
    }

    #endregion

    #region Role Handling Tests

    [Fact]
    public async Task EchoM365_HandlesSystemRole()
    {
        // Arrange: Create SystemMessage per TypeSpec
        var message = new SystemMessage
        {
            MessageId = "msg_system_001",
            Content = "Test system role"
        };

        var xml = _serializer.Serialize(message);
        var content = new StringContent(xml, Encoding.UTF8, "application/xml");

        // Act
        var response = await _client.PostAsync("/api/messages", content);

        // Assert: Bot can process system messages
        response.StatusCode.Should().Be(HttpStatusCode.OK,
            "Bot should accept messages with role=system");
    }

    [Fact]
    public async Task EchoM365_HandlesDeveloperRole()
    {
        // Arrange: Create DeveloperMessage per TypeSpec
        var message = new DeveloperMessage
        {
            MessageId = "msg_developer_001",
            Content = "Test developer role"
        };

        var xml = _serializer.Serialize(message);
        var content = new StringContent(xml, Encoding.UTF8, "application/xml");

        // Act
        var response = await _client.PostAsync("/api/messages", content);

        // Assert: Bot can process developer messages
        response.StatusCode.Should().Be(HttpStatusCode.OK,
            "Bot should accept messages with role=developer");
    }

    [Fact]
    public async Task EchoM365_HandlesUserRole()
    {
        // Arrange: Create UserMessage per TypeSpec
        var message = new UserMessage
        {
            MessageId = "msg_user_001",
            Contents = new List<AIContent>
            {
                new TextContent { Text = "Test user role" }
            }
        };

        var xml = _serializer.Serialize(message);
        var content = new StringContent(xml, Encoding.UTF8, "application/xml");

        // Act
        var response = await _client.PostAsync("/api/messages", content);

        // Assert: Bot can process user messages
        response.StatusCode.Should().Be(HttpStatusCode.OK,
            "Bot should accept messages with role=user");
    }

    [Fact]
    public async Task EchoM365_HandlesAgentRole()
    {
        // Arrange: Create AgentMessage per TypeSpec
        var message = new AgentMessage
        {
            MessageId = "msg_agent_001",
            Contents = new List<AIContent>
            {
                new TextContent { Text = "Test agent role" }
            }
        };

        var xml = _serializer.Serialize(message);
        var content = new StringContent(xml, Encoding.UTF8, "application/xml");

        // Act
        var response = await _client.PostAsync("/api/messages", content);

        // Assert: Bot can process agent messages
        response.StatusCode.Should().Be(HttpStatusCode.OK,
            "Bot should accept messages with role=agent");
    }

    [Fact]
    public async Task EchoM365_HandlesToolRole()
    {
        // Arrange: Create ToolMessage per TypeSpec
        var message = new ToolMessage
        {
            MessageId = "msg_tool_001",
            Contents = new List<AIContent>
            {
                new FunctionResultContent
                {
                    CallId = "call_001",
                    Name = "test_tool",
                    Result = "Test tool result",
                    Audience = "agent"
                }
            }
        };

        var xml = _serializer.Serialize(message);
        var content = new StringContent(xml, Encoding.UTF8, "application/xml");

        // Act
        var response = await _client.PostAsync("/api/messages", content);

        // Assert: Bot can process tool messages
        response.StatusCode.Should().Be(HttpStatusCode.OK,
            "Bot should accept messages with role=tool");
    }

    [Fact]
    public async Task EchoM365_HandlesChannelRole()
    {
        // Arrange: Create ChannelMessage per TypeSpec
        var message = new ChannelMessage
        {
            MessageId = "msg_channel_001",
            Contents = new List<AIContent>
            {
                new EventContent
                {
                    Name = "test_event",
                    Timestamp = DateTime.UtcNow,
                    Value = "Test channel event value"
                }
            }
        };

        var xml = _serializer.Serialize(message);
        var content = new StringContent(xml, Encoding.UTF8, "application/xml");

        // Act
        var response = await _client.PostAsync("/api/messages", content);

        // Assert: Bot can process channel messages
        response.StatusCode.Should().Be(HttpStatusCode.OK,
            "Bot should accept messages with role=channel");
    }


    #endregion

    #region Content Type Tests

    [Fact]
    public async Task EchoM365_HandlesTextContent()
    {
        // Arrange
        var message = new UserMessage
        {
            MessageId = "msg_text_001",
            Contents = new List<AIContent>
            {
                new TextContent { Text = "Hello bot!" }
            }
        };

        // Act
        var response = await PostMessage(message);

        // Assert
        response.Should().BeOfType<AgentMessage>();
        var agentMsg = (AgentMessage)response;

        var textContent = agentMsg.Contents.OfType<TextContent>().First();
        textContent.Text.Should().Contain("You said:");
    }

    #endregion

    #region Serialization Tests

    [Theory]
    [InlineData("application/xml")]
    [InlineData("application/json")]
    public async Task EchoM365_SupportsContentTypes(string contentType)
    {
        // Arrange
        var message = new UserMessage
        {
            MessageId = "msg_serialization_001",
            Contents = new List<AIContent>
            {
                new TextContent { Text = "Test serialization" }
            }
        };

        string serialized;
        if (contentType.Contains("xml"))
        {
            serialized = _serializer.Serialize(message);
        }
        else
        {
            // TODO: Add JSON serialization support
            serialized = _serializer.Serialize(message);
        }

        var content = new StringContent(serialized, Encoding.UTF8, contentType);

        // Act
        var response = await _client.PostAsync("/api/messages", content);

        // Assert
        response.StatusCode.Should().Be(HttpStatusCode.OK);
        response.Content.Headers.ContentType?.MediaType.Should().Be(contentType);
    }

    [Fact]
    public async Task EchoM365_ProducesValidXml()
    {
        // Arrange
        var message = new UserMessage
        {
            MessageId = "msg_xml_001",
            Contents = new List<AIContent>
            {
                new TextContent { Text = "Test XML" }
            }
        };

        var xml = _serializer.Serialize(message);
        var content = new StringContent(xml, Encoding.UTF8, "application/xml");

        // Act
        var response = await _client.PostAsync("/api/messages", content);
        var responseXml = await response.Content.ReadAsStringAsync();

        // Assert: Response is valid XML per TypeSpec schema
        var responseMessage = _serializer.Deserialize(responseXml);
        responseMessage.Should().NotBeNull("Response must be valid XML");

        // Validate XML structure
        responseXml.Should().Contain("<agent", "Response must be AgentMessage");
        responseXml.Should().Contain("message-id=", "message-id attribute required");
        responseXml.Should().Contain("<text>", "TextContent required");
    }

    #endregion

    #region Round-Trip Tests

    [Fact]
    public async Task EchoM365_RoundTrips_PreservesStructure()
    {
        // Arrange: Original message
        var original = new UserMessage
        {
            MessageId = "msg_roundtrip_001",
            UserId = "user_roundtrip_123",
            CreatedAt = new DateTime(2026, 2, 7, 10, 0, 0, DateTimeKind.Utc),
            Contents = new List<AIContent>
            {
                new TextContent { Text = "Test round-trip" }
            }
        };

        // Act: Serialize → Send → Receive → Deserialize
        var xmlRequest = _serializer.Serialize(original);
        var response = await _client.PostAsync("/api/messages",
            new StringContent(xmlRequest, Encoding.UTF8, "application/xml"));
        var xmlResponse = await response.Content.ReadAsStringAsync();
        var responseMessage = _serializer.Deserialize(xmlResponse);

        // Assert: Response is valid AgentMessage
        responseMessage.Should().BeOfType<AgentMessage>();
        var agentMsg = (AgentMessage)responseMessage;

        // Verify structure preservation per TypeSpec
        agentMsg.MessageId.Should().NotBeNullOrEmpty("messageId required");
        agentMsg.Role.Should().Be(ChatRole.Agent, "role must match type");
        agentMsg.Contents.Should().NotBeEmpty("contents required");

        // Verify XML schema compliance
        ValidateXmlStructure(xmlResponse);
    }

    #endregion

    #region Helper Methods

    private async Task<ChatMessage> PostMessage(ChatMessage message)
    {
        var xml = _serializer.Serialize(message);
        var content = new StringContent(xml, Encoding.UTF8, "application/xml");

        var response = await _client.PostAsync("/api/messages", content);
        response.StatusCode.Should().Be(HttpStatusCode.OK);

        var responseXml = await response.Content.ReadAsStringAsync();
        return _serializer.Deserialize(responseXml);
    }

    private void ValidateXmlStructure(string xml)
    {
        // Basic XML validation
        xml.Should().NotBeNullOrWhiteSpace();
        xml.Should().Contain("<", "Must be valid XML");

        // Must have root element
        var doc = System.Xml.Linq.XDocument.Parse(xml);
        doc.Root.Should().NotBeNull("Must have root element");

        // Must have message-id attribute
        doc.Root!.Attribute("message-id").Should().NotBeNull(
            "message-id is required per TypeSpec @key annotation");
    }

    #endregion
}
