using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Formatting;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace Microsoft.Agents.CodeGen.Utilities;

/// <summary>
/// Common utilities for Roslyn-based code generation.
/// Consolidated from multiple generators to ensure consistency.
/// </summary>
public static class CodeGenerationUtilities
{
    /// <summary>
    /// Creates XML documentation comment trivia from documentation text.
    /// </summary>
    /// <param name="documentation">Documentation text (may contain multiple lines)</param>
    /// <param name="maxLines">Maximum number of documentation lines to include (default: unlimited)</param>
    /// <returns>SyntaxTriviaList containing XML comment trivia</returns>
    public static SyntaxTriviaList CreateXmlComment(string documentation, int maxLines = int.MaxValue)
    {
        if (string.IsNullOrWhiteSpace(documentation))
        {
            // Return minimal summary for empty documentation
            return TriviaList(
                Comment("/// <summary>"),
                Comment("/// </summary>"),
                CarriageReturnLineFeed
            );
        }

        var lines = documentation.Split('\n')
            .Select(line => line.Trim())
            .Where(line => !string.IsNullOrWhiteSpace(line))
            .Take(maxLines);

        var triviaList = new List<SyntaxTrivia>
        {
            Comment("/// <summary>")
        };

        foreach (var line in lines)
        {
            // Escape XML special characters in documentation
            var escapedLine = EscapeXmlComment(line);
            triviaList.Add(Comment($"/// {escapedLine}"));
        }

        triviaList.Add(Comment("/// </summary>"));
        triviaList.Add(CarriageReturnLineFeed);

        return TriviaList(triviaList);
    }

    /// <summary>
    /// Formats a Roslyn CompilationUnitSyntax using standard formatting rules and adds auto-generated header.
    /// </summary>
    /// <param name="compilationUnit">The compilation unit to format</param>
    /// <returns>Formatted code as a string with auto-generated header</returns>
    public static string FormatCode(CompilationUnitSyntax compilationUnit)
    {
        using var workspace = new AdhocWorkspace();
        var formatted = Formatter.Format(compilationUnit, workspace);
        var code = formatted.ToFullString();

        // Prepend auto-generated header
        var timestamp = DateTime.UtcNow.ToString("yyyy-MM-ddTHH:mm:ssZ");
        var header = $@"// <auto-generated>
// This code was generated by TypeSpec Code Generator on {timestamp}.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// To modify this file, edit the TypeSpec source and regenerate.
// </auto-generated>

";
        return header + code;
    }

    /// <summary>
    /// Creates an auto-generated file header comment.
    /// </summary>
    /// <param name="generatorName">Name of the generator (e.g., "TypeSpec Code Generator")</param>
    /// <returns>SyntaxTriviaList containing auto-generated header comment</returns>
    public static SyntaxTriviaList CreateAutoGeneratedHeader(string generatorName = "TypeSpec Code Generator")
    {
        var timestamp = DateTime.UtcNow.ToString("yyyy-MM-ddTHH:mm:ssZ");

        return TriviaList(
            Comment("// <auto-generated>"),
            CarriageReturnLineFeed,
            Comment($"// This code was generated by {generatorName} on {timestamp}."),
            CarriageReturnLineFeed,
            Comment("// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated."),
            CarriageReturnLineFeed,
            Comment("// To modify this file, edit the TypeSpec source and regenerate."),
            CarriageReturnLineFeed,
            Comment("// </auto-generated>"),
            CarriageReturnLineFeed,
            CarriageReturnLineFeed
        );
    }

    /// <summary>
    /// Escapes XML special characters in documentation text.
    /// </summary>
    /// <param name="text">Text to escape</param>
    /// <returns>Escaped text safe for XML comments</returns>
    private static string EscapeXmlComment(string text)
    {
        return text
            .Replace("&", "&amp;")
            .Replace("<", "&lt;")
            .Replace(">", "&gt;");
    }
}
