#!/usr/bin/env python3
"""
Generate SDK types from TypeSpec definitions.

Supports Python, C#, and TypeScript generation using the .NET code generator.
"""

import argparse
import shutil
import subprocess
import sys
from pathlib import Path
from typing import List, Optional


# TypeSpec files to generate from (in order)
TYPESPEC_FILES = [
    "messages",      # Core message types
    "threads",       # Thread/conversation types
    "execution",     # Run/execution types
    "tools",         # Tool/function types
    "agents",        # Agent configuration types
    "streaming",     # SSE streaming event types
    "subscriptions", # Webhook subscription types
    "common",        # Common/shared types
    "usage",         # Token usage types (CompletionUsage, etc.)
    "conditions",    # Condition types (RunCondition, etc.)
    "eval",          # Evaluation types (ThreadElement, EvalThread, Expect, etc.)
]


class SDKGenerator:
    """Generate SDK types from TypeSpec."""

    def __init__(self, language: str, repo_root: Path, dry_run: bool = False):
        self.language = language
        self.repo_root = repo_root
        self.dry_run = dry_run
        self.typespec_dir = repo_root / "typespec"
        self.codegen_project = repo_root / "dotnet" / "src" / "Microsoft.Agents.CodeGen"

        # Find dotnet (skip in dry-run mode)
        if not dry_run:
            self.dotnet = self._find_dotnet()
        else:
            self.dotnet = "dotnet"

    def _find_dotnet(self) -> str:
        """Find dotnet executable."""
        if shutil.which("dotnet"):
            return "dotnet"

        # Try macOS default path
        macos_path = "/usr/local/share/dotnet/dotnet"
        if Path(macos_path).exists():
            return macos_path

        print("❌ Error: dotnet not found")
        print("Install .NET SDK from https://dotnet.microsoft.com/download")
        sys.exit(1)

    def _get_output_config(self):
        """Get language-specific output configuration."""
        if self.language == "python":
            return {
                "output_base": self.repo_root / "python" / "microsoft-agents-protocol-abstractions" / "microsoft" / "agents",
                "namespace": "microsoft.agents",
                "subdir": "models"
            }
        elif self.language == "csharp":
            return {
                "output_base": self.repo_root / "dotnet" / "src" / "Microsoft.Agents.Protocol.Abstractions",
                "namespace": "Microsoft.Agents",
                "subdir": "Models"
            }
        elif self.language == "typescript":
            return {
                "output_base": self.repo_root / "typescript" / "packages" / "agents-protocol-abstractions" / "src",
                "namespace": "",
                "subdir": "generated"
            }
        else:
            raise ValueError(f"Unknown language: {self.language}")

    def _clean_output(self, output_dir: Path):
        """Clean previous generated files."""
        print(f"🧹 Cleaning previous generated files...")

        if output_dir.exists():
            # Remove all files except __init__.py (for Python)
            for file in output_dir.glob("*"):
                if file.is_file() and file.name != "__init__.py":
                    file.unlink()
                elif file.is_dir():
                    shutil.rmtree(file)

        output_dir.mkdir(parents=True, exist_ok=True)

    def _create_init_file(self, output_dir: Path):
        """Create __init__.py for Python packages."""
        if self.language == "python":
            init_file = output_dir / "__init__.py"
            init_file.write_text('''# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

"""
Generated models from TypeSpec definitions.

This module is autogenerated - DO NOT EDIT MANUALLY.
Run scripts/codegen/generate_sdk.py --lang python to regenerate.
"""

# Exports will be added during code generation
__all__ = []
''')

    def _build_python_init(self, output_dir: Path):
        """Build complete __init__.py with all exports from generated files."""
        print(f"📦 Building complete __init__.py...")

        # Python reserved keywords that need underscore suffix
        PYTHON_RESERVED = {
            "and", "as", "assert", "async", "await", "break", "class", "continue", "def",
            "del", "elif", "else", "except", "finally", "for", "from", "global", "if",
            "import", "in", "is", "lambda", "nonlocal", "not", "or", "pass", "raise",
            "return", "try", "while", "with", "yield"
        }

        # Collect all Python files (excluding __init__.py)
        py_files = sorted([f for f in output_dir.glob("*.py") if f.name != "__init__.py"])

        if not py_files:
            print("  ⚠️  No Python files found to export")
            return

        # Extract type names from each file and map them to their source file
        type_to_file = {}  # Maps type name to source module name (without .py)
        for py_file in py_files:
            content = py_file.read_text()
            module_name = py_file.stem  # File name without extension

            # Extract class names (class ClassName:)
            import re
            class_pattern = r'^class\s+(\w+)'

            for match in re.finditer(class_pattern, content, re.MULTILINE):
                class_name = match.group(1)
                type_to_file[class_name] = module_name

            # Extract type aliases (TypeName = Union[...] or TypeName = ...)
            # Look for patterns like: ThreadElement = Union[...] or CancelActionType = Literal[...]
            type_alias_pattern = r'^([A-Z]\w+)\s*=\s*'
            for match in re.finditer(type_alias_pattern, content, re.MULTILINE):
                type_name = match.group(1)
                type_to_file[type_name] = module_name

        exports = sorted(type_to_file.keys())

        if not exports:
            print("  ⚠️  No exportable types found")
            return

        # Build __init__.py content
        init_content = '''# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

"""
Generated models from TypeSpec definitions.

This module is autogenerated - DO NOT EDIT MANUALLY.
Run scripts/codegen/generate_sdk.py --lang python to regenerate.
"""

'''

        # Add imports using the actual file mapping
        for export_name in exports:
            module_name = type_to_file[export_name]
            init_content += f"from .{module_name} import {export_name}\n"

        init_content += "\n__all__ = [\n"
        for export_name in exports:
            init_content += f"    '{export_name}',\n"
        init_content += "]\n"

        # Write __init__.py
        init_file = output_dir / "__init__.py"
        init_file.write_text(init_content)

        print(f"  ✅ Exported {len(exports)} types")

    def generate(self):
        """Generate SDK types."""
        config = self._get_output_config()
        output_dir = config["output_base"] / config["subdir"]

        lang_display = {
            "python": "Python",
            "csharp": "C#",
            "typescript": "TypeScript"
        }[self.language]

        print("╔" + "=" * 56 + "╗")
        print(f"║       {lang_display} Type Generation from TypeSpec".ljust(57) + "║")
        print("╚" + "=" * 56 + "╝")
        print()

        # Dry-run mode: show what would be generated without writing files
        if self.dry_run:
            print("🔍 DRY RUN - Preview of generation")
            print()
            print(f"Would generate {lang_display} types from {len(TYPESPEC_FILES)} TypeSpec files:")
            for file in TYPESPEC_FILES:
                typespec_file = self.typespec_dir / f"{file}.tsp"
                status = "✓" if typespec_file.exists() else "✗ (missing)"
                print(f"  - {file}.tsp {status}")
            print()
            print(f"Output directory: {output_dir}")
            print()
            print("🔍 Dry run complete - no files were written")
            print("   Run without --dry-run to generate files")
            return

        # Clean output
        self._clean_output(output_dir)

        # Create init file if needed
        self._create_init_file(output_dir)

        # Generate from each TypeSpec file
        total = len(TYPESPEC_FILES)
        for i, file in enumerate(TYPESPEC_FILES, 1):
            print()
            print(f"[{i}/{total}] Generating from {file}.tsp...")

            typespec_file = self.typespec_dir / f"{file}.tsp"
            if not typespec_file.exists():
                print(f"⚠️  Skipping {file}.tsp (not found)")
                continue

            # Build command
            cmd = [
                self.dotnet, "run",
                "--project", str(self.codegen_project),
            ]

            # Add --no-build for C# to avoid circular dependency during generation
            if self.language == "csharp":
                cmd.append("--no-build")

            cmd.extend([
                "--",
                "--typespec", str(typespec_file),
                "--language", self.language,
                "--output", str(output_dir),
            ])

            if config["namespace"]:
                cmd.extend(["--namespace", config["namespace"]])

            # Run generation
            try:
                result = subprocess.run(
                    cmd,
                    capture_output=True,
                    text=True,
                    check=True
                )
                # Filter out NuGet warnings
                for line in result.stdout.split('\n'):
                    if 'warning NU' not in line and line.strip():
                        print(f"  {line}")
            except subprocess.CalledProcessError as e:
                print(f"❌ Error generating {file}.tsp:")
                print(e.stderr)
                sys.exit(1)

        # Post-process: Build complete __init__.py for Python
        if self.language == "python":
            self._build_python_init(output_dir)

        print()
        print("╔" + "=" * 56 + "╗")
        print(f"║     ✅ {lang_display} types generated successfully!".ljust(57) + "║")
        print("╚" + "=" * 56 + "╝")
        print()
        print(f"Output directory: {output_dir}")
        print(f"Generated from: {total} TypeSpec files")
        print()


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Generate SDK types from TypeSpec (optionally for all languages)"
    )
    parser.add_argument(
        "--lang",
        choices=["python", "csharp", "typescript", "all"],
        default="all",
        help="Target language for generation (default: all)"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Preview changes without writing files"
    )

    args = parser.parse_args()

    script_dir = Path(__file__).parent
    repo_root = script_dir.parent.parent

    # Generate for all languages if --lang all or no --lang specified
    if args.lang == "all":
        print("╔" + "=" * 56 + "╗")
        print("║          Agent Protocol Code Generation                ║")
        print("╚" + "=" * 56 + "╝")
        print()
        if args.dry_run:
            print("🔍 DRY RUN - Previewing generation for all languages...")
        else:
            print("Generating SDK types for all languages...")
        print()

        for lang in ["csharp", "typescript", "python"]:
            print(f"\n{'='*60}")
            print(f"{'[DRY RUN] ' if args.dry_run else ''}Generating {lang.upper()}")
            print('='*60 + "\n")
            generator = SDKGenerator(lang, repo_root, dry_run=args.dry_run)
            generator.generate()

        if not args.dry_run:
            print()
            print("╔" + "=" * 56 + "╗")
            print("║              ✅ All SDKs Generated!                     ║")
            print("╚" + "=" * 56 + "╝")
            print()
    else:
        generator = SDKGenerator(args.lang, repo_root, dry_run=args.dry_run)
        generator.generate()


if __name__ == "__main__":
    main()
